/*
 *  Copyright (c) 2023, Stefan Johnson
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without modification,
 *  are permitted provided that the following conditions are met:
 *
 *  1. Redistributions of source code must retain the above copyright notice, this list
 *     of conditions and the following disclaimer.
 *  2. Redistributions in binary form must reproduce the above copyright notice, this
 *     list of conditions and the following disclaimer in the documentation and/or other
 *     materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

//generic_imp.rb: -pc 1 -n 'CC_BITS' -t CommonC/BitsTemplate.h -th '<CommonC/BitsTemplate.h>' -m 'Tbase' 'T=PTYPE(Tbase *)'
#ifndef T
#define T PTYPE(Tbase *)
#endif

#include <CommonC/Generics.h>

#define CCBitsGet(set, index) CCBitsGet_Ref(set, index)(set, index)
#define CCBitsSet(set, index) CCBitsSet_Ref(set, index)(set, index)
#define CCBitsClear(set, index) CCBitsClear_Ref(set, index)(set, index)
#define CCBitsAssign(set, index, value) CCBitsAssign_Ref(set, index, value)(set, index, value)
#define CCBitsSetRange(set, index, count) CCBitsSetRange_Ref(set, index, count)(set, index, count)
#define CCBitsClearRange(set, index, count) CCBitsClearRange_Ref(set, index, count)(set, index, count)
#define CCBitsCount(set, index, count) CCBitsCount_Ref(set, index, count)(set, index, count)
#define CCBitsAny(set, index, count) CCBitsAny_Ref(set, index, count)(set, index, count)
#define CCBitsMask(seta, setb, index, count, indexes) CCBitsMask_Ref(seta, setb, index, count, indexes)(seta, setb, index, count, indexes)
#define CCBitsNot(set, index, count) CCBitsNot_Ref(set, index, count)(set, index, count)
#define CCBitsOr(seta, setb, index, count) CCBitsOr_Ref(seta, setb, index, count)(seta, setb, index, count)
#define CCBitsAnd(seta, setb, index, count) CCBitsAnd_Ref(seta, setb, index, count)(seta, setb, index, count)
#define CCBitsXor(seta, setb, index, count) CCBitsXor_Ref(seta, setb, index, count)(seta, setb, index, count)
#define CCBitsCopy(seta, setb, index, count) CCBitsCopy_Ref(seta, setb, index, count)(seta, setb, index, count)

#define CCBitsGet_Ref(set, index) CC_GENERIC((((typeof(set)){0})), CCBitsGet_T, CC_GENERIC_MATCH, CC_GENERIC_ERROR, (CC_BITS_T))
#define CCBitsSet_Ref(set, index) CC_GENERIC((((typeof(set)){0})), CCBitsSet_T, CC_GENERIC_MATCH, CC_GENERIC_ERROR, (CC_BITS_T))
#define CCBitsClear_Ref(set, index) CC_GENERIC((((typeof(set)){0})), CCBitsClear_T, CC_GENERIC_MATCH, CC_GENERIC_ERROR, (CC_BITS_T))
#define CCBitsAssign_Ref(set, index, value) CC_GENERIC((((typeof(set)){0})), CCBitsAssign_T, CC_GENERIC_MATCH, CC_GENERIC_ERROR, (CC_BITS_T))
#define CCBitsSetRange_Ref(set, index, count) CC_GENERIC((((typeof(set)){0})), CCBitsSetRange_T, CC_GENERIC_MATCH, CC_GENERIC_ERROR, (CC_BITS_T))
#define CCBitsClearRange_Ref(set, index, count) CC_GENERIC((((typeof(set)){0})), CCBitsClearRange_T, CC_GENERIC_MATCH, CC_GENERIC_ERROR, (CC_BITS_T))
#define CCBitsCount_Ref(set, index, count) CC_GENERIC((((typeof(set)){0})), CCBitsCount_T, CC_GENERIC_MATCH, CC_GENERIC_ERROR, (CC_BITS_T))
#define CCBitsAny_Ref(set, index, count) CC_GENERIC((((typeof(set)){0})), CCBitsAny_T, CC_GENERIC_MATCH, CC_GENERIC_ERROR, (CC_BITS_T))
#define CCBitsMask_Ref(seta, setb, index, count, indexes) CC_GENERIC((((typeof(seta)){0})), CCBitsMask_T, CC_GENERIC_MATCH, CC_GENERIC_ERROR, (CC_BITS_T))
#define CCBitsNot_Ref(set, index, count) CC_GENERIC((((typeof(set)){0})), CCBitsNot_T, CC_GENERIC_MATCH, CC_GENERIC_ERROR, (CC_BITS_T))
#define CCBitsOr_Ref(seta, setb, index, count) CC_GENERIC((((typeof(seta)){0})), CCBitsOr_T, CC_GENERIC_MATCH, CC_GENERIC_ERROR, (CC_BITS_T))
#define CCBitsAnd_Ref(seta, setb, index, count) CC_GENERIC((((typeof(seta)){0})), CCBitsAnd_T, CC_GENERIC_MATCH, CC_GENERIC_ERROR, (CC_BITS_T))
#define CCBitsXor_Ref(seta, setb, index, count) CC_GENERIC((((typeof(seta)){0})), CCBitsXor_T, CC_GENERIC_MATCH, CC_GENERIC_ERROR, (CC_BITS_T))
#define CCBitsCopy_Ref(seta, setb, index, count) CC_GENERIC((((typeof(seta)){0})), CCBitsCopy_T, CC_GENERIC_MATCH, CC_GENERIC_ERROR, (CC_BITS_T))

#define CC_BITS_T CC_GENERIC_INDEXED_TYPE_LIST(CC_BITS_T, CC_BITS_COUNT)

#ifndef CC_MANGLE_TYPE_CC_BITS_T0
#define CC_MANGLE_TYPE_CC_BITS_T0 CC_BITS_T0
#endif

#ifndef CC_MANGLE_TYPE_CC_BITS_T1
#define CC_MANGLE_TYPE_CC_BITS_T1 CC_BITS_T1
#endif

#ifndef CC_MANGLE_TYPE_CC_BITS_T2
#define CC_MANGLE_TYPE_CC_BITS_T2 CC_BITS_T2
#endif

#ifndef CC_MANGLE_TYPE_CC_BITS_T3
#define CC_MANGLE_TYPE_CC_BITS_T3 CC_BITS_T3
#endif

#ifndef CC_MANGLE_TYPE_CC_BITS_T4
#define CC_MANGLE_TYPE_CC_BITS_T4 CC_BITS_T4
#endif

#ifndef CC_MANGLE_TYPE_CC_BITS_T5
#define CC_MANGLE_TYPE_CC_BITS_T5 CC_BITS_T5
#endif

#ifndef CC_MANGLE_TYPE_CC_BITS_T6
#define CC_MANGLE_TYPE_CC_BITS_T6 CC_BITS_T6
#endif

#ifndef CC_MANGLE_TYPE_CC_BITS_T7
#define CC_MANGLE_TYPE_CC_BITS_T7 CC_BITS_T7
#endif

#ifndef CC_MANGLE_TYPE_CC_BITS_T8
#define CC_MANGLE_TYPE_CC_BITS_T8 CC_BITS_T8
#endif

#ifndef CC_MANGLE_TYPE_CC_BITS_T9
#define CC_MANGLE_TYPE_CC_BITS_T9 CC_BITS_T9
#endif

#ifndef CC_MANGLE_TYPE_CC_BITS_T10
#define CC_MANGLE_TYPE_CC_BITS_T10 CC_BITS_T10
#endif

#ifndef CC_MANGLE_TYPE_CC_BITS_T11
#define CC_MANGLE_TYPE_CC_BITS_T11 CC_BITS_T11
#endif

#ifndef CC_MANGLE_TYPE_CC_BITS_T12
#define CC_MANGLE_TYPE_CC_BITS_T12 CC_BITS_T12
#endif

#ifndef CC_MANGLE_TYPE_CC_BITS_T13
#define CC_MANGLE_TYPE_CC_BITS_T13 CC_BITS_T13
#endif

#ifndef CC_MANGLE_TYPE_CC_BITS_T14
#define CC_MANGLE_TYPE_CC_BITS_T14 CC_BITS_T14
#endif

#ifndef CC_MANGLE_TYPE_CC_BITS_T15
#define CC_MANGLE_TYPE_CC_BITS_T15 CC_BITS_T15
#endif

#ifndef CC_MANGLE_TYPE_CC_BITS_T16
#define CC_MANGLE_TYPE_CC_BITS_T16 CC_BITS_T16
#endif

#ifndef CC_MANGLE_TYPE_CC_BITS_T17
#define CC_MANGLE_TYPE_CC_BITS_T17 CC_BITS_T17
#endif

#ifndef CC_MANGLE_TYPE_CC_BITS_T18
#define CC_MANGLE_TYPE_CC_BITS_T18 CC_BITS_T18
#endif

#ifndef CC_MANGLE_TYPE_CC_BITS_T19
#define CC_MANGLE_TYPE_CC_BITS_T19 CC_BITS_T19
#endif

#define CC_MANGLE_TYPE_0_CC_BITS_T0 CC_MANGLE_TYPE_CC_BITS_T0
#define CC_MANGLE_TYPE_1_CC_BITS_T0 CC_MANGLE_TYPE_CC_BITS_T0
#define CC_MANGLE_TYPE_2_CC_BITS_T0 CC_MANGLE_TYPE_CC_BITS_T0
#define CC_MANGLE_TYPE_3_CC_BITS_T0 CC_MANGLE_TYPE_CC_BITS_T0
#define CC_MANGLE_TYPE_4_CC_BITS_T0 CC_MANGLE_TYPE_CC_BITS_T0
#define CC_MANGLE_TYPE_5_CC_BITS_T0 CC_MANGLE_TYPE_CC_BITS_T0
#define CC_MANGLE_TYPE_6_CC_BITS_T0 CC_MANGLE_TYPE_CC_BITS_T0
#define CC_MANGLE_TYPE_7_CC_BITS_T0 CC_MANGLE_TYPE_CC_BITS_T0
#define CC_MANGLE_TYPE_8_CC_BITS_T0 CC_MANGLE_TYPE_CC_BITS_T0
#define CC_MANGLE_TYPE_9_CC_BITS_T0 CC_MANGLE_TYPE_CC_BITS_T0
#define CC_MANGLE_TYPE_0_CC_BITS_T1 CC_MANGLE_TYPE_CC_BITS_T1
#define CC_MANGLE_TYPE_1_CC_BITS_T1 CC_MANGLE_TYPE_CC_BITS_T1
#define CC_MANGLE_TYPE_2_CC_BITS_T1 CC_MANGLE_TYPE_CC_BITS_T1
#define CC_MANGLE_TYPE_3_CC_BITS_T1 CC_MANGLE_TYPE_CC_BITS_T1
#define CC_MANGLE_TYPE_4_CC_BITS_T1 CC_MANGLE_TYPE_CC_BITS_T1
#define CC_MANGLE_TYPE_5_CC_BITS_T1 CC_MANGLE_TYPE_CC_BITS_T1
#define CC_MANGLE_TYPE_6_CC_BITS_T1 CC_MANGLE_TYPE_CC_BITS_T1
#define CC_MANGLE_TYPE_7_CC_BITS_T1 CC_MANGLE_TYPE_CC_BITS_T1
#define CC_MANGLE_TYPE_8_CC_BITS_T1 CC_MANGLE_TYPE_CC_BITS_T1
#define CC_MANGLE_TYPE_9_CC_BITS_T1 CC_MANGLE_TYPE_CC_BITS_T1
#define CC_MANGLE_TYPE_0_CC_BITS_T2 CC_MANGLE_TYPE_CC_BITS_T2
#define CC_MANGLE_TYPE_1_CC_BITS_T2 CC_MANGLE_TYPE_CC_BITS_T2
#define CC_MANGLE_TYPE_2_CC_BITS_T2 CC_MANGLE_TYPE_CC_BITS_T2
#define CC_MANGLE_TYPE_3_CC_BITS_T2 CC_MANGLE_TYPE_CC_BITS_T2
#define CC_MANGLE_TYPE_4_CC_BITS_T2 CC_MANGLE_TYPE_CC_BITS_T2
#define CC_MANGLE_TYPE_5_CC_BITS_T2 CC_MANGLE_TYPE_CC_BITS_T2
#define CC_MANGLE_TYPE_6_CC_BITS_T2 CC_MANGLE_TYPE_CC_BITS_T2
#define CC_MANGLE_TYPE_7_CC_BITS_T2 CC_MANGLE_TYPE_CC_BITS_T2
#define CC_MANGLE_TYPE_8_CC_BITS_T2 CC_MANGLE_TYPE_CC_BITS_T2
#define CC_MANGLE_TYPE_9_CC_BITS_T2 CC_MANGLE_TYPE_CC_BITS_T2
#define CC_MANGLE_TYPE_0_CC_BITS_T3 CC_MANGLE_TYPE_CC_BITS_T3
#define CC_MANGLE_TYPE_1_CC_BITS_T3 CC_MANGLE_TYPE_CC_BITS_T3
#define CC_MANGLE_TYPE_2_CC_BITS_T3 CC_MANGLE_TYPE_CC_BITS_T3
#define CC_MANGLE_TYPE_3_CC_BITS_T3 CC_MANGLE_TYPE_CC_BITS_T3
#define CC_MANGLE_TYPE_4_CC_BITS_T3 CC_MANGLE_TYPE_CC_BITS_T3
#define CC_MANGLE_TYPE_5_CC_BITS_T3 CC_MANGLE_TYPE_CC_BITS_T3
#define CC_MANGLE_TYPE_6_CC_BITS_T3 CC_MANGLE_TYPE_CC_BITS_T3
#define CC_MANGLE_TYPE_7_CC_BITS_T3 CC_MANGLE_TYPE_CC_BITS_T3
#define CC_MANGLE_TYPE_8_CC_BITS_T3 CC_MANGLE_TYPE_CC_BITS_T3
#define CC_MANGLE_TYPE_9_CC_BITS_T3 CC_MANGLE_TYPE_CC_BITS_T3
#define CC_MANGLE_TYPE_0_CC_BITS_T4 CC_MANGLE_TYPE_CC_BITS_T4
#define CC_MANGLE_TYPE_1_CC_BITS_T4 CC_MANGLE_TYPE_CC_BITS_T4
#define CC_MANGLE_TYPE_2_CC_BITS_T4 CC_MANGLE_TYPE_CC_BITS_T4
#define CC_MANGLE_TYPE_3_CC_BITS_T4 CC_MANGLE_TYPE_CC_BITS_T4
#define CC_MANGLE_TYPE_4_CC_BITS_T4 CC_MANGLE_TYPE_CC_BITS_T4
#define CC_MANGLE_TYPE_5_CC_BITS_T4 CC_MANGLE_TYPE_CC_BITS_T4
#define CC_MANGLE_TYPE_6_CC_BITS_T4 CC_MANGLE_TYPE_CC_BITS_T4
#define CC_MANGLE_TYPE_7_CC_BITS_T4 CC_MANGLE_TYPE_CC_BITS_T4
#define CC_MANGLE_TYPE_8_CC_BITS_T4 CC_MANGLE_TYPE_CC_BITS_T4
#define CC_MANGLE_TYPE_9_CC_BITS_T4 CC_MANGLE_TYPE_CC_BITS_T4
#define CC_MANGLE_TYPE_0_CC_BITS_T5 CC_MANGLE_TYPE_CC_BITS_T5
#define CC_MANGLE_TYPE_1_CC_BITS_T5 CC_MANGLE_TYPE_CC_BITS_T5
#define CC_MANGLE_TYPE_2_CC_BITS_T5 CC_MANGLE_TYPE_CC_BITS_T5
#define CC_MANGLE_TYPE_3_CC_BITS_T5 CC_MANGLE_TYPE_CC_BITS_T5
#define CC_MANGLE_TYPE_4_CC_BITS_T5 CC_MANGLE_TYPE_CC_BITS_T5
#define CC_MANGLE_TYPE_5_CC_BITS_T5 CC_MANGLE_TYPE_CC_BITS_T5
#define CC_MANGLE_TYPE_6_CC_BITS_T5 CC_MANGLE_TYPE_CC_BITS_T5
#define CC_MANGLE_TYPE_7_CC_BITS_T5 CC_MANGLE_TYPE_CC_BITS_T5
#define CC_MANGLE_TYPE_8_CC_BITS_T5 CC_MANGLE_TYPE_CC_BITS_T5
#define CC_MANGLE_TYPE_9_CC_BITS_T5 CC_MANGLE_TYPE_CC_BITS_T5
#define CC_MANGLE_TYPE_0_CC_BITS_T6 CC_MANGLE_TYPE_CC_BITS_T6
#define CC_MANGLE_TYPE_1_CC_BITS_T6 CC_MANGLE_TYPE_CC_BITS_T6
#define CC_MANGLE_TYPE_2_CC_BITS_T6 CC_MANGLE_TYPE_CC_BITS_T6
#define CC_MANGLE_TYPE_3_CC_BITS_T6 CC_MANGLE_TYPE_CC_BITS_T6
#define CC_MANGLE_TYPE_4_CC_BITS_T6 CC_MANGLE_TYPE_CC_BITS_T6
#define CC_MANGLE_TYPE_5_CC_BITS_T6 CC_MANGLE_TYPE_CC_BITS_T6
#define CC_MANGLE_TYPE_6_CC_BITS_T6 CC_MANGLE_TYPE_CC_BITS_T6
#define CC_MANGLE_TYPE_7_CC_BITS_T6 CC_MANGLE_TYPE_CC_BITS_T6
#define CC_MANGLE_TYPE_8_CC_BITS_T6 CC_MANGLE_TYPE_CC_BITS_T6
#define CC_MANGLE_TYPE_9_CC_BITS_T6 CC_MANGLE_TYPE_CC_BITS_T6
#define CC_MANGLE_TYPE_0_CC_BITS_T7 CC_MANGLE_TYPE_CC_BITS_T7
#define CC_MANGLE_TYPE_1_CC_BITS_T7 CC_MANGLE_TYPE_CC_BITS_T7
#define CC_MANGLE_TYPE_2_CC_BITS_T7 CC_MANGLE_TYPE_CC_BITS_T7
#define CC_MANGLE_TYPE_3_CC_BITS_T7 CC_MANGLE_TYPE_CC_BITS_T7
#define CC_MANGLE_TYPE_4_CC_BITS_T7 CC_MANGLE_TYPE_CC_BITS_T7
#define CC_MANGLE_TYPE_5_CC_BITS_T7 CC_MANGLE_TYPE_CC_BITS_T7
#define CC_MANGLE_TYPE_6_CC_BITS_T7 CC_MANGLE_TYPE_CC_BITS_T7
#define CC_MANGLE_TYPE_7_CC_BITS_T7 CC_MANGLE_TYPE_CC_BITS_T7
#define CC_MANGLE_TYPE_8_CC_BITS_T7 CC_MANGLE_TYPE_CC_BITS_T7
#define CC_MANGLE_TYPE_9_CC_BITS_T7 CC_MANGLE_TYPE_CC_BITS_T7
#define CC_MANGLE_TYPE_0_CC_BITS_T8 CC_MANGLE_TYPE_CC_BITS_T8
#define CC_MANGLE_TYPE_1_CC_BITS_T8 CC_MANGLE_TYPE_CC_BITS_T8
#define CC_MANGLE_TYPE_2_CC_BITS_T8 CC_MANGLE_TYPE_CC_BITS_T8
#define CC_MANGLE_TYPE_3_CC_BITS_T8 CC_MANGLE_TYPE_CC_BITS_T8
#define CC_MANGLE_TYPE_4_CC_BITS_T8 CC_MANGLE_TYPE_CC_BITS_T8
#define CC_MANGLE_TYPE_5_CC_BITS_T8 CC_MANGLE_TYPE_CC_BITS_T8
#define CC_MANGLE_TYPE_6_CC_BITS_T8 CC_MANGLE_TYPE_CC_BITS_T8
#define CC_MANGLE_TYPE_7_CC_BITS_T8 CC_MANGLE_TYPE_CC_BITS_T8
#define CC_MANGLE_TYPE_8_CC_BITS_T8 CC_MANGLE_TYPE_CC_BITS_T8
#define CC_MANGLE_TYPE_9_CC_BITS_T8 CC_MANGLE_TYPE_CC_BITS_T8
#define CC_MANGLE_TYPE_0_CC_BITS_T9 CC_MANGLE_TYPE_CC_BITS_T9
#define CC_MANGLE_TYPE_1_CC_BITS_T9 CC_MANGLE_TYPE_CC_BITS_T9
#define CC_MANGLE_TYPE_2_CC_BITS_T9 CC_MANGLE_TYPE_CC_BITS_T9
#define CC_MANGLE_TYPE_3_CC_BITS_T9 CC_MANGLE_TYPE_CC_BITS_T9
#define CC_MANGLE_TYPE_4_CC_BITS_T9 CC_MANGLE_TYPE_CC_BITS_T9
#define CC_MANGLE_TYPE_5_CC_BITS_T9 CC_MANGLE_TYPE_CC_BITS_T9
#define CC_MANGLE_TYPE_6_CC_BITS_T9 CC_MANGLE_TYPE_CC_BITS_T9
#define CC_MANGLE_TYPE_7_CC_BITS_T9 CC_MANGLE_TYPE_CC_BITS_T9
#define CC_MANGLE_TYPE_8_CC_BITS_T9 CC_MANGLE_TYPE_CC_BITS_T9
#define CC_MANGLE_TYPE_9_CC_BITS_T9 CC_MANGLE_TYPE_CC_BITS_T9
#define CC_MANGLE_TYPE_0_CC_BITS_T10 CC_MANGLE_TYPE_CC_BITS_T10
#define CC_MANGLE_TYPE_1_CC_BITS_T10 CC_MANGLE_TYPE_CC_BITS_T10
#define CC_MANGLE_TYPE_2_CC_BITS_T10 CC_MANGLE_TYPE_CC_BITS_T10
#define CC_MANGLE_TYPE_3_CC_BITS_T10 CC_MANGLE_TYPE_CC_BITS_T10
#define CC_MANGLE_TYPE_4_CC_BITS_T10 CC_MANGLE_TYPE_CC_BITS_T10
#define CC_MANGLE_TYPE_5_CC_BITS_T10 CC_MANGLE_TYPE_CC_BITS_T10
#define CC_MANGLE_TYPE_6_CC_BITS_T10 CC_MANGLE_TYPE_CC_BITS_T10
#define CC_MANGLE_TYPE_7_CC_BITS_T10 CC_MANGLE_TYPE_CC_BITS_T10
#define CC_MANGLE_TYPE_8_CC_BITS_T10 CC_MANGLE_TYPE_CC_BITS_T10
#define CC_MANGLE_TYPE_9_CC_BITS_T10 CC_MANGLE_TYPE_CC_BITS_T10
#define CC_MANGLE_TYPE_0_CC_BITS_T11 CC_MANGLE_TYPE_CC_BITS_T11
#define CC_MANGLE_TYPE_1_CC_BITS_T11 CC_MANGLE_TYPE_CC_BITS_T11
#define CC_MANGLE_TYPE_2_CC_BITS_T11 CC_MANGLE_TYPE_CC_BITS_T11
#define CC_MANGLE_TYPE_3_CC_BITS_T11 CC_MANGLE_TYPE_CC_BITS_T11
#define CC_MANGLE_TYPE_4_CC_BITS_T11 CC_MANGLE_TYPE_CC_BITS_T11
#define CC_MANGLE_TYPE_5_CC_BITS_T11 CC_MANGLE_TYPE_CC_BITS_T11
#define CC_MANGLE_TYPE_6_CC_BITS_T11 CC_MANGLE_TYPE_CC_BITS_T11
#define CC_MANGLE_TYPE_7_CC_BITS_T11 CC_MANGLE_TYPE_CC_BITS_T11
#define CC_MANGLE_TYPE_8_CC_BITS_T11 CC_MANGLE_TYPE_CC_BITS_T11
#define CC_MANGLE_TYPE_9_CC_BITS_T11 CC_MANGLE_TYPE_CC_BITS_T11
#define CC_MANGLE_TYPE_0_CC_BITS_T12 CC_MANGLE_TYPE_CC_BITS_T12
#define CC_MANGLE_TYPE_1_CC_BITS_T12 CC_MANGLE_TYPE_CC_BITS_T12
#define CC_MANGLE_TYPE_2_CC_BITS_T12 CC_MANGLE_TYPE_CC_BITS_T12
#define CC_MANGLE_TYPE_3_CC_BITS_T12 CC_MANGLE_TYPE_CC_BITS_T12
#define CC_MANGLE_TYPE_4_CC_BITS_T12 CC_MANGLE_TYPE_CC_BITS_T12
#define CC_MANGLE_TYPE_5_CC_BITS_T12 CC_MANGLE_TYPE_CC_BITS_T12
#define CC_MANGLE_TYPE_6_CC_BITS_T12 CC_MANGLE_TYPE_CC_BITS_T12
#define CC_MANGLE_TYPE_7_CC_BITS_T12 CC_MANGLE_TYPE_CC_BITS_T12
#define CC_MANGLE_TYPE_8_CC_BITS_T12 CC_MANGLE_TYPE_CC_BITS_T12
#define CC_MANGLE_TYPE_9_CC_BITS_T12 CC_MANGLE_TYPE_CC_BITS_T12
#define CC_MANGLE_TYPE_0_CC_BITS_T13 CC_MANGLE_TYPE_CC_BITS_T13
#define CC_MANGLE_TYPE_1_CC_BITS_T13 CC_MANGLE_TYPE_CC_BITS_T13
#define CC_MANGLE_TYPE_2_CC_BITS_T13 CC_MANGLE_TYPE_CC_BITS_T13
#define CC_MANGLE_TYPE_3_CC_BITS_T13 CC_MANGLE_TYPE_CC_BITS_T13
#define CC_MANGLE_TYPE_4_CC_BITS_T13 CC_MANGLE_TYPE_CC_BITS_T13
#define CC_MANGLE_TYPE_5_CC_BITS_T13 CC_MANGLE_TYPE_CC_BITS_T13
#define CC_MANGLE_TYPE_6_CC_BITS_T13 CC_MANGLE_TYPE_CC_BITS_T13
#define CC_MANGLE_TYPE_7_CC_BITS_T13 CC_MANGLE_TYPE_CC_BITS_T13
#define CC_MANGLE_TYPE_8_CC_BITS_T13 CC_MANGLE_TYPE_CC_BITS_T13
#define CC_MANGLE_TYPE_9_CC_BITS_T13 CC_MANGLE_TYPE_CC_BITS_T13
#define CC_MANGLE_TYPE_0_CC_BITS_T14 CC_MANGLE_TYPE_CC_BITS_T14
#define CC_MANGLE_TYPE_1_CC_BITS_T14 CC_MANGLE_TYPE_CC_BITS_T14
#define CC_MANGLE_TYPE_2_CC_BITS_T14 CC_MANGLE_TYPE_CC_BITS_T14
#define CC_MANGLE_TYPE_3_CC_BITS_T14 CC_MANGLE_TYPE_CC_BITS_T14
#define CC_MANGLE_TYPE_4_CC_BITS_T14 CC_MANGLE_TYPE_CC_BITS_T14
#define CC_MANGLE_TYPE_5_CC_BITS_T14 CC_MANGLE_TYPE_CC_BITS_T14
#define CC_MANGLE_TYPE_6_CC_BITS_T14 CC_MANGLE_TYPE_CC_BITS_T14
#define CC_MANGLE_TYPE_7_CC_BITS_T14 CC_MANGLE_TYPE_CC_BITS_T14
#define CC_MANGLE_TYPE_8_CC_BITS_T14 CC_MANGLE_TYPE_CC_BITS_T14
#define CC_MANGLE_TYPE_9_CC_BITS_T14 CC_MANGLE_TYPE_CC_BITS_T14
#define CC_MANGLE_TYPE_0_CC_BITS_T15 CC_MANGLE_TYPE_CC_BITS_T15
#define CC_MANGLE_TYPE_1_CC_BITS_T15 CC_MANGLE_TYPE_CC_BITS_T15
#define CC_MANGLE_TYPE_2_CC_BITS_T15 CC_MANGLE_TYPE_CC_BITS_T15
#define CC_MANGLE_TYPE_3_CC_BITS_T15 CC_MANGLE_TYPE_CC_BITS_T15
#define CC_MANGLE_TYPE_4_CC_BITS_T15 CC_MANGLE_TYPE_CC_BITS_T15
#define CC_MANGLE_TYPE_5_CC_BITS_T15 CC_MANGLE_TYPE_CC_BITS_T15
#define CC_MANGLE_TYPE_6_CC_BITS_T15 CC_MANGLE_TYPE_CC_BITS_T15
#define CC_MANGLE_TYPE_7_CC_BITS_T15 CC_MANGLE_TYPE_CC_BITS_T15
#define CC_MANGLE_TYPE_8_CC_BITS_T15 CC_MANGLE_TYPE_CC_BITS_T15
#define CC_MANGLE_TYPE_9_CC_BITS_T15 CC_MANGLE_TYPE_CC_BITS_T15
#define CC_MANGLE_TYPE_0_CC_BITS_T16 CC_MANGLE_TYPE_CC_BITS_T16
#define CC_MANGLE_TYPE_1_CC_BITS_T16 CC_MANGLE_TYPE_CC_BITS_T16
#define CC_MANGLE_TYPE_2_CC_BITS_T16 CC_MANGLE_TYPE_CC_BITS_T16
#define CC_MANGLE_TYPE_3_CC_BITS_T16 CC_MANGLE_TYPE_CC_BITS_T16
#define CC_MANGLE_TYPE_4_CC_BITS_T16 CC_MANGLE_TYPE_CC_BITS_T16
#define CC_MANGLE_TYPE_5_CC_BITS_T16 CC_MANGLE_TYPE_CC_BITS_T16
#define CC_MANGLE_TYPE_6_CC_BITS_T16 CC_MANGLE_TYPE_CC_BITS_T16
#define CC_MANGLE_TYPE_7_CC_BITS_T16 CC_MANGLE_TYPE_CC_BITS_T16
#define CC_MANGLE_TYPE_8_CC_BITS_T16 CC_MANGLE_TYPE_CC_BITS_T16
#define CC_MANGLE_TYPE_9_CC_BITS_T16 CC_MANGLE_TYPE_CC_BITS_T16
#define CC_MANGLE_TYPE_0_CC_BITS_T17 CC_MANGLE_TYPE_CC_BITS_T17
#define CC_MANGLE_TYPE_1_CC_BITS_T17 CC_MANGLE_TYPE_CC_BITS_T17
#define CC_MANGLE_TYPE_2_CC_BITS_T17 CC_MANGLE_TYPE_CC_BITS_T17
#define CC_MANGLE_TYPE_3_CC_BITS_T17 CC_MANGLE_TYPE_CC_BITS_T17
#define CC_MANGLE_TYPE_4_CC_BITS_T17 CC_MANGLE_TYPE_CC_BITS_T17
#define CC_MANGLE_TYPE_5_CC_BITS_T17 CC_MANGLE_TYPE_CC_BITS_T17
#define CC_MANGLE_TYPE_6_CC_BITS_T17 CC_MANGLE_TYPE_CC_BITS_T17
#define CC_MANGLE_TYPE_7_CC_BITS_T17 CC_MANGLE_TYPE_CC_BITS_T17
#define CC_MANGLE_TYPE_8_CC_BITS_T17 CC_MANGLE_TYPE_CC_BITS_T17
#define CC_MANGLE_TYPE_9_CC_BITS_T17 CC_MANGLE_TYPE_CC_BITS_T17
#define CC_MANGLE_TYPE_0_CC_BITS_T18 CC_MANGLE_TYPE_CC_BITS_T18
#define CC_MANGLE_TYPE_1_CC_BITS_T18 CC_MANGLE_TYPE_CC_BITS_T18
#define CC_MANGLE_TYPE_2_CC_BITS_T18 CC_MANGLE_TYPE_CC_BITS_T18
#define CC_MANGLE_TYPE_3_CC_BITS_T18 CC_MANGLE_TYPE_CC_BITS_T18
#define CC_MANGLE_TYPE_4_CC_BITS_T18 CC_MANGLE_TYPE_CC_BITS_T18
#define CC_MANGLE_TYPE_5_CC_BITS_T18 CC_MANGLE_TYPE_CC_BITS_T18
#define CC_MANGLE_TYPE_6_CC_BITS_T18 CC_MANGLE_TYPE_CC_BITS_T18
#define CC_MANGLE_TYPE_7_CC_BITS_T18 CC_MANGLE_TYPE_CC_BITS_T18
#define CC_MANGLE_TYPE_8_CC_BITS_T18 CC_MANGLE_TYPE_CC_BITS_T18
#define CC_MANGLE_TYPE_9_CC_BITS_T18 CC_MANGLE_TYPE_CC_BITS_T18
#define CC_MANGLE_TYPE_0_CC_BITS_T19 CC_MANGLE_TYPE_CC_BITS_T19
#define CC_MANGLE_TYPE_1_CC_BITS_T19 CC_MANGLE_TYPE_CC_BITS_T19
#define CC_MANGLE_TYPE_2_CC_BITS_T19 CC_MANGLE_TYPE_CC_BITS_T19
#define CC_MANGLE_TYPE_3_CC_BITS_T19 CC_MANGLE_TYPE_CC_BITS_T19
#define CC_MANGLE_TYPE_4_CC_BITS_T19 CC_MANGLE_TYPE_CC_BITS_T19
#define CC_MANGLE_TYPE_5_CC_BITS_T19 CC_MANGLE_TYPE_CC_BITS_T19
#define CC_MANGLE_TYPE_6_CC_BITS_T19 CC_MANGLE_TYPE_CC_BITS_T19
#define CC_MANGLE_TYPE_7_CC_BITS_T19 CC_MANGLE_TYPE_CC_BITS_T19
#define CC_MANGLE_TYPE_8_CC_BITS_T19 CC_MANGLE_TYPE_CC_BITS_T19
#define CC_MANGLE_TYPE_9_CC_BITS_T19 CC_MANGLE_TYPE_CC_BITS_T19

#define CC_TYPE_DECL_CC_BITS_T0(...) CC_BITS_T0, __VA_ARGS__
#define CC_TYPE_DECL_CC_BITS_T1(...) CC_BITS_T1, __VA_ARGS__
#define CC_TYPE_DECL_CC_BITS_T2(...) CC_BITS_T2, __VA_ARGS__
#define CC_TYPE_DECL_CC_BITS_T3(...) CC_BITS_T3, __VA_ARGS__
#define CC_TYPE_DECL_CC_BITS_T4(...) CC_BITS_T4, __VA_ARGS__
#define CC_TYPE_DECL_CC_BITS_T5(...) CC_BITS_T5, __VA_ARGS__
#define CC_TYPE_DECL_CC_BITS_T6(...) CC_BITS_T6, __VA_ARGS__
#define CC_TYPE_DECL_CC_BITS_T7(...) CC_BITS_T7, __VA_ARGS__
#define CC_TYPE_DECL_CC_BITS_T8(...) CC_BITS_T8, __VA_ARGS__
#define CC_TYPE_DECL_CC_BITS_T9(...) CC_BITS_T9, __VA_ARGS__
#define CC_TYPE_DECL_CC_BITS_T10(...) CC_BITS_T10, __VA_ARGS__
#define CC_TYPE_DECL_CC_BITS_T11(...) CC_BITS_T11, __VA_ARGS__
#define CC_TYPE_DECL_CC_BITS_T12(...) CC_BITS_T12, __VA_ARGS__
#define CC_TYPE_DECL_CC_BITS_T13(...) CC_BITS_T13, __VA_ARGS__
#define CC_TYPE_DECL_CC_BITS_T14(...) CC_BITS_T14, __VA_ARGS__
#define CC_TYPE_DECL_CC_BITS_T15(...) CC_BITS_T15, __VA_ARGS__
#define CC_TYPE_DECL_CC_BITS_T16(...) CC_BITS_T16, __VA_ARGS__
#define CC_TYPE_DECL_CC_BITS_T17(...) CC_BITS_T17, __VA_ARGS__
#define CC_TYPE_DECL_CC_BITS_T18(...) CC_BITS_T18, __VA_ARGS__
#define CC_TYPE_DECL_CC_BITS_T19(...) CC_BITS_T19, __VA_ARGS__
#define CC_TYPE_DECL_0_CC_BITS_T0 CC_TYPE_DECL_CC_BITS_T0,
#define CC_TYPE_DECL_1_CC_BITS_T0 CC_TYPE_DECL_CC_BITS_T0,
#define CC_TYPE_DECL_2_CC_BITS_T0 CC_TYPE_DECL_CC_BITS_T0,
#define CC_TYPE_DECL_3_CC_BITS_T0 CC_TYPE_DECL_CC_BITS_T0,
#define CC_TYPE_DECL_4_CC_BITS_T0 CC_TYPE_DECL_CC_BITS_T0,
#define CC_TYPE_DECL_5_CC_BITS_T0 CC_TYPE_DECL_CC_BITS_T0,
#define CC_TYPE_DECL_6_CC_BITS_T0 CC_TYPE_DECL_CC_BITS_T0,
#define CC_TYPE_DECL_7_CC_BITS_T0 CC_TYPE_DECL_CC_BITS_T0,
#define CC_TYPE_DECL_8_CC_BITS_T0 CC_TYPE_DECL_CC_BITS_T0,
#define CC_TYPE_DECL_9_CC_BITS_T0 CC_TYPE_DECL_CC_BITS_T0,
#define CC_TYPE_DECL_0_CC_BITS_T1 CC_TYPE_DECL_CC_BITS_T1,
#define CC_TYPE_DECL_1_CC_BITS_T1 CC_TYPE_DECL_CC_BITS_T1,
#define CC_TYPE_DECL_2_CC_BITS_T1 CC_TYPE_DECL_CC_BITS_T1,
#define CC_TYPE_DECL_3_CC_BITS_T1 CC_TYPE_DECL_CC_BITS_T1,
#define CC_TYPE_DECL_4_CC_BITS_T1 CC_TYPE_DECL_CC_BITS_T1,
#define CC_TYPE_DECL_5_CC_BITS_T1 CC_TYPE_DECL_CC_BITS_T1,
#define CC_TYPE_DECL_6_CC_BITS_T1 CC_TYPE_DECL_CC_BITS_T1,
#define CC_TYPE_DECL_7_CC_BITS_T1 CC_TYPE_DECL_CC_BITS_T1,
#define CC_TYPE_DECL_8_CC_BITS_T1 CC_TYPE_DECL_CC_BITS_T1,
#define CC_TYPE_DECL_9_CC_BITS_T1 CC_TYPE_DECL_CC_BITS_T1,
#define CC_TYPE_DECL_0_CC_BITS_T2 CC_TYPE_DECL_CC_BITS_T2,
#define CC_TYPE_DECL_1_CC_BITS_T2 CC_TYPE_DECL_CC_BITS_T2,
#define CC_TYPE_DECL_2_CC_BITS_T2 CC_TYPE_DECL_CC_BITS_T2,
#define CC_TYPE_DECL_3_CC_BITS_T2 CC_TYPE_DECL_CC_BITS_T2,
#define CC_TYPE_DECL_4_CC_BITS_T2 CC_TYPE_DECL_CC_BITS_T2,
#define CC_TYPE_DECL_5_CC_BITS_T2 CC_TYPE_DECL_CC_BITS_T2,
#define CC_TYPE_DECL_6_CC_BITS_T2 CC_TYPE_DECL_CC_BITS_T2,
#define CC_TYPE_DECL_7_CC_BITS_T2 CC_TYPE_DECL_CC_BITS_T2,
#define CC_TYPE_DECL_8_CC_BITS_T2 CC_TYPE_DECL_CC_BITS_T2,
#define CC_TYPE_DECL_9_CC_BITS_T2 CC_TYPE_DECL_CC_BITS_T2,
#define CC_TYPE_DECL_0_CC_BITS_T3 CC_TYPE_DECL_CC_BITS_T3,
#define CC_TYPE_DECL_1_CC_BITS_T3 CC_TYPE_DECL_CC_BITS_T3,
#define CC_TYPE_DECL_2_CC_BITS_T3 CC_TYPE_DECL_CC_BITS_T3,
#define CC_TYPE_DECL_3_CC_BITS_T3 CC_TYPE_DECL_CC_BITS_T3,
#define CC_TYPE_DECL_4_CC_BITS_T3 CC_TYPE_DECL_CC_BITS_T3,
#define CC_TYPE_DECL_5_CC_BITS_T3 CC_TYPE_DECL_CC_BITS_T3,
#define CC_TYPE_DECL_6_CC_BITS_T3 CC_TYPE_DECL_CC_BITS_T3,
#define CC_TYPE_DECL_7_CC_BITS_T3 CC_TYPE_DECL_CC_BITS_T3,
#define CC_TYPE_DECL_8_CC_BITS_T3 CC_TYPE_DECL_CC_BITS_T3,
#define CC_TYPE_DECL_9_CC_BITS_T3 CC_TYPE_DECL_CC_BITS_T3,
#define CC_TYPE_DECL_0_CC_BITS_T4 CC_TYPE_DECL_CC_BITS_T4,
#define CC_TYPE_DECL_1_CC_BITS_T4 CC_TYPE_DECL_CC_BITS_T4,
#define CC_TYPE_DECL_2_CC_BITS_T4 CC_TYPE_DECL_CC_BITS_T4,
#define CC_TYPE_DECL_3_CC_BITS_T4 CC_TYPE_DECL_CC_BITS_T4,
#define CC_TYPE_DECL_4_CC_BITS_T4 CC_TYPE_DECL_CC_BITS_T4,
#define CC_TYPE_DECL_5_CC_BITS_T4 CC_TYPE_DECL_CC_BITS_T4,
#define CC_TYPE_DECL_6_CC_BITS_T4 CC_TYPE_DECL_CC_BITS_T4,
#define CC_TYPE_DECL_7_CC_BITS_T4 CC_TYPE_DECL_CC_BITS_T4,
#define CC_TYPE_DECL_8_CC_BITS_T4 CC_TYPE_DECL_CC_BITS_T4,
#define CC_TYPE_DECL_9_CC_BITS_T4 CC_TYPE_DECL_CC_BITS_T4,
#define CC_TYPE_DECL_0_CC_BITS_T5 CC_TYPE_DECL_CC_BITS_T5,
#define CC_TYPE_DECL_1_CC_BITS_T5 CC_TYPE_DECL_CC_BITS_T5,
#define CC_TYPE_DECL_2_CC_BITS_T5 CC_TYPE_DECL_CC_BITS_T5,
#define CC_TYPE_DECL_3_CC_BITS_T5 CC_TYPE_DECL_CC_BITS_T5,
#define CC_TYPE_DECL_4_CC_BITS_T5 CC_TYPE_DECL_CC_BITS_T5,
#define CC_TYPE_DECL_5_CC_BITS_T5 CC_TYPE_DECL_CC_BITS_T5,
#define CC_TYPE_DECL_6_CC_BITS_T5 CC_TYPE_DECL_CC_BITS_T5,
#define CC_TYPE_DECL_7_CC_BITS_T5 CC_TYPE_DECL_CC_BITS_T5,
#define CC_TYPE_DECL_8_CC_BITS_T5 CC_TYPE_DECL_CC_BITS_T5,
#define CC_TYPE_DECL_9_CC_BITS_T5 CC_TYPE_DECL_CC_BITS_T5,
#define CC_TYPE_DECL_0_CC_BITS_T6 CC_TYPE_DECL_CC_BITS_T6,
#define CC_TYPE_DECL_1_CC_BITS_T6 CC_TYPE_DECL_CC_BITS_T6,
#define CC_TYPE_DECL_2_CC_BITS_T6 CC_TYPE_DECL_CC_BITS_T6,
#define CC_TYPE_DECL_3_CC_BITS_T6 CC_TYPE_DECL_CC_BITS_T6,
#define CC_TYPE_DECL_4_CC_BITS_T6 CC_TYPE_DECL_CC_BITS_T6,
#define CC_TYPE_DECL_5_CC_BITS_T6 CC_TYPE_DECL_CC_BITS_T6,
#define CC_TYPE_DECL_6_CC_BITS_T6 CC_TYPE_DECL_CC_BITS_T6,
#define CC_TYPE_DECL_7_CC_BITS_T6 CC_TYPE_DECL_CC_BITS_T6,
#define CC_TYPE_DECL_8_CC_BITS_T6 CC_TYPE_DECL_CC_BITS_T6,
#define CC_TYPE_DECL_9_CC_BITS_T6 CC_TYPE_DECL_CC_BITS_T6,
#define CC_TYPE_DECL_0_CC_BITS_T7 CC_TYPE_DECL_CC_BITS_T7,
#define CC_TYPE_DECL_1_CC_BITS_T7 CC_TYPE_DECL_CC_BITS_T7,
#define CC_TYPE_DECL_2_CC_BITS_T7 CC_TYPE_DECL_CC_BITS_T7,
#define CC_TYPE_DECL_3_CC_BITS_T7 CC_TYPE_DECL_CC_BITS_T7,
#define CC_TYPE_DECL_4_CC_BITS_T7 CC_TYPE_DECL_CC_BITS_T7,
#define CC_TYPE_DECL_5_CC_BITS_T7 CC_TYPE_DECL_CC_BITS_T7,
#define CC_TYPE_DECL_6_CC_BITS_T7 CC_TYPE_DECL_CC_BITS_T7,
#define CC_TYPE_DECL_7_CC_BITS_T7 CC_TYPE_DECL_CC_BITS_T7,
#define CC_TYPE_DECL_8_CC_BITS_T7 CC_TYPE_DECL_CC_BITS_T7,
#define CC_TYPE_DECL_9_CC_BITS_T7 CC_TYPE_DECL_CC_BITS_T7,
#define CC_TYPE_DECL_0_CC_BITS_T8 CC_TYPE_DECL_CC_BITS_T8,
#define CC_TYPE_DECL_1_CC_BITS_T8 CC_TYPE_DECL_CC_BITS_T8,
#define CC_TYPE_DECL_2_CC_BITS_T8 CC_TYPE_DECL_CC_BITS_T8,
#define CC_TYPE_DECL_3_CC_BITS_T8 CC_TYPE_DECL_CC_BITS_T8,
#define CC_TYPE_DECL_4_CC_BITS_T8 CC_TYPE_DECL_CC_BITS_T8,
#define CC_TYPE_DECL_5_CC_BITS_T8 CC_TYPE_DECL_CC_BITS_T8,
#define CC_TYPE_DECL_6_CC_BITS_T8 CC_TYPE_DECL_CC_BITS_T8,
#define CC_TYPE_DECL_7_CC_BITS_T8 CC_TYPE_DECL_CC_BITS_T8,
#define CC_TYPE_DECL_8_CC_BITS_T8 CC_TYPE_DECL_CC_BITS_T8,
#define CC_TYPE_DECL_9_CC_BITS_T8 CC_TYPE_DECL_CC_BITS_T8,
#define CC_TYPE_DECL_0_CC_BITS_T9 CC_TYPE_DECL_CC_BITS_T9,
#define CC_TYPE_DECL_1_CC_BITS_T9 CC_TYPE_DECL_CC_BITS_T9,
#define CC_TYPE_DECL_2_CC_BITS_T9 CC_TYPE_DECL_CC_BITS_T9,
#define CC_TYPE_DECL_3_CC_BITS_T9 CC_TYPE_DECL_CC_BITS_T9,
#define CC_TYPE_DECL_4_CC_BITS_T9 CC_TYPE_DECL_CC_BITS_T9,
#define CC_TYPE_DECL_5_CC_BITS_T9 CC_TYPE_DECL_CC_BITS_T9,
#define CC_TYPE_DECL_6_CC_BITS_T9 CC_TYPE_DECL_CC_BITS_T9,
#define CC_TYPE_DECL_7_CC_BITS_T9 CC_TYPE_DECL_CC_BITS_T9,
#define CC_TYPE_DECL_8_CC_BITS_T9 CC_TYPE_DECL_CC_BITS_T9,
#define CC_TYPE_DECL_9_CC_BITS_T9 CC_TYPE_DECL_CC_BITS_T9,
#define CC_TYPE_DECL_0_CC_BITS_T10 CC_TYPE_DECL_CC_BITS_T10,
#define CC_TYPE_DECL_1_CC_BITS_T10 CC_TYPE_DECL_CC_BITS_T10,
#define CC_TYPE_DECL_2_CC_BITS_T10 CC_TYPE_DECL_CC_BITS_T10,
#define CC_TYPE_DECL_3_CC_BITS_T10 CC_TYPE_DECL_CC_BITS_T10,
#define CC_TYPE_DECL_4_CC_BITS_T10 CC_TYPE_DECL_CC_BITS_T10,
#define CC_TYPE_DECL_5_CC_BITS_T10 CC_TYPE_DECL_CC_BITS_T10,
#define CC_TYPE_DECL_6_CC_BITS_T10 CC_TYPE_DECL_CC_BITS_T10,
#define CC_TYPE_DECL_7_CC_BITS_T10 CC_TYPE_DECL_CC_BITS_T10,
#define CC_TYPE_DECL_8_CC_BITS_T10 CC_TYPE_DECL_CC_BITS_T10,
#define CC_TYPE_DECL_9_CC_BITS_T10 CC_TYPE_DECL_CC_BITS_T10,
#define CC_TYPE_DECL_0_CC_BITS_T11 CC_TYPE_DECL_CC_BITS_T11,
#define CC_TYPE_DECL_1_CC_BITS_T11 CC_TYPE_DECL_CC_BITS_T11,
#define CC_TYPE_DECL_2_CC_BITS_T11 CC_TYPE_DECL_CC_BITS_T11,
#define CC_TYPE_DECL_3_CC_BITS_T11 CC_TYPE_DECL_CC_BITS_T11,
#define CC_TYPE_DECL_4_CC_BITS_T11 CC_TYPE_DECL_CC_BITS_T11,
#define CC_TYPE_DECL_5_CC_BITS_T11 CC_TYPE_DECL_CC_BITS_T11,
#define CC_TYPE_DECL_6_CC_BITS_T11 CC_TYPE_DECL_CC_BITS_T11,
#define CC_TYPE_DECL_7_CC_BITS_T11 CC_TYPE_DECL_CC_BITS_T11,
#define CC_TYPE_DECL_8_CC_BITS_T11 CC_TYPE_DECL_CC_BITS_T11,
#define CC_TYPE_DECL_9_CC_BITS_T11 CC_TYPE_DECL_CC_BITS_T11,
#define CC_TYPE_DECL_0_CC_BITS_T12 CC_TYPE_DECL_CC_BITS_T12,
#define CC_TYPE_DECL_1_CC_BITS_T12 CC_TYPE_DECL_CC_BITS_T12,
#define CC_TYPE_DECL_2_CC_BITS_T12 CC_TYPE_DECL_CC_BITS_T12,
#define CC_TYPE_DECL_3_CC_BITS_T12 CC_TYPE_DECL_CC_BITS_T12,
#define CC_TYPE_DECL_4_CC_BITS_T12 CC_TYPE_DECL_CC_BITS_T12,
#define CC_TYPE_DECL_5_CC_BITS_T12 CC_TYPE_DECL_CC_BITS_T12,
#define CC_TYPE_DECL_6_CC_BITS_T12 CC_TYPE_DECL_CC_BITS_T12,
#define CC_TYPE_DECL_7_CC_BITS_T12 CC_TYPE_DECL_CC_BITS_T12,
#define CC_TYPE_DECL_8_CC_BITS_T12 CC_TYPE_DECL_CC_BITS_T12,
#define CC_TYPE_DECL_9_CC_BITS_T12 CC_TYPE_DECL_CC_BITS_T12,
#define CC_TYPE_DECL_0_CC_BITS_T13 CC_TYPE_DECL_CC_BITS_T13,
#define CC_TYPE_DECL_1_CC_BITS_T13 CC_TYPE_DECL_CC_BITS_T13,
#define CC_TYPE_DECL_2_CC_BITS_T13 CC_TYPE_DECL_CC_BITS_T13,
#define CC_TYPE_DECL_3_CC_BITS_T13 CC_TYPE_DECL_CC_BITS_T13,
#define CC_TYPE_DECL_4_CC_BITS_T13 CC_TYPE_DECL_CC_BITS_T13,
#define CC_TYPE_DECL_5_CC_BITS_T13 CC_TYPE_DECL_CC_BITS_T13,
#define CC_TYPE_DECL_6_CC_BITS_T13 CC_TYPE_DECL_CC_BITS_T13,
#define CC_TYPE_DECL_7_CC_BITS_T13 CC_TYPE_DECL_CC_BITS_T13,
#define CC_TYPE_DECL_8_CC_BITS_T13 CC_TYPE_DECL_CC_BITS_T13,
#define CC_TYPE_DECL_9_CC_BITS_T13 CC_TYPE_DECL_CC_BITS_T13,
#define CC_TYPE_DECL_0_CC_BITS_T14 CC_TYPE_DECL_CC_BITS_T14,
#define CC_TYPE_DECL_1_CC_BITS_T14 CC_TYPE_DECL_CC_BITS_T14,
#define CC_TYPE_DECL_2_CC_BITS_T14 CC_TYPE_DECL_CC_BITS_T14,
#define CC_TYPE_DECL_3_CC_BITS_T14 CC_TYPE_DECL_CC_BITS_T14,
#define CC_TYPE_DECL_4_CC_BITS_T14 CC_TYPE_DECL_CC_BITS_T14,
#define CC_TYPE_DECL_5_CC_BITS_T14 CC_TYPE_DECL_CC_BITS_T14,
#define CC_TYPE_DECL_6_CC_BITS_T14 CC_TYPE_DECL_CC_BITS_T14,
#define CC_TYPE_DECL_7_CC_BITS_T14 CC_TYPE_DECL_CC_BITS_T14,
#define CC_TYPE_DECL_8_CC_BITS_T14 CC_TYPE_DECL_CC_BITS_T14,
#define CC_TYPE_DECL_9_CC_BITS_T14 CC_TYPE_DECL_CC_BITS_T14,
#define CC_TYPE_DECL_0_CC_BITS_T15 CC_TYPE_DECL_CC_BITS_T15,
#define CC_TYPE_DECL_1_CC_BITS_T15 CC_TYPE_DECL_CC_BITS_T15,
#define CC_TYPE_DECL_2_CC_BITS_T15 CC_TYPE_DECL_CC_BITS_T15,
#define CC_TYPE_DECL_3_CC_BITS_T15 CC_TYPE_DECL_CC_BITS_T15,
#define CC_TYPE_DECL_4_CC_BITS_T15 CC_TYPE_DECL_CC_BITS_T15,
#define CC_TYPE_DECL_5_CC_BITS_T15 CC_TYPE_DECL_CC_BITS_T15,
#define CC_TYPE_DECL_6_CC_BITS_T15 CC_TYPE_DECL_CC_BITS_T15,
#define CC_TYPE_DECL_7_CC_BITS_T15 CC_TYPE_DECL_CC_BITS_T15,
#define CC_TYPE_DECL_8_CC_BITS_T15 CC_TYPE_DECL_CC_BITS_T15,
#define CC_TYPE_DECL_9_CC_BITS_T15 CC_TYPE_DECL_CC_BITS_T15,
#define CC_TYPE_DECL_0_CC_BITS_T16 CC_TYPE_DECL_CC_BITS_T16,
#define CC_TYPE_DECL_1_CC_BITS_T16 CC_TYPE_DECL_CC_BITS_T16,
#define CC_TYPE_DECL_2_CC_BITS_T16 CC_TYPE_DECL_CC_BITS_T16,
#define CC_TYPE_DECL_3_CC_BITS_T16 CC_TYPE_DECL_CC_BITS_T16,
#define CC_TYPE_DECL_4_CC_BITS_T16 CC_TYPE_DECL_CC_BITS_T16,
#define CC_TYPE_DECL_5_CC_BITS_T16 CC_TYPE_DECL_CC_BITS_T16,
#define CC_TYPE_DECL_6_CC_BITS_T16 CC_TYPE_DECL_CC_BITS_T16,
#define CC_TYPE_DECL_7_CC_BITS_T16 CC_TYPE_DECL_CC_BITS_T16,
#define CC_TYPE_DECL_8_CC_BITS_T16 CC_TYPE_DECL_CC_BITS_T16,
#define CC_TYPE_DECL_9_CC_BITS_T16 CC_TYPE_DECL_CC_BITS_T16,
#define CC_TYPE_DECL_0_CC_BITS_T17 CC_TYPE_DECL_CC_BITS_T17,
#define CC_TYPE_DECL_1_CC_BITS_T17 CC_TYPE_DECL_CC_BITS_T17,
#define CC_TYPE_DECL_2_CC_BITS_T17 CC_TYPE_DECL_CC_BITS_T17,
#define CC_TYPE_DECL_3_CC_BITS_T17 CC_TYPE_DECL_CC_BITS_T17,
#define CC_TYPE_DECL_4_CC_BITS_T17 CC_TYPE_DECL_CC_BITS_T17,
#define CC_TYPE_DECL_5_CC_BITS_T17 CC_TYPE_DECL_CC_BITS_T17,
#define CC_TYPE_DECL_6_CC_BITS_T17 CC_TYPE_DECL_CC_BITS_T17,
#define CC_TYPE_DECL_7_CC_BITS_T17 CC_TYPE_DECL_CC_BITS_T17,
#define CC_TYPE_DECL_8_CC_BITS_T17 CC_TYPE_DECL_CC_BITS_T17,
#define CC_TYPE_DECL_9_CC_BITS_T17 CC_TYPE_DECL_CC_BITS_T17,
#define CC_TYPE_DECL_0_CC_BITS_T18 CC_TYPE_DECL_CC_BITS_T18,
#define CC_TYPE_DECL_1_CC_BITS_T18 CC_TYPE_DECL_CC_BITS_T18,
#define CC_TYPE_DECL_2_CC_BITS_T18 CC_TYPE_DECL_CC_BITS_T18,
#define CC_TYPE_DECL_3_CC_BITS_T18 CC_TYPE_DECL_CC_BITS_T18,
#define CC_TYPE_DECL_4_CC_BITS_T18 CC_TYPE_DECL_CC_BITS_T18,
#define CC_TYPE_DECL_5_CC_BITS_T18 CC_TYPE_DECL_CC_BITS_T18,
#define CC_TYPE_DECL_6_CC_BITS_T18 CC_TYPE_DECL_CC_BITS_T18,
#define CC_TYPE_DECL_7_CC_BITS_T18 CC_TYPE_DECL_CC_BITS_T18,
#define CC_TYPE_DECL_8_CC_BITS_T18 CC_TYPE_DECL_CC_BITS_T18,
#define CC_TYPE_DECL_9_CC_BITS_T18 CC_TYPE_DECL_CC_BITS_T18,
#define CC_TYPE_DECL_0_CC_BITS_T19 CC_TYPE_DECL_CC_BITS_T19,
#define CC_TYPE_DECL_1_CC_BITS_T19 CC_TYPE_DECL_CC_BITS_T19,
#define CC_TYPE_DECL_2_CC_BITS_T19 CC_TYPE_DECL_CC_BITS_T19,
#define CC_TYPE_DECL_3_CC_BITS_T19 CC_TYPE_DECL_CC_BITS_T19,
#define CC_TYPE_DECL_4_CC_BITS_T19 CC_TYPE_DECL_CC_BITS_T19,
#define CC_TYPE_DECL_5_CC_BITS_T19 CC_TYPE_DECL_CC_BITS_T19,
#define CC_TYPE_DECL_6_CC_BITS_T19 CC_TYPE_DECL_CC_BITS_T19,
#define CC_TYPE_DECL_7_CC_BITS_T19 CC_TYPE_DECL_CC_BITS_T19,
#define CC_TYPE_DECL_8_CC_BITS_T19 CC_TYPE_DECL_CC_BITS_T19,
#define CC_TYPE_DECL_9_CC_BITS_T19 CC_TYPE_DECL_CC_BITS_T19,

#ifdef CC_BITS_COUNT
#define CC_GENERIC_COUNT CC_BITS_COUNT
#endif

#ifndef CC_GENERIC_TEMPLATE
#define CC_GENERIC_TEMPLATE <CommonC/BitsTemplate.h>
#endif

#undef CC_GENERIC_TYPE
#define CC_GENERIC_TYPE CC_BITS
#include <CommonC/Generic1.h>

#if CC_GENERIC_COUNT < 1
#undef CC_MANGLE_TYPE_CC_BITS_T0
#endif

#if CC_GENERIC_COUNT < 2
#undef CC_MANGLE_TYPE_CC_BITS_T1
#endif

#if CC_GENERIC_COUNT < 3
#undef CC_MANGLE_TYPE_CC_BITS_T2
#endif

#if CC_GENERIC_COUNT < 4
#undef CC_MANGLE_TYPE_CC_BITS_T3
#endif

#if CC_GENERIC_COUNT < 5
#undef CC_MANGLE_TYPE_CC_BITS_T4
#endif

#if CC_GENERIC_COUNT < 6
#undef CC_MANGLE_TYPE_CC_BITS_T5
#endif

#if CC_GENERIC_COUNT < 7
#undef CC_MANGLE_TYPE_CC_BITS_T6
#endif

#if CC_GENERIC_COUNT < 8
#undef CC_MANGLE_TYPE_CC_BITS_T7
#endif

#if CC_GENERIC_COUNT < 9
#undef CC_MANGLE_TYPE_CC_BITS_T8
#endif

#if CC_GENERIC_COUNT < 10
#undef CC_MANGLE_TYPE_CC_BITS_T9
#endif

#if CC_GENERIC_COUNT < 11
#undef CC_MANGLE_TYPE_CC_BITS_T10
#endif

#if CC_GENERIC_COUNT < 12
#undef CC_MANGLE_TYPE_CC_BITS_T11
#endif

#if CC_GENERIC_COUNT < 13
#undef CC_MANGLE_TYPE_CC_BITS_T12
#endif

#if CC_GENERIC_COUNT < 14
#undef CC_MANGLE_TYPE_CC_BITS_T13
#endif

#if CC_GENERIC_COUNT < 15
#undef CC_MANGLE_TYPE_CC_BITS_T14
#endif

#if CC_GENERIC_COUNT < 16
#undef CC_MANGLE_TYPE_CC_BITS_T15
#endif

#if CC_GENERIC_COUNT < 17
#undef CC_MANGLE_TYPE_CC_BITS_T16
#endif

#if CC_GENERIC_COUNT < 18
#undef CC_MANGLE_TYPE_CC_BITS_T17
#endif

#if CC_GENERIC_COUNT < 19
#undef CC_MANGLE_TYPE_CC_BITS_T18
#endif

#if CC_GENERIC_COUNT < 20
#undef CC_MANGLE_TYPE_CC_BITS_T19
#endif

#undef CC_BITS_COUNT

#if CC_GENERIC_COUNT == 1
#define CC_BITS_COUNT 1
#elif CC_GENERIC_COUNT == 2
#define CC_BITS_COUNT 2
#elif CC_GENERIC_COUNT == 3
#define CC_BITS_COUNT 3
#elif CC_GENERIC_COUNT == 4
#define CC_BITS_COUNT 4
#elif CC_GENERIC_COUNT == 5
#define CC_BITS_COUNT 5
#elif CC_GENERIC_COUNT == 6
#define CC_BITS_COUNT 6
#elif CC_GENERIC_COUNT == 7
#define CC_BITS_COUNT 7
#elif CC_GENERIC_COUNT == 8
#define CC_BITS_COUNT 8
#elif CC_GENERIC_COUNT == 9
#define CC_BITS_COUNT 9
#elif CC_GENERIC_COUNT == 10
#define CC_BITS_COUNT 10
#elif CC_GENERIC_COUNT == 11
#define CC_BITS_COUNT 11
#elif CC_GENERIC_COUNT == 12
#define CC_BITS_COUNT 12
#elif CC_GENERIC_COUNT == 13
#define CC_BITS_COUNT 13
#elif CC_GENERIC_COUNT == 14
#define CC_BITS_COUNT 14
#elif CC_GENERIC_COUNT == 15
#define CC_BITS_COUNT 15
#elif CC_GENERIC_COUNT == 16
#define CC_BITS_COUNT 16
#elif CC_GENERIC_COUNT == 17
#define CC_BITS_COUNT 17
#elif CC_GENERIC_COUNT == 18
#define CC_BITS_COUNT 18
#elif CC_GENERIC_COUNT == 19
#define CC_BITS_COUNT 19
#elif CC_GENERIC_COUNT == 20
#define CC_BITS_COUNT 20
#else
#error Add additional cases
#endif

#undef CC_GENERIC_COUNT

#define CC_TYPE_CC_BITS_T0(...) CC_BITS_T0
#define CC_TYPE_CC_BITS_T1(...) CC_BITS_T1
#define CC_TYPE_CC_BITS_T2(...) CC_BITS_T2
#define CC_TYPE_CC_BITS_T3(...) CC_BITS_T3
#define CC_TYPE_CC_BITS_T4(...) CC_BITS_T4
#define CC_TYPE_CC_BITS_T5(...) CC_BITS_T5
#define CC_TYPE_CC_BITS_T6(...) CC_BITS_T6
#define CC_TYPE_CC_BITS_T7(...) CC_BITS_T7
#define CC_TYPE_CC_BITS_T8(...) CC_BITS_T8
#define CC_TYPE_CC_BITS_T9(...) CC_BITS_T9
#define CC_TYPE_CC_BITS_T10(...) CC_BITS_T10
#define CC_TYPE_CC_BITS_T11(...) CC_BITS_T11
#define CC_TYPE_CC_BITS_T12(...) CC_BITS_T12
#define CC_TYPE_CC_BITS_T13(...) CC_BITS_T13
#define CC_TYPE_CC_BITS_T14(...) CC_BITS_T14
#define CC_TYPE_CC_BITS_T15(...) CC_BITS_T15
#define CC_TYPE_CC_BITS_T16(...) CC_BITS_T16
#define CC_TYPE_CC_BITS_T17(...) CC_BITS_T17
#define CC_TYPE_CC_BITS_T18(...) CC_BITS_T18
#define CC_TYPE_CC_BITS_T19(...) CC_BITS_T19
#define CC_TYPE_0_CC_BITS_T0 CC_TYPE_CC_BITS_T0,
#define CC_TYPE_1_CC_BITS_T0 CC_TYPE_CC_BITS_T0,
#define CC_TYPE_2_CC_BITS_T0 CC_TYPE_CC_BITS_T0,
#define CC_TYPE_3_CC_BITS_T0 CC_TYPE_CC_BITS_T0,
#define CC_TYPE_4_CC_BITS_T0 CC_TYPE_CC_BITS_T0,
#define CC_TYPE_5_CC_BITS_T0 CC_TYPE_CC_BITS_T0,
#define CC_TYPE_6_CC_BITS_T0 CC_TYPE_CC_BITS_T0,
#define CC_TYPE_7_CC_BITS_T0 CC_TYPE_CC_BITS_T0,
#define CC_TYPE_8_CC_BITS_T0 CC_TYPE_CC_BITS_T0,
#define CC_TYPE_9_CC_BITS_T0 CC_TYPE_CC_BITS_T0,
#define CC_TYPE_0_CC_BITS_T1 CC_TYPE_CC_BITS_T1,
#define CC_TYPE_1_CC_BITS_T1 CC_TYPE_CC_BITS_T1,
#define CC_TYPE_2_CC_BITS_T1 CC_TYPE_CC_BITS_T1,
#define CC_TYPE_3_CC_BITS_T1 CC_TYPE_CC_BITS_T1,
#define CC_TYPE_4_CC_BITS_T1 CC_TYPE_CC_BITS_T1,
#define CC_TYPE_5_CC_BITS_T1 CC_TYPE_CC_BITS_T1,
#define CC_TYPE_6_CC_BITS_T1 CC_TYPE_CC_BITS_T1,
#define CC_TYPE_7_CC_BITS_T1 CC_TYPE_CC_BITS_T1,
#define CC_TYPE_8_CC_BITS_T1 CC_TYPE_CC_BITS_T1,
#define CC_TYPE_9_CC_BITS_T1 CC_TYPE_CC_BITS_T1,
#define CC_TYPE_0_CC_BITS_T2 CC_TYPE_CC_BITS_T2,
#define CC_TYPE_1_CC_BITS_T2 CC_TYPE_CC_BITS_T2,
#define CC_TYPE_2_CC_BITS_T2 CC_TYPE_CC_BITS_T2,
#define CC_TYPE_3_CC_BITS_T2 CC_TYPE_CC_BITS_T2,
#define CC_TYPE_4_CC_BITS_T2 CC_TYPE_CC_BITS_T2,
#define CC_TYPE_5_CC_BITS_T2 CC_TYPE_CC_BITS_T2,
#define CC_TYPE_6_CC_BITS_T2 CC_TYPE_CC_BITS_T2,
#define CC_TYPE_7_CC_BITS_T2 CC_TYPE_CC_BITS_T2,
#define CC_TYPE_8_CC_BITS_T2 CC_TYPE_CC_BITS_T2,
#define CC_TYPE_9_CC_BITS_T2 CC_TYPE_CC_BITS_T2,
#define CC_TYPE_0_CC_BITS_T3 CC_TYPE_CC_BITS_T3,
#define CC_TYPE_1_CC_BITS_T3 CC_TYPE_CC_BITS_T3,
#define CC_TYPE_2_CC_BITS_T3 CC_TYPE_CC_BITS_T3,
#define CC_TYPE_3_CC_BITS_T3 CC_TYPE_CC_BITS_T3,
#define CC_TYPE_4_CC_BITS_T3 CC_TYPE_CC_BITS_T3,
#define CC_TYPE_5_CC_BITS_T3 CC_TYPE_CC_BITS_T3,
#define CC_TYPE_6_CC_BITS_T3 CC_TYPE_CC_BITS_T3,
#define CC_TYPE_7_CC_BITS_T3 CC_TYPE_CC_BITS_T3,
#define CC_TYPE_8_CC_BITS_T3 CC_TYPE_CC_BITS_T3,
#define CC_TYPE_9_CC_BITS_T3 CC_TYPE_CC_BITS_T3,
#define CC_TYPE_0_CC_BITS_T4 CC_TYPE_CC_BITS_T4,
#define CC_TYPE_1_CC_BITS_T4 CC_TYPE_CC_BITS_T4,
#define CC_TYPE_2_CC_BITS_T4 CC_TYPE_CC_BITS_T4,
#define CC_TYPE_3_CC_BITS_T4 CC_TYPE_CC_BITS_T4,
#define CC_TYPE_4_CC_BITS_T4 CC_TYPE_CC_BITS_T4,
#define CC_TYPE_5_CC_BITS_T4 CC_TYPE_CC_BITS_T4,
#define CC_TYPE_6_CC_BITS_T4 CC_TYPE_CC_BITS_T4,
#define CC_TYPE_7_CC_BITS_T4 CC_TYPE_CC_BITS_T4,
#define CC_TYPE_8_CC_BITS_T4 CC_TYPE_CC_BITS_T4,
#define CC_TYPE_9_CC_BITS_T4 CC_TYPE_CC_BITS_T4,
#define CC_TYPE_0_CC_BITS_T5 CC_TYPE_CC_BITS_T5,
#define CC_TYPE_1_CC_BITS_T5 CC_TYPE_CC_BITS_T5,
#define CC_TYPE_2_CC_BITS_T5 CC_TYPE_CC_BITS_T5,
#define CC_TYPE_3_CC_BITS_T5 CC_TYPE_CC_BITS_T5,
#define CC_TYPE_4_CC_BITS_T5 CC_TYPE_CC_BITS_T5,
#define CC_TYPE_5_CC_BITS_T5 CC_TYPE_CC_BITS_T5,
#define CC_TYPE_6_CC_BITS_T5 CC_TYPE_CC_BITS_T5,
#define CC_TYPE_7_CC_BITS_T5 CC_TYPE_CC_BITS_T5,
#define CC_TYPE_8_CC_BITS_T5 CC_TYPE_CC_BITS_T5,
#define CC_TYPE_9_CC_BITS_T5 CC_TYPE_CC_BITS_T5,
#define CC_TYPE_0_CC_BITS_T6 CC_TYPE_CC_BITS_T6,
#define CC_TYPE_1_CC_BITS_T6 CC_TYPE_CC_BITS_T6,
#define CC_TYPE_2_CC_BITS_T6 CC_TYPE_CC_BITS_T6,
#define CC_TYPE_3_CC_BITS_T6 CC_TYPE_CC_BITS_T6,
#define CC_TYPE_4_CC_BITS_T6 CC_TYPE_CC_BITS_T6,
#define CC_TYPE_5_CC_BITS_T6 CC_TYPE_CC_BITS_T6,
#define CC_TYPE_6_CC_BITS_T6 CC_TYPE_CC_BITS_T6,
#define CC_TYPE_7_CC_BITS_T6 CC_TYPE_CC_BITS_T6,
#define CC_TYPE_8_CC_BITS_T6 CC_TYPE_CC_BITS_T6,
#define CC_TYPE_9_CC_BITS_T6 CC_TYPE_CC_BITS_T6,
#define CC_TYPE_0_CC_BITS_T7 CC_TYPE_CC_BITS_T7,
#define CC_TYPE_1_CC_BITS_T7 CC_TYPE_CC_BITS_T7,
#define CC_TYPE_2_CC_BITS_T7 CC_TYPE_CC_BITS_T7,
#define CC_TYPE_3_CC_BITS_T7 CC_TYPE_CC_BITS_T7,
#define CC_TYPE_4_CC_BITS_T7 CC_TYPE_CC_BITS_T7,
#define CC_TYPE_5_CC_BITS_T7 CC_TYPE_CC_BITS_T7,
#define CC_TYPE_6_CC_BITS_T7 CC_TYPE_CC_BITS_T7,
#define CC_TYPE_7_CC_BITS_T7 CC_TYPE_CC_BITS_T7,
#define CC_TYPE_8_CC_BITS_T7 CC_TYPE_CC_BITS_T7,
#define CC_TYPE_9_CC_BITS_T7 CC_TYPE_CC_BITS_T7,
#define CC_TYPE_0_CC_BITS_T8 CC_TYPE_CC_BITS_T8,
#define CC_TYPE_1_CC_BITS_T8 CC_TYPE_CC_BITS_T8,
#define CC_TYPE_2_CC_BITS_T8 CC_TYPE_CC_BITS_T8,
#define CC_TYPE_3_CC_BITS_T8 CC_TYPE_CC_BITS_T8,
#define CC_TYPE_4_CC_BITS_T8 CC_TYPE_CC_BITS_T8,
#define CC_TYPE_5_CC_BITS_T8 CC_TYPE_CC_BITS_T8,
#define CC_TYPE_6_CC_BITS_T8 CC_TYPE_CC_BITS_T8,
#define CC_TYPE_7_CC_BITS_T8 CC_TYPE_CC_BITS_T8,
#define CC_TYPE_8_CC_BITS_T8 CC_TYPE_CC_BITS_T8,
#define CC_TYPE_9_CC_BITS_T8 CC_TYPE_CC_BITS_T8,
#define CC_TYPE_0_CC_BITS_T9 CC_TYPE_CC_BITS_T9,
#define CC_TYPE_1_CC_BITS_T9 CC_TYPE_CC_BITS_T9,
#define CC_TYPE_2_CC_BITS_T9 CC_TYPE_CC_BITS_T9,
#define CC_TYPE_3_CC_BITS_T9 CC_TYPE_CC_BITS_T9,
#define CC_TYPE_4_CC_BITS_T9 CC_TYPE_CC_BITS_T9,
#define CC_TYPE_5_CC_BITS_T9 CC_TYPE_CC_BITS_T9,
#define CC_TYPE_6_CC_BITS_T9 CC_TYPE_CC_BITS_T9,
#define CC_TYPE_7_CC_BITS_T9 CC_TYPE_CC_BITS_T9,
#define CC_TYPE_8_CC_BITS_T9 CC_TYPE_CC_BITS_T9,
#define CC_TYPE_9_CC_BITS_T9 CC_TYPE_CC_BITS_T9,
#define CC_TYPE_0_CC_BITS_T10 CC_TYPE_CC_BITS_T10,
#define CC_TYPE_1_CC_BITS_T10 CC_TYPE_CC_BITS_T10,
#define CC_TYPE_2_CC_BITS_T10 CC_TYPE_CC_BITS_T10,
#define CC_TYPE_3_CC_BITS_T10 CC_TYPE_CC_BITS_T10,
#define CC_TYPE_4_CC_BITS_T10 CC_TYPE_CC_BITS_T10,
#define CC_TYPE_5_CC_BITS_T10 CC_TYPE_CC_BITS_T10,
#define CC_TYPE_6_CC_BITS_T10 CC_TYPE_CC_BITS_T10,
#define CC_TYPE_7_CC_BITS_T10 CC_TYPE_CC_BITS_T10,
#define CC_TYPE_8_CC_BITS_T10 CC_TYPE_CC_BITS_T10,
#define CC_TYPE_9_CC_BITS_T10 CC_TYPE_CC_BITS_T10,
#define CC_TYPE_0_CC_BITS_T11 CC_TYPE_CC_BITS_T11,
#define CC_TYPE_1_CC_BITS_T11 CC_TYPE_CC_BITS_T11,
#define CC_TYPE_2_CC_BITS_T11 CC_TYPE_CC_BITS_T11,
#define CC_TYPE_3_CC_BITS_T11 CC_TYPE_CC_BITS_T11,
#define CC_TYPE_4_CC_BITS_T11 CC_TYPE_CC_BITS_T11,
#define CC_TYPE_5_CC_BITS_T11 CC_TYPE_CC_BITS_T11,
#define CC_TYPE_6_CC_BITS_T11 CC_TYPE_CC_BITS_T11,
#define CC_TYPE_7_CC_BITS_T11 CC_TYPE_CC_BITS_T11,
#define CC_TYPE_8_CC_BITS_T11 CC_TYPE_CC_BITS_T11,
#define CC_TYPE_9_CC_BITS_T11 CC_TYPE_CC_BITS_T11,
#define CC_TYPE_0_CC_BITS_T12 CC_TYPE_CC_BITS_T12,
#define CC_TYPE_1_CC_BITS_T12 CC_TYPE_CC_BITS_T12,
#define CC_TYPE_2_CC_BITS_T12 CC_TYPE_CC_BITS_T12,
#define CC_TYPE_3_CC_BITS_T12 CC_TYPE_CC_BITS_T12,
#define CC_TYPE_4_CC_BITS_T12 CC_TYPE_CC_BITS_T12,
#define CC_TYPE_5_CC_BITS_T12 CC_TYPE_CC_BITS_T12,
#define CC_TYPE_6_CC_BITS_T12 CC_TYPE_CC_BITS_T12,
#define CC_TYPE_7_CC_BITS_T12 CC_TYPE_CC_BITS_T12,
#define CC_TYPE_8_CC_BITS_T12 CC_TYPE_CC_BITS_T12,
#define CC_TYPE_9_CC_BITS_T12 CC_TYPE_CC_BITS_T12,
#define CC_TYPE_0_CC_BITS_T13 CC_TYPE_CC_BITS_T13,
#define CC_TYPE_1_CC_BITS_T13 CC_TYPE_CC_BITS_T13,
#define CC_TYPE_2_CC_BITS_T13 CC_TYPE_CC_BITS_T13,
#define CC_TYPE_3_CC_BITS_T13 CC_TYPE_CC_BITS_T13,
#define CC_TYPE_4_CC_BITS_T13 CC_TYPE_CC_BITS_T13,
#define CC_TYPE_5_CC_BITS_T13 CC_TYPE_CC_BITS_T13,
#define CC_TYPE_6_CC_BITS_T13 CC_TYPE_CC_BITS_T13,
#define CC_TYPE_7_CC_BITS_T13 CC_TYPE_CC_BITS_T13,
#define CC_TYPE_8_CC_BITS_T13 CC_TYPE_CC_BITS_T13,
#define CC_TYPE_9_CC_BITS_T13 CC_TYPE_CC_BITS_T13,
#define CC_TYPE_0_CC_BITS_T14 CC_TYPE_CC_BITS_T14,
#define CC_TYPE_1_CC_BITS_T14 CC_TYPE_CC_BITS_T14,
#define CC_TYPE_2_CC_BITS_T14 CC_TYPE_CC_BITS_T14,
#define CC_TYPE_3_CC_BITS_T14 CC_TYPE_CC_BITS_T14,
#define CC_TYPE_4_CC_BITS_T14 CC_TYPE_CC_BITS_T14,
#define CC_TYPE_5_CC_BITS_T14 CC_TYPE_CC_BITS_T14,
#define CC_TYPE_6_CC_BITS_T14 CC_TYPE_CC_BITS_T14,
#define CC_TYPE_7_CC_BITS_T14 CC_TYPE_CC_BITS_T14,
#define CC_TYPE_8_CC_BITS_T14 CC_TYPE_CC_BITS_T14,
#define CC_TYPE_9_CC_BITS_T14 CC_TYPE_CC_BITS_T14,
#define CC_TYPE_0_CC_BITS_T15 CC_TYPE_CC_BITS_T15,
#define CC_TYPE_1_CC_BITS_T15 CC_TYPE_CC_BITS_T15,
#define CC_TYPE_2_CC_BITS_T15 CC_TYPE_CC_BITS_T15,
#define CC_TYPE_3_CC_BITS_T15 CC_TYPE_CC_BITS_T15,
#define CC_TYPE_4_CC_BITS_T15 CC_TYPE_CC_BITS_T15,
#define CC_TYPE_5_CC_BITS_T15 CC_TYPE_CC_BITS_T15,
#define CC_TYPE_6_CC_BITS_T15 CC_TYPE_CC_BITS_T15,
#define CC_TYPE_7_CC_BITS_T15 CC_TYPE_CC_BITS_T15,
#define CC_TYPE_8_CC_BITS_T15 CC_TYPE_CC_BITS_T15,
#define CC_TYPE_9_CC_BITS_T15 CC_TYPE_CC_BITS_T15,
#define CC_TYPE_0_CC_BITS_T16 CC_TYPE_CC_BITS_T16,
#define CC_TYPE_1_CC_BITS_T16 CC_TYPE_CC_BITS_T16,
#define CC_TYPE_2_CC_BITS_T16 CC_TYPE_CC_BITS_T16,
#define CC_TYPE_3_CC_BITS_T16 CC_TYPE_CC_BITS_T16,
#define CC_TYPE_4_CC_BITS_T16 CC_TYPE_CC_BITS_T16,
#define CC_TYPE_5_CC_BITS_T16 CC_TYPE_CC_BITS_T16,
#define CC_TYPE_6_CC_BITS_T16 CC_TYPE_CC_BITS_T16,
#define CC_TYPE_7_CC_BITS_T16 CC_TYPE_CC_BITS_T16,
#define CC_TYPE_8_CC_BITS_T16 CC_TYPE_CC_BITS_T16,
#define CC_TYPE_9_CC_BITS_T16 CC_TYPE_CC_BITS_T16,
#define CC_TYPE_0_CC_BITS_T17 CC_TYPE_CC_BITS_T17,
#define CC_TYPE_1_CC_BITS_T17 CC_TYPE_CC_BITS_T17,
#define CC_TYPE_2_CC_BITS_T17 CC_TYPE_CC_BITS_T17,
#define CC_TYPE_3_CC_BITS_T17 CC_TYPE_CC_BITS_T17,
#define CC_TYPE_4_CC_BITS_T17 CC_TYPE_CC_BITS_T17,
#define CC_TYPE_5_CC_BITS_T17 CC_TYPE_CC_BITS_T17,
#define CC_TYPE_6_CC_BITS_T17 CC_TYPE_CC_BITS_T17,
#define CC_TYPE_7_CC_BITS_T17 CC_TYPE_CC_BITS_T17,
#define CC_TYPE_8_CC_BITS_T17 CC_TYPE_CC_BITS_T17,
#define CC_TYPE_9_CC_BITS_T17 CC_TYPE_CC_BITS_T17,
#define CC_TYPE_0_CC_BITS_T18 CC_TYPE_CC_BITS_T18,
#define CC_TYPE_1_CC_BITS_T18 CC_TYPE_CC_BITS_T18,
#define CC_TYPE_2_CC_BITS_T18 CC_TYPE_CC_BITS_T18,
#define CC_TYPE_3_CC_BITS_T18 CC_TYPE_CC_BITS_T18,
#define CC_TYPE_4_CC_BITS_T18 CC_TYPE_CC_BITS_T18,
#define CC_TYPE_5_CC_BITS_T18 CC_TYPE_CC_BITS_T18,
#define CC_TYPE_6_CC_BITS_T18 CC_TYPE_CC_BITS_T18,
#define CC_TYPE_7_CC_BITS_T18 CC_TYPE_CC_BITS_T18,
#define CC_TYPE_8_CC_BITS_T18 CC_TYPE_CC_BITS_T18,
#define CC_TYPE_9_CC_BITS_T18 CC_TYPE_CC_BITS_T18,
#define CC_TYPE_0_CC_BITS_T19 CC_TYPE_CC_BITS_T19,
#define CC_TYPE_1_CC_BITS_T19 CC_TYPE_CC_BITS_T19,
#define CC_TYPE_2_CC_BITS_T19 CC_TYPE_CC_BITS_T19,
#define CC_TYPE_3_CC_BITS_T19 CC_TYPE_CC_BITS_T19,
#define CC_TYPE_4_CC_BITS_T19 CC_TYPE_CC_BITS_T19,
#define CC_TYPE_5_CC_BITS_T19 CC_TYPE_CC_BITS_T19,
#define CC_TYPE_6_CC_BITS_T19 CC_TYPE_CC_BITS_T19,
#define CC_TYPE_7_CC_BITS_T19 CC_TYPE_CC_BITS_T19,
#define CC_TYPE_8_CC_BITS_T19 CC_TYPE_CC_BITS_T19,
#define CC_TYPE_9_CC_BITS_T19 CC_TYPE_CC_BITS_T19,

#ifndef CC_GENERIC_PRESERVE_TYPE
#undef Tbase
#endif
