//This file is automatically generated, modifications will be lost!
#define CC_CONTAINER_DECLARE_PRESET_CCCollection \
CC_CONTAINER_DECLARE(CCCollection, CCCollectionEntry);

#define CC_CONTAINER_DECLARE_PRESET_CCDictionary \
CC_CONTAINER_DECLARE(CCDictionary, CCString, uint32_t);

#define CC_CONTAINER_DECLARE_PRESET_CCLinkedList \
CC_CONTAINER_DECLARE(CCLinkedList, CCArray);

#define CC_CONTAINER_DECLARE_PRESET_CCList \
CC_CONTAINER_DECLARE(CCList, uint64_t);

#define CC_CONTAINER_DECLARE_PRESET_CCOrderedCollection \
CC_CONTAINER_DECLARE(CCOrderedCollection, CCString); \
CC_CONTAINER_DECLARE(CCOrderedCollection, FSPath); \
CC_CONTAINER_DECLARE(CCOrderedCollection, FSPathComponent);
