//This file is automatically generated, modifications will be lost!
CC_CONTAINER_DECLARE(CCCollection, CCCollectionEntry);
CC_CONTAINER_DECLARE(CCDictionary, CCString, uint32_t);
CC_CONTAINER_DECLARE(CCLinkedList, CCArray);
CC_CONTAINER_DECLARE(CCList, uint64_t);
CC_CONTAINER_DECLARE(CCOrderedCollection, CCString);
CC_CONTAINER_DECLARE(CCOrderedCollection, FSPath);
CC_CONTAINER_DECLARE(CCOrderedCollection, FSPathComponent);
