//This file is automatically generated, modifications will be lost!
#define CC_CONTAINER_DECLARE_PRESET_CCArray() \
CC_CONTAINER_DECLARE(CCArray, CCArray); \
CC_CONTAINER_DECLARE(CCArray, CC_CONTAINER(CCArray, uintmax_t)); \
CC_CONTAINER_DECLARE(CCArray, uint8_t);

#define CC_CONTAINER_DECLARE_PRESET_CCCollection() \
CC_CONTAINER_DECLARE(CCCollection, CCCollectionEntry); \
CC_CONTAINER_DECLARE(CCCollection, FSPath);

#define CC_CONTAINER_DECLARE_PRESET_CCConcurrentBuffer()

#define CC_CONTAINER_DECLARE_PRESET_CCConcurrentIndexMap()

#define CC_CONTAINER_DECLARE_PRESET_CCConcurrentQueue()

#define CC_CONTAINER_DECLARE_PRESET_CCData()

#define CC_CONTAINER_DECLARE_PRESET_CCDictionary() \
CC_CONTAINER_DECLARE(CCDictionary, CCString, FSVirtualNode); \
CC_CONTAINER_DECLARE(CCDictionary, CCString, uint32_t);

#define CC_CONTAINER_DECLARE_PRESET_CCHashMap()

#define CC_CONTAINER_DECLARE_PRESET_CCLinkedList() \
CC_CONTAINER_DECLARE(CCLinkedList, CCArray);

#define CC_CONTAINER_DECLARE_PRESET_CCList() \
CC_CONTAINER_DECLARE(CCList, uint64_t);

#define CC_CONTAINER_DECLARE_PRESET_CCOrderedCollection() \
CC_CONTAINER_DECLARE(CCOrderedCollection, CCString); \
CC_CONTAINER_DECLARE(CCOrderedCollection, FSPath); \
CC_CONTAINER_DECLARE(CCOrderedCollection, FSPathComponent);

#define CC_CONTAINER_DECLARE_PRESET_CCQueue()
