/*
 *  Copyright (c) 2020, Stefan Johnson
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without modification,
 *  are permitted provided that the following conditions are met:
 *
 *  1. Redistributions of source code must retain the above copyright notice, this list
 *     of conditions and the following disclaimer.
 *  2. Redistributions in binary form must reproduce the above copyright notice, this
 *     list of conditions and the following disclaimer in the documentation and/or other
 *     materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */


#define CC_TYPE_CC_GENERIC_T0(...) CC_GENERIC_T(0)
#define CC_TYPE_CC_GENERIC_T1(...) CC_GENERIC_T(1)
#define CC_TYPE_CC_GENERIC_T2(...) CC_GENERIC_T(2)
#define CC_TYPE_CC_GENERIC_T3(...) CC_GENERIC_T(3)
#define CC_TYPE_CC_GENERIC_T4(...) CC_GENERIC_T(4)
#define CC_TYPE_CC_GENERIC_T5(...) CC_GENERIC_T(5)
#define CC_TYPE_CC_GENERIC_T6(...) CC_GENERIC_T(6)
#define CC_TYPE_CC_GENERIC_T7(...) CC_GENERIC_T(7)
#define CC_TYPE_CC_GENERIC_T8(...) CC_GENERIC_T(8)
#define CC_TYPE_CC_GENERIC_T9(...) CC_GENERIC_T(9)
#define CC_TYPE_CC_GENERIC_T10(...) CC_GENERIC_T(10)
#define CC_TYPE_CC_GENERIC_T11(...) CC_GENERIC_T(11)
#define CC_TYPE_CC_GENERIC_T12(...) CC_GENERIC_T(12)
#define CC_TYPE_CC_GENERIC_T13(...) CC_GENERIC_T(13)
#define CC_TYPE_CC_GENERIC_T14(...) CC_GENERIC_T(14)
#define CC_TYPE_CC_GENERIC_T15(...) CC_GENERIC_T(15)
#define CC_TYPE_CC_GENERIC_T16(...) CC_GENERIC_T(16)
#define CC_TYPE_CC_GENERIC_T17(...) CC_GENERIC_T(17)
#define CC_TYPE_CC_GENERIC_T18(...) CC_GENERIC_T(18)
#define CC_TYPE_CC_GENERIC_T19(...) CC_GENERIC_T(19)
#define CC_TYPE_0_CC_GENERIC_T0 CC_TYPE_CC_GENERIC_T0,
#define CC_TYPE_1_CC_GENERIC_T0 CC_TYPE_CC_GENERIC_T0,
#define CC_TYPE_2_CC_GENERIC_T0 CC_TYPE_CC_GENERIC_T0,
#define CC_TYPE_3_CC_GENERIC_T0 CC_TYPE_CC_GENERIC_T0,
#define CC_TYPE_4_CC_GENERIC_T0 CC_TYPE_CC_GENERIC_T0,
#define CC_TYPE_5_CC_GENERIC_T0 CC_TYPE_CC_GENERIC_T0,
#define CC_TYPE_6_CC_GENERIC_T0 CC_TYPE_CC_GENERIC_T0,
#define CC_TYPE_7_CC_GENERIC_T0 CC_TYPE_CC_GENERIC_T0,
#define CC_TYPE_8_CC_GENERIC_T0 CC_TYPE_CC_GENERIC_T0,
#define CC_TYPE_9_CC_GENERIC_T0 CC_TYPE_CC_GENERIC_T0,
#define CC_TYPE_0_CC_GENERIC_T1 CC_TYPE_CC_GENERIC_T1,
#define CC_TYPE_1_CC_GENERIC_T1 CC_TYPE_CC_GENERIC_T1,
#define CC_TYPE_2_CC_GENERIC_T1 CC_TYPE_CC_GENERIC_T1,
#define CC_TYPE_3_CC_GENERIC_T1 CC_TYPE_CC_GENERIC_T1,
#define CC_TYPE_4_CC_GENERIC_T1 CC_TYPE_CC_GENERIC_T1,
#define CC_TYPE_5_CC_GENERIC_T1 CC_TYPE_CC_GENERIC_T1,
#define CC_TYPE_6_CC_GENERIC_T1 CC_TYPE_CC_GENERIC_T1,
#define CC_TYPE_7_CC_GENERIC_T1 CC_TYPE_CC_GENERIC_T1,
#define CC_TYPE_8_CC_GENERIC_T1 CC_TYPE_CC_GENERIC_T1,
#define CC_TYPE_9_CC_GENERIC_T1 CC_TYPE_CC_GENERIC_T1,
#define CC_TYPE_0_CC_GENERIC_T2 CC_TYPE_CC_GENERIC_T2,
#define CC_TYPE_1_CC_GENERIC_T2 CC_TYPE_CC_GENERIC_T2,
#define CC_TYPE_2_CC_GENERIC_T2 CC_TYPE_CC_GENERIC_T2,
#define CC_TYPE_3_CC_GENERIC_T2 CC_TYPE_CC_GENERIC_T2,
#define CC_TYPE_4_CC_GENERIC_T2 CC_TYPE_CC_GENERIC_T2,
#define CC_TYPE_5_CC_GENERIC_T2 CC_TYPE_CC_GENERIC_T2,
#define CC_TYPE_6_CC_GENERIC_T2 CC_TYPE_CC_GENERIC_T2,
#define CC_TYPE_7_CC_GENERIC_T2 CC_TYPE_CC_GENERIC_T2,
#define CC_TYPE_8_CC_GENERIC_T2 CC_TYPE_CC_GENERIC_T2,
#define CC_TYPE_9_CC_GENERIC_T2 CC_TYPE_CC_GENERIC_T2,
#define CC_TYPE_0_CC_GENERIC_T3 CC_TYPE_CC_GENERIC_T3,
#define CC_TYPE_1_CC_GENERIC_T3 CC_TYPE_CC_GENERIC_T3,
#define CC_TYPE_2_CC_GENERIC_T3 CC_TYPE_CC_GENERIC_T3,
#define CC_TYPE_3_CC_GENERIC_T3 CC_TYPE_CC_GENERIC_T3,
#define CC_TYPE_4_CC_GENERIC_T3 CC_TYPE_CC_GENERIC_T3,
#define CC_TYPE_5_CC_GENERIC_T3 CC_TYPE_CC_GENERIC_T3,
#define CC_TYPE_6_CC_GENERIC_T3 CC_TYPE_CC_GENERIC_T3,
#define CC_TYPE_7_CC_GENERIC_T3 CC_TYPE_CC_GENERIC_T3,
#define CC_TYPE_8_CC_GENERIC_T3 CC_TYPE_CC_GENERIC_T3,
#define CC_TYPE_9_CC_GENERIC_T3 CC_TYPE_CC_GENERIC_T3,
#define CC_TYPE_0_CC_GENERIC_T4 CC_TYPE_CC_GENERIC_T4,
#define CC_TYPE_1_CC_GENERIC_T4 CC_TYPE_CC_GENERIC_T4,
#define CC_TYPE_2_CC_GENERIC_T4 CC_TYPE_CC_GENERIC_T4,
#define CC_TYPE_3_CC_GENERIC_T4 CC_TYPE_CC_GENERIC_T4,
#define CC_TYPE_4_CC_GENERIC_T4 CC_TYPE_CC_GENERIC_T4,
#define CC_TYPE_5_CC_GENERIC_T4 CC_TYPE_CC_GENERIC_T4,
#define CC_TYPE_6_CC_GENERIC_T4 CC_TYPE_CC_GENERIC_T4,
#define CC_TYPE_7_CC_GENERIC_T4 CC_TYPE_CC_GENERIC_T4,
#define CC_TYPE_8_CC_GENERIC_T4 CC_TYPE_CC_GENERIC_T4,
#define CC_TYPE_9_CC_GENERIC_T4 CC_TYPE_CC_GENERIC_T4,
#define CC_TYPE_0_CC_GENERIC_T5 CC_TYPE_CC_GENERIC_T5,
#define CC_TYPE_1_CC_GENERIC_T5 CC_TYPE_CC_GENERIC_T5,
#define CC_TYPE_2_CC_GENERIC_T5 CC_TYPE_CC_GENERIC_T5,
#define CC_TYPE_3_CC_GENERIC_T5 CC_TYPE_CC_GENERIC_T5,
#define CC_TYPE_4_CC_GENERIC_T5 CC_TYPE_CC_GENERIC_T5,
#define CC_TYPE_5_CC_GENERIC_T5 CC_TYPE_CC_GENERIC_T5,
#define CC_TYPE_6_CC_GENERIC_T5 CC_TYPE_CC_GENERIC_T5,
#define CC_TYPE_7_CC_GENERIC_T5 CC_TYPE_CC_GENERIC_T5,
#define CC_TYPE_8_CC_GENERIC_T5 CC_TYPE_CC_GENERIC_T5,
#define CC_TYPE_9_CC_GENERIC_T5 CC_TYPE_CC_GENERIC_T5,
#define CC_TYPE_0_CC_GENERIC_T6 CC_TYPE_CC_GENERIC_T6,
#define CC_TYPE_1_CC_GENERIC_T6 CC_TYPE_CC_GENERIC_T6,
#define CC_TYPE_2_CC_GENERIC_T6 CC_TYPE_CC_GENERIC_T6,
#define CC_TYPE_3_CC_GENERIC_T6 CC_TYPE_CC_GENERIC_T6,
#define CC_TYPE_4_CC_GENERIC_T6 CC_TYPE_CC_GENERIC_T6,
#define CC_TYPE_5_CC_GENERIC_T6 CC_TYPE_CC_GENERIC_T6,
#define CC_TYPE_6_CC_GENERIC_T6 CC_TYPE_CC_GENERIC_T6,
#define CC_TYPE_7_CC_GENERIC_T6 CC_TYPE_CC_GENERIC_T6,
#define CC_TYPE_8_CC_GENERIC_T6 CC_TYPE_CC_GENERIC_T6,
#define CC_TYPE_9_CC_GENERIC_T6 CC_TYPE_CC_GENERIC_T6,
#define CC_TYPE_0_CC_GENERIC_T7 CC_TYPE_CC_GENERIC_T7,
#define CC_TYPE_1_CC_GENERIC_T7 CC_TYPE_CC_GENERIC_T7,
#define CC_TYPE_2_CC_GENERIC_T7 CC_TYPE_CC_GENERIC_T7,
#define CC_TYPE_3_CC_GENERIC_T7 CC_TYPE_CC_GENERIC_T7,
#define CC_TYPE_4_CC_GENERIC_T7 CC_TYPE_CC_GENERIC_T7,
#define CC_TYPE_5_CC_GENERIC_T7 CC_TYPE_CC_GENERIC_T7,
#define CC_TYPE_6_CC_GENERIC_T7 CC_TYPE_CC_GENERIC_T7,
#define CC_TYPE_7_CC_GENERIC_T7 CC_TYPE_CC_GENERIC_T7,
#define CC_TYPE_8_CC_GENERIC_T7 CC_TYPE_CC_GENERIC_T7,
#define CC_TYPE_9_CC_GENERIC_T7 CC_TYPE_CC_GENERIC_T7,
#define CC_TYPE_0_CC_GENERIC_T8 CC_TYPE_CC_GENERIC_T8,
#define CC_TYPE_1_CC_GENERIC_T8 CC_TYPE_CC_GENERIC_T8,
#define CC_TYPE_2_CC_GENERIC_T8 CC_TYPE_CC_GENERIC_T8,
#define CC_TYPE_3_CC_GENERIC_T8 CC_TYPE_CC_GENERIC_T8,
#define CC_TYPE_4_CC_GENERIC_T8 CC_TYPE_CC_GENERIC_T8,
#define CC_TYPE_5_CC_GENERIC_T8 CC_TYPE_CC_GENERIC_T8,
#define CC_TYPE_6_CC_GENERIC_T8 CC_TYPE_CC_GENERIC_T8,
#define CC_TYPE_7_CC_GENERIC_T8 CC_TYPE_CC_GENERIC_T8,
#define CC_TYPE_8_CC_GENERIC_T8 CC_TYPE_CC_GENERIC_T8,
#define CC_TYPE_9_CC_GENERIC_T8 CC_TYPE_CC_GENERIC_T8,
#define CC_TYPE_0_CC_GENERIC_T9 CC_TYPE_CC_GENERIC_T9,
#define CC_TYPE_1_CC_GENERIC_T9 CC_TYPE_CC_GENERIC_T9,
#define CC_TYPE_2_CC_GENERIC_T9 CC_TYPE_CC_GENERIC_T9,
#define CC_TYPE_3_CC_GENERIC_T9 CC_TYPE_CC_GENERIC_T9,
#define CC_TYPE_4_CC_GENERIC_T9 CC_TYPE_CC_GENERIC_T9,
#define CC_TYPE_5_CC_GENERIC_T9 CC_TYPE_CC_GENERIC_T9,
#define CC_TYPE_6_CC_GENERIC_T9 CC_TYPE_CC_GENERIC_T9,
#define CC_TYPE_7_CC_GENERIC_T9 CC_TYPE_CC_GENERIC_T9,
#define CC_TYPE_8_CC_GENERIC_T9 CC_TYPE_CC_GENERIC_T9,
#define CC_TYPE_9_CC_GENERIC_T9 CC_TYPE_CC_GENERIC_T9,
#define CC_TYPE_0_CC_GENERIC_T10 CC_TYPE_CC_GENERIC_T10,
#define CC_TYPE_1_CC_GENERIC_T10 CC_TYPE_CC_GENERIC_T10,
#define CC_TYPE_2_CC_GENERIC_T10 CC_TYPE_CC_GENERIC_T10,
#define CC_TYPE_3_CC_GENERIC_T10 CC_TYPE_CC_GENERIC_T10,
#define CC_TYPE_4_CC_GENERIC_T10 CC_TYPE_CC_GENERIC_T10,
#define CC_TYPE_5_CC_GENERIC_T10 CC_TYPE_CC_GENERIC_T10,
#define CC_TYPE_6_CC_GENERIC_T10 CC_TYPE_CC_GENERIC_T10,
#define CC_TYPE_7_CC_GENERIC_T10 CC_TYPE_CC_GENERIC_T10,
#define CC_TYPE_8_CC_GENERIC_T10 CC_TYPE_CC_GENERIC_T10,
#define CC_TYPE_9_CC_GENERIC_T10 CC_TYPE_CC_GENERIC_T10,
#define CC_TYPE_0_CC_GENERIC_T11 CC_TYPE_CC_GENERIC_T11,
#define CC_TYPE_1_CC_GENERIC_T11 CC_TYPE_CC_GENERIC_T11,
#define CC_TYPE_2_CC_GENERIC_T11 CC_TYPE_CC_GENERIC_T11,
#define CC_TYPE_3_CC_GENERIC_T11 CC_TYPE_CC_GENERIC_T11,
#define CC_TYPE_4_CC_GENERIC_T11 CC_TYPE_CC_GENERIC_T11,
#define CC_TYPE_5_CC_GENERIC_T11 CC_TYPE_CC_GENERIC_T11,
#define CC_TYPE_6_CC_GENERIC_T11 CC_TYPE_CC_GENERIC_T11,
#define CC_TYPE_7_CC_GENERIC_T11 CC_TYPE_CC_GENERIC_T11,
#define CC_TYPE_8_CC_GENERIC_T11 CC_TYPE_CC_GENERIC_T11,
#define CC_TYPE_9_CC_GENERIC_T11 CC_TYPE_CC_GENERIC_T11,
#define CC_TYPE_0_CC_GENERIC_T12 CC_TYPE_CC_GENERIC_T12,
#define CC_TYPE_1_CC_GENERIC_T12 CC_TYPE_CC_GENERIC_T12,
#define CC_TYPE_2_CC_GENERIC_T12 CC_TYPE_CC_GENERIC_T12,
#define CC_TYPE_3_CC_GENERIC_T12 CC_TYPE_CC_GENERIC_T12,
#define CC_TYPE_4_CC_GENERIC_T12 CC_TYPE_CC_GENERIC_T12,
#define CC_TYPE_5_CC_GENERIC_T12 CC_TYPE_CC_GENERIC_T12,
#define CC_TYPE_6_CC_GENERIC_T12 CC_TYPE_CC_GENERIC_T12,
#define CC_TYPE_7_CC_GENERIC_T12 CC_TYPE_CC_GENERIC_T12,
#define CC_TYPE_8_CC_GENERIC_T12 CC_TYPE_CC_GENERIC_T12,
#define CC_TYPE_9_CC_GENERIC_T12 CC_TYPE_CC_GENERIC_T12,
#define CC_TYPE_0_CC_GENERIC_T13 CC_TYPE_CC_GENERIC_T13,
#define CC_TYPE_1_CC_GENERIC_T13 CC_TYPE_CC_GENERIC_T13,
#define CC_TYPE_2_CC_GENERIC_T13 CC_TYPE_CC_GENERIC_T13,
#define CC_TYPE_3_CC_GENERIC_T13 CC_TYPE_CC_GENERIC_T13,
#define CC_TYPE_4_CC_GENERIC_T13 CC_TYPE_CC_GENERIC_T13,
#define CC_TYPE_5_CC_GENERIC_T13 CC_TYPE_CC_GENERIC_T13,
#define CC_TYPE_6_CC_GENERIC_T13 CC_TYPE_CC_GENERIC_T13,
#define CC_TYPE_7_CC_GENERIC_T13 CC_TYPE_CC_GENERIC_T13,
#define CC_TYPE_8_CC_GENERIC_T13 CC_TYPE_CC_GENERIC_T13,
#define CC_TYPE_9_CC_GENERIC_T13 CC_TYPE_CC_GENERIC_T13,
#define CC_TYPE_0_CC_GENERIC_T14 CC_TYPE_CC_GENERIC_T14,
#define CC_TYPE_1_CC_GENERIC_T14 CC_TYPE_CC_GENERIC_T14,
#define CC_TYPE_2_CC_GENERIC_T14 CC_TYPE_CC_GENERIC_T14,
#define CC_TYPE_3_CC_GENERIC_T14 CC_TYPE_CC_GENERIC_T14,
#define CC_TYPE_4_CC_GENERIC_T14 CC_TYPE_CC_GENERIC_T14,
#define CC_TYPE_5_CC_GENERIC_T14 CC_TYPE_CC_GENERIC_T14,
#define CC_TYPE_6_CC_GENERIC_T14 CC_TYPE_CC_GENERIC_T14,
#define CC_TYPE_7_CC_GENERIC_T14 CC_TYPE_CC_GENERIC_T14,
#define CC_TYPE_8_CC_GENERIC_T14 CC_TYPE_CC_GENERIC_T14,
#define CC_TYPE_9_CC_GENERIC_T14 CC_TYPE_CC_GENERIC_T14,
#define CC_TYPE_0_CC_GENERIC_T15 CC_TYPE_CC_GENERIC_T15,
#define CC_TYPE_1_CC_GENERIC_T15 CC_TYPE_CC_GENERIC_T15,
#define CC_TYPE_2_CC_GENERIC_T15 CC_TYPE_CC_GENERIC_T15,
#define CC_TYPE_3_CC_GENERIC_T15 CC_TYPE_CC_GENERIC_T15,
#define CC_TYPE_4_CC_GENERIC_T15 CC_TYPE_CC_GENERIC_T15,
#define CC_TYPE_5_CC_GENERIC_T15 CC_TYPE_CC_GENERIC_T15,
#define CC_TYPE_6_CC_GENERIC_T15 CC_TYPE_CC_GENERIC_T15,
#define CC_TYPE_7_CC_GENERIC_T15 CC_TYPE_CC_GENERIC_T15,
#define CC_TYPE_8_CC_GENERIC_T15 CC_TYPE_CC_GENERIC_T15,
#define CC_TYPE_9_CC_GENERIC_T15 CC_TYPE_CC_GENERIC_T15,
#define CC_TYPE_0_CC_GENERIC_T16 CC_TYPE_CC_GENERIC_T16,
#define CC_TYPE_1_CC_GENERIC_T16 CC_TYPE_CC_GENERIC_T16,
#define CC_TYPE_2_CC_GENERIC_T16 CC_TYPE_CC_GENERIC_T16,
#define CC_TYPE_3_CC_GENERIC_T16 CC_TYPE_CC_GENERIC_T16,
#define CC_TYPE_4_CC_GENERIC_T16 CC_TYPE_CC_GENERIC_T16,
#define CC_TYPE_5_CC_GENERIC_T16 CC_TYPE_CC_GENERIC_T16,
#define CC_TYPE_6_CC_GENERIC_T16 CC_TYPE_CC_GENERIC_T16,
#define CC_TYPE_7_CC_GENERIC_T16 CC_TYPE_CC_GENERIC_T16,
#define CC_TYPE_8_CC_GENERIC_T16 CC_TYPE_CC_GENERIC_T16,
#define CC_TYPE_9_CC_GENERIC_T16 CC_TYPE_CC_GENERIC_T16,
#define CC_TYPE_0_CC_GENERIC_T17 CC_TYPE_CC_GENERIC_T17,
#define CC_TYPE_1_CC_GENERIC_T17 CC_TYPE_CC_GENERIC_T17,
#define CC_TYPE_2_CC_GENERIC_T17 CC_TYPE_CC_GENERIC_T17,
#define CC_TYPE_3_CC_GENERIC_T17 CC_TYPE_CC_GENERIC_T17,
#define CC_TYPE_4_CC_GENERIC_T17 CC_TYPE_CC_GENERIC_T17,
#define CC_TYPE_5_CC_GENERIC_T17 CC_TYPE_CC_GENERIC_T17,
#define CC_TYPE_6_CC_GENERIC_T17 CC_TYPE_CC_GENERIC_T17,
#define CC_TYPE_7_CC_GENERIC_T17 CC_TYPE_CC_GENERIC_T17,
#define CC_TYPE_8_CC_GENERIC_T17 CC_TYPE_CC_GENERIC_T17,
#define CC_TYPE_9_CC_GENERIC_T17 CC_TYPE_CC_GENERIC_T17,
#define CC_TYPE_0_CC_GENERIC_T18 CC_TYPE_CC_GENERIC_T18,
#define CC_TYPE_1_CC_GENERIC_T18 CC_TYPE_CC_GENERIC_T18,
#define CC_TYPE_2_CC_GENERIC_T18 CC_TYPE_CC_GENERIC_T18,
#define CC_TYPE_3_CC_GENERIC_T18 CC_TYPE_CC_GENERIC_T18,
#define CC_TYPE_4_CC_GENERIC_T18 CC_TYPE_CC_GENERIC_T18,
#define CC_TYPE_5_CC_GENERIC_T18 CC_TYPE_CC_GENERIC_T18,
#define CC_TYPE_6_CC_GENERIC_T18 CC_TYPE_CC_GENERIC_T18,
#define CC_TYPE_7_CC_GENERIC_T18 CC_TYPE_CC_GENERIC_T18,
#define CC_TYPE_8_CC_GENERIC_T18 CC_TYPE_CC_GENERIC_T18,
#define CC_TYPE_9_CC_GENERIC_T18 CC_TYPE_CC_GENERIC_T18,
#define CC_TYPE_0_CC_GENERIC_T19 CC_TYPE_CC_GENERIC_T19,
#define CC_TYPE_1_CC_GENERIC_T19 CC_TYPE_CC_GENERIC_T19,
#define CC_TYPE_2_CC_GENERIC_T19 CC_TYPE_CC_GENERIC_T19,
#define CC_TYPE_3_CC_GENERIC_T19 CC_TYPE_CC_GENERIC_T19,
#define CC_TYPE_4_CC_GENERIC_T19 CC_TYPE_CC_GENERIC_T19,
#define CC_TYPE_5_CC_GENERIC_T19 CC_TYPE_CC_GENERIC_T19,
#define CC_TYPE_6_CC_GENERIC_T19 CC_TYPE_CC_GENERIC_T19,
#define CC_TYPE_7_CC_GENERIC_T19 CC_TYPE_CC_GENERIC_T19,
#define CC_TYPE_8_CC_GENERIC_T19 CC_TYPE_CC_GENERIC_T19,
#define CC_TYPE_9_CC_GENERIC_T19 CC_TYPE_CC_GENERIC_T19,

#define CC_PRESERVE_CC_TYPE_CC_GENERIC_T0 CC_TYPE_CC_GENERIC_T0
#define CC_PRESERVE_CC_TYPE_CC_GENERIC_T1 CC_TYPE_CC_GENERIC_T1
#define CC_PRESERVE_CC_TYPE_CC_GENERIC_T2 CC_TYPE_CC_GENERIC_T2
#define CC_PRESERVE_CC_TYPE_CC_GENERIC_T3 CC_TYPE_CC_GENERIC_T3
#define CC_PRESERVE_CC_TYPE_CC_GENERIC_T4 CC_TYPE_CC_GENERIC_T4
#define CC_PRESERVE_CC_TYPE_CC_GENERIC_T5 CC_TYPE_CC_GENERIC_T5
#define CC_PRESERVE_CC_TYPE_CC_GENERIC_T6 CC_TYPE_CC_GENERIC_T6
#define CC_PRESERVE_CC_TYPE_CC_GENERIC_T7 CC_TYPE_CC_GENERIC_T7
#define CC_PRESERVE_CC_TYPE_CC_GENERIC_T8 CC_TYPE_CC_GENERIC_T8
#define CC_PRESERVE_CC_TYPE_CC_GENERIC_T9 CC_TYPE_CC_GENERIC_T9
#define CC_PRESERVE_CC_TYPE_CC_GENERIC_T10 CC_TYPE_CC_GENERIC_T10
#define CC_PRESERVE_CC_TYPE_CC_GENERIC_T11 CC_TYPE_CC_GENERIC_T11
#define CC_PRESERVE_CC_TYPE_CC_GENERIC_T12 CC_TYPE_CC_GENERIC_T12
#define CC_PRESERVE_CC_TYPE_CC_GENERIC_T13 CC_TYPE_CC_GENERIC_T13
#define CC_PRESERVE_CC_TYPE_CC_GENERIC_T14 CC_TYPE_CC_GENERIC_T14
#define CC_PRESERVE_CC_TYPE_CC_GENERIC_T15 CC_TYPE_CC_GENERIC_T15
#define CC_PRESERVE_CC_TYPE_CC_GENERIC_T16 CC_TYPE_CC_GENERIC_T16
#define CC_PRESERVE_CC_TYPE_CC_GENERIC_T17 CC_TYPE_CC_GENERIC_T17
#define CC_PRESERVE_CC_TYPE_CC_GENERIC_T18 CC_TYPE_CC_GENERIC_T18
#define CC_PRESERVE_CC_TYPE_CC_GENERIC_T19 CC_TYPE_CC_GENERIC_T19

#define CC_TYPE_DECL_CC_GENERIC_T0(...) CC_GENERIC_T(0), __VA_ARGS__
#define CC_TYPE_DECL_CC_GENERIC_T1(...) CC_GENERIC_T(1), __VA_ARGS__
#define CC_TYPE_DECL_CC_GENERIC_T2(...) CC_GENERIC_T(2), __VA_ARGS__
#define CC_TYPE_DECL_CC_GENERIC_T3(...) CC_GENERIC_T(3), __VA_ARGS__
#define CC_TYPE_DECL_CC_GENERIC_T4(...) CC_GENERIC_T(4), __VA_ARGS__
#define CC_TYPE_DECL_CC_GENERIC_T5(...) CC_GENERIC_T(5), __VA_ARGS__
#define CC_TYPE_DECL_CC_GENERIC_T6(...) CC_GENERIC_T(6), __VA_ARGS__
#define CC_TYPE_DECL_CC_GENERIC_T7(...) CC_GENERIC_T(7), __VA_ARGS__
#define CC_TYPE_DECL_CC_GENERIC_T8(...) CC_GENERIC_T(8), __VA_ARGS__
#define CC_TYPE_DECL_CC_GENERIC_T9(...) CC_GENERIC_T(9), __VA_ARGS__
#define CC_TYPE_DECL_CC_GENERIC_T10(...) CC_GENERIC_T(10), __VA_ARGS__
#define CC_TYPE_DECL_CC_GENERIC_T11(...) CC_GENERIC_T(11), __VA_ARGS__
#define CC_TYPE_DECL_CC_GENERIC_T12(...) CC_GENERIC_T(12), __VA_ARGS__
#define CC_TYPE_DECL_CC_GENERIC_T13(...) CC_GENERIC_T(13), __VA_ARGS__
#define CC_TYPE_DECL_CC_GENERIC_T14(...) CC_GENERIC_T(14), __VA_ARGS__
#define CC_TYPE_DECL_CC_GENERIC_T15(...) CC_GENERIC_T(15), __VA_ARGS__
#define CC_TYPE_DECL_CC_GENERIC_T16(...) CC_GENERIC_T(16), __VA_ARGS__
#define CC_TYPE_DECL_CC_GENERIC_T17(...) CC_GENERIC_T(17), __VA_ARGS__
#define CC_TYPE_DECL_CC_GENERIC_T18(...) CC_GENERIC_T(18), __VA_ARGS__
#define CC_TYPE_DECL_CC_GENERIC_T19(...) CC_GENERIC_T(19), __VA_ARGS__
#define CC_TYPE_DECL_0_CC_GENERIC_T0 CC_TYPE_DECL_CC_GENERIC_T0,
#define CC_TYPE_DECL_1_CC_GENERIC_T0 CC_TYPE_DECL_CC_GENERIC_T0,
#define CC_TYPE_DECL_2_CC_GENERIC_T0 CC_TYPE_DECL_CC_GENERIC_T0,
#define CC_TYPE_DECL_3_CC_GENERIC_T0 CC_TYPE_DECL_CC_GENERIC_T0,
#define CC_TYPE_DECL_4_CC_GENERIC_T0 CC_TYPE_DECL_CC_GENERIC_T0,
#define CC_TYPE_DECL_5_CC_GENERIC_T0 CC_TYPE_DECL_CC_GENERIC_T0,
#define CC_TYPE_DECL_6_CC_GENERIC_T0 CC_TYPE_DECL_CC_GENERIC_T0,
#define CC_TYPE_DECL_7_CC_GENERIC_T0 CC_TYPE_DECL_CC_GENERIC_T0,
#define CC_TYPE_DECL_8_CC_GENERIC_T0 CC_TYPE_DECL_CC_GENERIC_T0,
#define CC_TYPE_DECL_9_CC_GENERIC_T0 CC_TYPE_DECL_CC_GENERIC_T0,
#define CC_TYPE_DECL_0_CC_GENERIC_T1 CC_TYPE_DECL_CC_GENERIC_T1,
#define CC_TYPE_DECL_1_CC_GENERIC_T1 CC_TYPE_DECL_CC_GENERIC_T1,
#define CC_TYPE_DECL_2_CC_GENERIC_T1 CC_TYPE_DECL_CC_GENERIC_T1,
#define CC_TYPE_DECL_3_CC_GENERIC_T1 CC_TYPE_DECL_CC_GENERIC_T1,
#define CC_TYPE_DECL_4_CC_GENERIC_T1 CC_TYPE_DECL_CC_GENERIC_T1,
#define CC_TYPE_DECL_5_CC_GENERIC_T1 CC_TYPE_DECL_CC_GENERIC_T1,
#define CC_TYPE_DECL_6_CC_GENERIC_T1 CC_TYPE_DECL_CC_GENERIC_T1,
#define CC_TYPE_DECL_7_CC_GENERIC_T1 CC_TYPE_DECL_CC_GENERIC_T1,
#define CC_TYPE_DECL_8_CC_GENERIC_T1 CC_TYPE_DECL_CC_GENERIC_T1,
#define CC_TYPE_DECL_9_CC_GENERIC_T1 CC_TYPE_DECL_CC_GENERIC_T1,
#define CC_TYPE_DECL_0_CC_GENERIC_T2 CC_TYPE_DECL_CC_GENERIC_T2,
#define CC_TYPE_DECL_1_CC_GENERIC_T2 CC_TYPE_DECL_CC_GENERIC_T2,
#define CC_TYPE_DECL_2_CC_GENERIC_T2 CC_TYPE_DECL_CC_GENERIC_T2,
#define CC_TYPE_DECL_3_CC_GENERIC_T2 CC_TYPE_DECL_CC_GENERIC_T2,
#define CC_TYPE_DECL_4_CC_GENERIC_T2 CC_TYPE_DECL_CC_GENERIC_T2,
#define CC_TYPE_DECL_5_CC_GENERIC_T2 CC_TYPE_DECL_CC_GENERIC_T2,
#define CC_TYPE_DECL_6_CC_GENERIC_T2 CC_TYPE_DECL_CC_GENERIC_T2,
#define CC_TYPE_DECL_7_CC_GENERIC_T2 CC_TYPE_DECL_CC_GENERIC_T2,
#define CC_TYPE_DECL_8_CC_GENERIC_T2 CC_TYPE_DECL_CC_GENERIC_T2,
#define CC_TYPE_DECL_9_CC_GENERIC_T2 CC_TYPE_DECL_CC_GENERIC_T2,
#define CC_TYPE_DECL_0_CC_GENERIC_T3 CC_TYPE_DECL_CC_GENERIC_T3,
#define CC_TYPE_DECL_1_CC_GENERIC_T3 CC_TYPE_DECL_CC_GENERIC_T3,
#define CC_TYPE_DECL_2_CC_GENERIC_T3 CC_TYPE_DECL_CC_GENERIC_T3,
#define CC_TYPE_DECL_3_CC_GENERIC_T3 CC_TYPE_DECL_CC_GENERIC_T3,
#define CC_TYPE_DECL_4_CC_GENERIC_T3 CC_TYPE_DECL_CC_GENERIC_T3,
#define CC_TYPE_DECL_5_CC_GENERIC_T3 CC_TYPE_DECL_CC_GENERIC_T3,
#define CC_TYPE_DECL_6_CC_GENERIC_T3 CC_TYPE_DECL_CC_GENERIC_T3,
#define CC_TYPE_DECL_7_CC_GENERIC_T3 CC_TYPE_DECL_CC_GENERIC_T3,
#define CC_TYPE_DECL_8_CC_GENERIC_T3 CC_TYPE_DECL_CC_GENERIC_T3,
#define CC_TYPE_DECL_9_CC_GENERIC_T3 CC_TYPE_DECL_CC_GENERIC_T3,
#define CC_TYPE_DECL_0_CC_GENERIC_T4 CC_TYPE_DECL_CC_GENERIC_T4,
#define CC_TYPE_DECL_1_CC_GENERIC_T4 CC_TYPE_DECL_CC_GENERIC_T4,
#define CC_TYPE_DECL_2_CC_GENERIC_T4 CC_TYPE_DECL_CC_GENERIC_T4,
#define CC_TYPE_DECL_3_CC_GENERIC_T4 CC_TYPE_DECL_CC_GENERIC_T4,
#define CC_TYPE_DECL_4_CC_GENERIC_T4 CC_TYPE_DECL_CC_GENERIC_T4,
#define CC_TYPE_DECL_5_CC_GENERIC_T4 CC_TYPE_DECL_CC_GENERIC_T4,
#define CC_TYPE_DECL_6_CC_GENERIC_T4 CC_TYPE_DECL_CC_GENERIC_T4,
#define CC_TYPE_DECL_7_CC_GENERIC_T4 CC_TYPE_DECL_CC_GENERIC_T4,
#define CC_TYPE_DECL_8_CC_GENERIC_T4 CC_TYPE_DECL_CC_GENERIC_T4,
#define CC_TYPE_DECL_9_CC_GENERIC_T4 CC_TYPE_DECL_CC_GENERIC_T4,
#define CC_TYPE_DECL_0_CC_GENERIC_T5 CC_TYPE_DECL_CC_GENERIC_T5,
#define CC_TYPE_DECL_1_CC_GENERIC_T5 CC_TYPE_DECL_CC_GENERIC_T5,
#define CC_TYPE_DECL_2_CC_GENERIC_T5 CC_TYPE_DECL_CC_GENERIC_T5,
#define CC_TYPE_DECL_3_CC_GENERIC_T5 CC_TYPE_DECL_CC_GENERIC_T5,
#define CC_TYPE_DECL_4_CC_GENERIC_T5 CC_TYPE_DECL_CC_GENERIC_T5,
#define CC_TYPE_DECL_5_CC_GENERIC_T5 CC_TYPE_DECL_CC_GENERIC_T5,
#define CC_TYPE_DECL_6_CC_GENERIC_T5 CC_TYPE_DECL_CC_GENERIC_T5,
#define CC_TYPE_DECL_7_CC_GENERIC_T5 CC_TYPE_DECL_CC_GENERIC_T5,
#define CC_TYPE_DECL_8_CC_GENERIC_T5 CC_TYPE_DECL_CC_GENERIC_T5,
#define CC_TYPE_DECL_9_CC_GENERIC_T5 CC_TYPE_DECL_CC_GENERIC_T5,
#define CC_TYPE_DECL_0_CC_GENERIC_T6 CC_TYPE_DECL_CC_GENERIC_T6,
#define CC_TYPE_DECL_1_CC_GENERIC_T6 CC_TYPE_DECL_CC_GENERIC_T6,
#define CC_TYPE_DECL_2_CC_GENERIC_T6 CC_TYPE_DECL_CC_GENERIC_T6,
#define CC_TYPE_DECL_3_CC_GENERIC_T6 CC_TYPE_DECL_CC_GENERIC_T6,
#define CC_TYPE_DECL_4_CC_GENERIC_T6 CC_TYPE_DECL_CC_GENERIC_T6,
#define CC_TYPE_DECL_5_CC_GENERIC_T6 CC_TYPE_DECL_CC_GENERIC_T6,
#define CC_TYPE_DECL_6_CC_GENERIC_T6 CC_TYPE_DECL_CC_GENERIC_T6,
#define CC_TYPE_DECL_7_CC_GENERIC_T6 CC_TYPE_DECL_CC_GENERIC_T6,
#define CC_TYPE_DECL_8_CC_GENERIC_T6 CC_TYPE_DECL_CC_GENERIC_T6,
#define CC_TYPE_DECL_9_CC_GENERIC_T6 CC_TYPE_DECL_CC_GENERIC_T6,
#define CC_TYPE_DECL_0_CC_GENERIC_T7 CC_TYPE_DECL_CC_GENERIC_T7,
#define CC_TYPE_DECL_1_CC_GENERIC_T7 CC_TYPE_DECL_CC_GENERIC_T7,
#define CC_TYPE_DECL_2_CC_GENERIC_T7 CC_TYPE_DECL_CC_GENERIC_T7,
#define CC_TYPE_DECL_3_CC_GENERIC_T7 CC_TYPE_DECL_CC_GENERIC_T7,
#define CC_TYPE_DECL_4_CC_GENERIC_T7 CC_TYPE_DECL_CC_GENERIC_T7,
#define CC_TYPE_DECL_5_CC_GENERIC_T7 CC_TYPE_DECL_CC_GENERIC_T7,
#define CC_TYPE_DECL_6_CC_GENERIC_T7 CC_TYPE_DECL_CC_GENERIC_T7,
#define CC_TYPE_DECL_7_CC_GENERIC_T7 CC_TYPE_DECL_CC_GENERIC_T7,
#define CC_TYPE_DECL_8_CC_GENERIC_T7 CC_TYPE_DECL_CC_GENERIC_T7,
#define CC_TYPE_DECL_9_CC_GENERIC_T7 CC_TYPE_DECL_CC_GENERIC_T7,
#define CC_TYPE_DECL_0_CC_GENERIC_T8 CC_TYPE_DECL_CC_GENERIC_T8,
#define CC_TYPE_DECL_1_CC_GENERIC_T8 CC_TYPE_DECL_CC_GENERIC_T8,
#define CC_TYPE_DECL_2_CC_GENERIC_T8 CC_TYPE_DECL_CC_GENERIC_T8,
#define CC_TYPE_DECL_3_CC_GENERIC_T8 CC_TYPE_DECL_CC_GENERIC_T8,
#define CC_TYPE_DECL_4_CC_GENERIC_T8 CC_TYPE_DECL_CC_GENERIC_T8,
#define CC_TYPE_DECL_5_CC_GENERIC_T8 CC_TYPE_DECL_CC_GENERIC_T8,
#define CC_TYPE_DECL_6_CC_GENERIC_T8 CC_TYPE_DECL_CC_GENERIC_T8,
#define CC_TYPE_DECL_7_CC_GENERIC_T8 CC_TYPE_DECL_CC_GENERIC_T8,
#define CC_TYPE_DECL_8_CC_GENERIC_T8 CC_TYPE_DECL_CC_GENERIC_T8,
#define CC_TYPE_DECL_9_CC_GENERIC_T8 CC_TYPE_DECL_CC_GENERIC_T8,
#define CC_TYPE_DECL_0_CC_GENERIC_T9 CC_TYPE_DECL_CC_GENERIC_T9,
#define CC_TYPE_DECL_1_CC_GENERIC_T9 CC_TYPE_DECL_CC_GENERIC_T9,
#define CC_TYPE_DECL_2_CC_GENERIC_T9 CC_TYPE_DECL_CC_GENERIC_T9,
#define CC_TYPE_DECL_3_CC_GENERIC_T9 CC_TYPE_DECL_CC_GENERIC_T9,
#define CC_TYPE_DECL_4_CC_GENERIC_T9 CC_TYPE_DECL_CC_GENERIC_T9,
#define CC_TYPE_DECL_5_CC_GENERIC_T9 CC_TYPE_DECL_CC_GENERIC_T9,
#define CC_TYPE_DECL_6_CC_GENERIC_T9 CC_TYPE_DECL_CC_GENERIC_T9,
#define CC_TYPE_DECL_7_CC_GENERIC_T9 CC_TYPE_DECL_CC_GENERIC_T9,
#define CC_TYPE_DECL_8_CC_GENERIC_T9 CC_TYPE_DECL_CC_GENERIC_T9,
#define CC_TYPE_DECL_9_CC_GENERIC_T9 CC_TYPE_DECL_CC_GENERIC_T9,
#define CC_TYPE_DECL_0_CC_GENERIC_T10 CC_TYPE_DECL_CC_GENERIC_T10,
#define CC_TYPE_DECL_1_CC_GENERIC_T10 CC_TYPE_DECL_CC_GENERIC_T10,
#define CC_TYPE_DECL_2_CC_GENERIC_T10 CC_TYPE_DECL_CC_GENERIC_T10,
#define CC_TYPE_DECL_3_CC_GENERIC_T10 CC_TYPE_DECL_CC_GENERIC_T10,
#define CC_TYPE_DECL_4_CC_GENERIC_T10 CC_TYPE_DECL_CC_GENERIC_T10,
#define CC_TYPE_DECL_5_CC_GENERIC_T10 CC_TYPE_DECL_CC_GENERIC_T10,
#define CC_TYPE_DECL_6_CC_GENERIC_T10 CC_TYPE_DECL_CC_GENERIC_T10,
#define CC_TYPE_DECL_7_CC_GENERIC_T10 CC_TYPE_DECL_CC_GENERIC_T10,
#define CC_TYPE_DECL_8_CC_GENERIC_T10 CC_TYPE_DECL_CC_GENERIC_T10,
#define CC_TYPE_DECL_9_CC_GENERIC_T10 CC_TYPE_DECL_CC_GENERIC_T10,
#define CC_TYPE_DECL_0_CC_GENERIC_T11 CC_TYPE_DECL_CC_GENERIC_T11,
#define CC_TYPE_DECL_1_CC_GENERIC_T11 CC_TYPE_DECL_CC_GENERIC_T11,
#define CC_TYPE_DECL_2_CC_GENERIC_T11 CC_TYPE_DECL_CC_GENERIC_T11,
#define CC_TYPE_DECL_3_CC_GENERIC_T11 CC_TYPE_DECL_CC_GENERIC_T11,
#define CC_TYPE_DECL_4_CC_GENERIC_T11 CC_TYPE_DECL_CC_GENERIC_T11,
#define CC_TYPE_DECL_5_CC_GENERIC_T11 CC_TYPE_DECL_CC_GENERIC_T11,
#define CC_TYPE_DECL_6_CC_GENERIC_T11 CC_TYPE_DECL_CC_GENERIC_T11,
#define CC_TYPE_DECL_7_CC_GENERIC_T11 CC_TYPE_DECL_CC_GENERIC_T11,
#define CC_TYPE_DECL_8_CC_GENERIC_T11 CC_TYPE_DECL_CC_GENERIC_T11,
#define CC_TYPE_DECL_9_CC_GENERIC_T11 CC_TYPE_DECL_CC_GENERIC_T11,
#define CC_TYPE_DECL_0_CC_GENERIC_T12 CC_TYPE_DECL_CC_GENERIC_T12,
#define CC_TYPE_DECL_1_CC_GENERIC_T12 CC_TYPE_DECL_CC_GENERIC_T12,
#define CC_TYPE_DECL_2_CC_GENERIC_T12 CC_TYPE_DECL_CC_GENERIC_T12,
#define CC_TYPE_DECL_3_CC_GENERIC_T12 CC_TYPE_DECL_CC_GENERIC_T12,
#define CC_TYPE_DECL_4_CC_GENERIC_T12 CC_TYPE_DECL_CC_GENERIC_T12,
#define CC_TYPE_DECL_5_CC_GENERIC_T12 CC_TYPE_DECL_CC_GENERIC_T12,
#define CC_TYPE_DECL_6_CC_GENERIC_T12 CC_TYPE_DECL_CC_GENERIC_T12,
#define CC_TYPE_DECL_7_CC_GENERIC_T12 CC_TYPE_DECL_CC_GENERIC_T12,
#define CC_TYPE_DECL_8_CC_GENERIC_T12 CC_TYPE_DECL_CC_GENERIC_T12,
#define CC_TYPE_DECL_9_CC_GENERIC_T12 CC_TYPE_DECL_CC_GENERIC_T12,
#define CC_TYPE_DECL_0_CC_GENERIC_T13 CC_TYPE_DECL_CC_GENERIC_T13,
#define CC_TYPE_DECL_1_CC_GENERIC_T13 CC_TYPE_DECL_CC_GENERIC_T13,
#define CC_TYPE_DECL_2_CC_GENERIC_T13 CC_TYPE_DECL_CC_GENERIC_T13,
#define CC_TYPE_DECL_3_CC_GENERIC_T13 CC_TYPE_DECL_CC_GENERIC_T13,
#define CC_TYPE_DECL_4_CC_GENERIC_T13 CC_TYPE_DECL_CC_GENERIC_T13,
#define CC_TYPE_DECL_5_CC_GENERIC_T13 CC_TYPE_DECL_CC_GENERIC_T13,
#define CC_TYPE_DECL_6_CC_GENERIC_T13 CC_TYPE_DECL_CC_GENERIC_T13,
#define CC_TYPE_DECL_7_CC_GENERIC_T13 CC_TYPE_DECL_CC_GENERIC_T13,
#define CC_TYPE_DECL_8_CC_GENERIC_T13 CC_TYPE_DECL_CC_GENERIC_T13,
#define CC_TYPE_DECL_9_CC_GENERIC_T13 CC_TYPE_DECL_CC_GENERIC_T13,
#define CC_TYPE_DECL_0_CC_GENERIC_T14 CC_TYPE_DECL_CC_GENERIC_T14,
#define CC_TYPE_DECL_1_CC_GENERIC_T14 CC_TYPE_DECL_CC_GENERIC_T14,
#define CC_TYPE_DECL_2_CC_GENERIC_T14 CC_TYPE_DECL_CC_GENERIC_T14,
#define CC_TYPE_DECL_3_CC_GENERIC_T14 CC_TYPE_DECL_CC_GENERIC_T14,
#define CC_TYPE_DECL_4_CC_GENERIC_T14 CC_TYPE_DECL_CC_GENERIC_T14,
#define CC_TYPE_DECL_5_CC_GENERIC_T14 CC_TYPE_DECL_CC_GENERIC_T14,
#define CC_TYPE_DECL_6_CC_GENERIC_T14 CC_TYPE_DECL_CC_GENERIC_T14,
#define CC_TYPE_DECL_7_CC_GENERIC_T14 CC_TYPE_DECL_CC_GENERIC_T14,
#define CC_TYPE_DECL_8_CC_GENERIC_T14 CC_TYPE_DECL_CC_GENERIC_T14,
#define CC_TYPE_DECL_9_CC_GENERIC_T14 CC_TYPE_DECL_CC_GENERIC_T14,
#define CC_TYPE_DECL_0_CC_GENERIC_T15 CC_TYPE_DECL_CC_GENERIC_T15,
#define CC_TYPE_DECL_1_CC_GENERIC_T15 CC_TYPE_DECL_CC_GENERIC_T15,
#define CC_TYPE_DECL_2_CC_GENERIC_T15 CC_TYPE_DECL_CC_GENERIC_T15,
#define CC_TYPE_DECL_3_CC_GENERIC_T15 CC_TYPE_DECL_CC_GENERIC_T15,
#define CC_TYPE_DECL_4_CC_GENERIC_T15 CC_TYPE_DECL_CC_GENERIC_T15,
#define CC_TYPE_DECL_5_CC_GENERIC_T15 CC_TYPE_DECL_CC_GENERIC_T15,
#define CC_TYPE_DECL_6_CC_GENERIC_T15 CC_TYPE_DECL_CC_GENERIC_T15,
#define CC_TYPE_DECL_7_CC_GENERIC_T15 CC_TYPE_DECL_CC_GENERIC_T15,
#define CC_TYPE_DECL_8_CC_GENERIC_T15 CC_TYPE_DECL_CC_GENERIC_T15,
#define CC_TYPE_DECL_9_CC_GENERIC_T15 CC_TYPE_DECL_CC_GENERIC_T15,
#define CC_TYPE_DECL_0_CC_GENERIC_T16 CC_TYPE_DECL_CC_GENERIC_T16,
#define CC_TYPE_DECL_1_CC_GENERIC_T16 CC_TYPE_DECL_CC_GENERIC_T16,
#define CC_TYPE_DECL_2_CC_GENERIC_T16 CC_TYPE_DECL_CC_GENERIC_T16,
#define CC_TYPE_DECL_3_CC_GENERIC_T16 CC_TYPE_DECL_CC_GENERIC_T16,
#define CC_TYPE_DECL_4_CC_GENERIC_T16 CC_TYPE_DECL_CC_GENERIC_T16,
#define CC_TYPE_DECL_5_CC_GENERIC_T16 CC_TYPE_DECL_CC_GENERIC_T16,
#define CC_TYPE_DECL_6_CC_GENERIC_T16 CC_TYPE_DECL_CC_GENERIC_T16,
#define CC_TYPE_DECL_7_CC_GENERIC_T16 CC_TYPE_DECL_CC_GENERIC_T16,
#define CC_TYPE_DECL_8_CC_GENERIC_T16 CC_TYPE_DECL_CC_GENERIC_T16,
#define CC_TYPE_DECL_9_CC_GENERIC_T16 CC_TYPE_DECL_CC_GENERIC_T16,
#define CC_TYPE_DECL_0_CC_GENERIC_T17 CC_TYPE_DECL_CC_GENERIC_T17,
#define CC_TYPE_DECL_1_CC_GENERIC_T17 CC_TYPE_DECL_CC_GENERIC_T17,
#define CC_TYPE_DECL_2_CC_GENERIC_T17 CC_TYPE_DECL_CC_GENERIC_T17,
#define CC_TYPE_DECL_3_CC_GENERIC_T17 CC_TYPE_DECL_CC_GENERIC_T17,
#define CC_TYPE_DECL_4_CC_GENERIC_T17 CC_TYPE_DECL_CC_GENERIC_T17,
#define CC_TYPE_DECL_5_CC_GENERIC_T17 CC_TYPE_DECL_CC_GENERIC_T17,
#define CC_TYPE_DECL_6_CC_GENERIC_T17 CC_TYPE_DECL_CC_GENERIC_T17,
#define CC_TYPE_DECL_7_CC_GENERIC_T17 CC_TYPE_DECL_CC_GENERIC_T17,
#define CC_TYPE_DECL_8_CC_GENERIC_T17 CC_TYPE_DECL_CC_GENERIC_T17,
#define CC_TYPE_DECL_9_CC_GENERIC_T17 CC_TYPE_DECL_CC_GENERIC_T17,
#define CC_TYPE_DECL_0_CC_GENERIC_T18 CC_TYPE_DECL_CC_GENERIC_T18,
#define CC_TYPE_DECL_1_CC_GENERIC_T18 CC_TYPE_DECL_CC_GENERIC_T18,
#define CC_TYPE_DECL_2_CC_GENERIC_T18 CC_TYPE_DECL_CC_GENERIC_T18,
#define CC_TYPE_DECL_3_CC_GENERIC_T18 CC_TYPE_DECL_CC_GENERIC_T18,
#define CC_TYPE_DECL_4_CC_GENERIC_T18 CC_TYPE_DECL_CC_GENERIC_T18,
#define CC_TYPE_DECL_5_CC_GENERIC_T18 CC_TYPE_DECL_CC_GENERIC_T18,
#define CC_TYPE_DECL_6_CC_GENERIC_T18 CC_TYPE_DECL_CC_GENERIC_T18,
#define CC_TYPE_DECL_7_CC_GENERIC_T18 CC_TYPE_DECL_CC_GENERIC_T18,
#define CC_TYPE_DECL_8_CC_GENERIC_T18 CC_TYPE_DECL_CC_GENERIC_T18,
#define CC_TYPE_DECL_9_CC_GENERIC_T18 CC_TYPE_DECL_CC_GENERIC_T18,
#define CC_TYPE_DECL_0_CC_GENERIC_T19 CC_TYPE_DECL_CC_GENERIC_T19,
#define CC_TYPE_DECL_1_CC_GENERIC_T19 CC_TYPE_DECL_CC_GENERIC_T19,
#define CC_TYPE_DECL_2_CC_GENERIC_T19 CC_TYPE_DECL_CC_GENERIC_T19,
#define CC_TYPE_DECL_3_CC_GENERIC_T19 CC_TYPE_DECL_CC_GENERIC_T19,
#define CC_TYPE_DECL_4_CC_GENERIC_T19 CC_TYPE_DECL_CC_GENERIC_T19,
#define CC_TYPE_DECL_5_CC_GENERIC_T19 CC_TYPE_DECL_CC_GENERIC_T19,
#define CC_TYPE_DECL_6_CC_GENERIC_T19 CC_TYPE_DECL_CC_GENERIC_T19,
#define CC_TYPE_DECL_7_CC_GENERIC_T19 CC_TYPE_DECL_CC_GENERIC_T19,
#define CC_TYPE_DECL_8_CC_GENERIC_T19 CC_TYPE_DECL_CC_GENERIC_T19,
#define CC_TYPE_DECL_9_CC_GENERIC_T19 CC_TYPE_DECL_CC_GENERIC_T19,

#define CC_GENERIC_T(n) CC_GENERIC_T_(CC_GENERIC_TYPE, n)
#define CC_GENERIC_T_(t, n) CC_GENERIC_T__(t, n)
#define CC_GENERIC_T__(t, n) t##_T##n


#ifndef CC_GENERIC_T_0
typedef T CC_GENERIC_T(0);
#undef T
#define T CC_GENERIC_T0

#define CC_GENERIC_T_0 CC_GENERIC_T(0)
#else

#ifndef CC_GENERIC_T_1
typedef T CC_GENERIC_T(1);
#undef T
#define T CC_GENERIC_T1

#undef CC_GENERIC_T_0
#define CC_GENERIC_T_0 CC_GENERIC_T(0) CC_GENERIC_T_1
#define CC_GENERIC_T_1 , CC_GENERIC_T(1)
#else

#ifndef CC_GENERIC_T_2
typedef T CC_GENERIC_T(2);
#undef T
#define T CC_GENERIC_T(2)

#undef CC_GENERIC_T_1
#define CC_GENERIC_T_1 , CC_GENERIC_T(1) CC_GENERIC_T_2
#define CC_GENERIC_T_2 , CC_GENERIC_T(2)
#else

#ifndef CC_GENERIC_T_3
typedef T CC_GENERIC_T(3);
#undef T
#define T CC_GENERIC_T(3)

#undef CC_GENERIC_T_2
#define CC_GENERIC_T_2 , CC_GENERIC_T(2) CC_GENERIC_T_3
#define CC_GENERIC_T_3 , CC_GENERIC_T(3)
#else

#ifndef CC_GENERIC_T_4
typedef T CC_GENERIC_T(4);
#undef T
#define T CC_GENERIC_T(4)

#undef CC_GENERIC_T_3
#define CC_GENERIC_T_3 , CC_GENERIC_T(3) CC_GENERIC_T_4
#define CC_GENERIC_T_4 , CC_GENERIC_T(4)
#else

#ifndef CC_GENERIC_T_5
typedef T CC_GENERIC_T(5);
#undef T
#define T CC_GENERIC_T(5)

#undef CC_GENERIC_T_4
#define CC_GENERIC_T_4 , CC_GENERIC_T(4) CC_GENERIC_T_5
#define CC_GENERIC_T_5 , CC_GENERIC_T(5)
#else

#ifndef CC_GENERIC_T_6
typedef T CC_GENERIC_T(6);
#undef T
#define T CC_GENERIC_T(6)

#undef CC_GENERIC_T_5
#define CC_GENERIC_T_5 , CC_GENERIC_T(5) CC_GENERIC_T_6
#define CC_GENERIC_T_6 , CC_GENERIC_T(6)
#else

#ifndef CC_GENERIC_T_7
typedef T CC_GENERIC_T(7);
#undef T
#define T CC_GENERIC_T(7)

#undef CC_GENERIC_T_6
#define CC_GENERIC_T_6 , CC_GENERIC_T(6) CC_GENERIC_T_7
#define CC_GENERIC_T_7 , CC_GENERIC_T(7)
#else

#ifndef CC_GENERIC_T_8
typedef T CC_GENERIC_T(8);
#undef T
#define T CC_GENERIC_T(8)

#undef CC_GENERIC_T_7
#define CC_GENERIC_T_7 , CC_GENERIC_T(7) CC_GENERIC_T_8
#define CC_GENERIC_T_8 , CC_GENERIC_T(8)
#else

#ifndef CC_GENERIC_T_9
typedef T CC_GENERIC_T(9);
#undef T
#define T CC_GENERIC_T(9)

#undef CC_GENERIC_T_8
#define CC_GENERIC_T_8 , CC_GENERIC_T(8) CC_GENERIC_T_9
#define CC_GENERIC_T_9 , CC_GENERIC_T(9)
#else

#ifndef CC_GENERIC_T_10
typedef T CC_GENERIC_T(10);
#undef T
#define T CC_GENERIC_T(10)

#undef CC_GENERIC_T_9
#define CC_GENERIC_T_9 , CC_GENERIC_T(9) CC_GENERIC_T_10
#define CC_GENERIC_T_10 , CC_GENERIC_T(10)
#else

#ifndef CC_GENERIC_T_11
typedef T CC_GENERIC_T(11);
#undef T
#define T CC_GENERIC_T(11)

#undef CC_GENERIC_T_10
#define CC_GENERIC_T_10 , CC_GENERIC_T(10) CC_GENERIC_T_11
#define CC_GENERIC_T_11 , CC_GENERIC_T(11)
#else

#ifndef CC_GENERIC_T_12
typedef T CC_GENERIC_T(12);
#undef T
#define T CC_GENERIC_T(12)

#undef CC_GENERIC_T_11
#define CC_GENERIC_T_11 , CC_GENERIC_T(11) CC_GENERIC_T_12
#define CC_GENERIC_T_12 , CC_GENERIC_T(12)
#else

#ifndef CC_GENERIC_T_13
typedef T CC_GENERIC_T(13);
#undef T
#define T CC_GENERIC_T(13)

#undef CC_GENERIC_T_12
#define CC_GENERIC_T_12 , CC_GENERIC_T(12) CC_GENERIC_T_13
#define CC_GENERIC_T_13 , CC_GENERIC_T(13)
#else

#ifndef CC_GENERIC_T_14
typedef T CC_GENERIC_T(14);
#undef T
#define T CC_GENERIC_T(14)

#undef CC_GENERIC_T_13
#define CC_GENERIC_T_13 , CC_GENERIC_T(13) CC_GENERIC_T_14
#define CC_GENERIC_T_14 , CC_GENERIC_T(14)
#else

#ifndef CC_GENERIC_T_15
typedef T CC_GENERIC_T(15);
#undef T
#define T CC_GENERIC_T(15)

#undef CC_GENERIC_T_14
#define CC_GENERIC_T_14 , CC_GENERIC_T(14) CC_GENERIC_T_15
#define CC_GENERIC_T_15 , CC_GENERIC_T(15)
#else

#ifndef CC_GENERIC_T_16
typedef T CC_GENERIC_T(16);
#undef T
#define T CC_GENERIC_T(16)

#undef CC_GENERIC_T_15
#define CC_GENERIC_T_15 , CC_GENERIC_T(15) CC_GENERIC_T_16
#define CC_GENERIC_T_16 , CC_GENERIC_T(16)
#else

#ifndef CC_GENERIC_T_17
typedef T CC_GENERIC_T(17);
#undef T
#define T CC_GENERIC_T(17)

#undef CC_GENERIC_T_16
#define CC_GENERIC_T_16 , CC_GENERIC_T(16) CC_GENERIC_T_17
#define CC_GENERIC_T_17 , CC_GENERIC_T(17)
#else

#ifndef CC_GENERIC_T_18
typedef T CC_GENERIC_T(18);
#undef T
#define T CC_GENERIC_T(18)

#undef CC_GENERIC_T_17
#define CC_GENERIC_T_17 , CC_GENERIC_T(17) CC_GENERIC_T_18
#define CC_GENERIC_T_18 , CC_GENERIC_T(18)
#else

#ifndef CC_GENERIC_T_19
typedef T CC_GENERIC_T(19);
#undef T
#define T CC_GENERIC_T(19)

#undef CC_GENERIC_T_18
#define CC_GENERIC_T_18 , CC_GENERIC_T(18) CC_GENERIC_T_19
#define CC_GENERIC_T_19 , CC_GENERIC_T(19)
#else
#error Add additional cases
#endif

#endif

#endif

#endif

#endif

#endif

#endif

#endif

#endif

#endif

#endif

#endif

#endif

#endif

#endif

#endif

#endif

#endif

#endif

#endif

#include CC_GENERIC_TEMPLATE
