/*
 *  Copyright (c) 2020, Stefan Johnson
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without modification,
 *  are permitted provided that the following conditions are met:
 *
 *  1. Redistributions of source code must retain the above copyright notice, this list
 *     of conditions and the following disclaimer.
 *  2. Redistributions in binary form must reproduce the above copyright notice, this
 *     list of conditions and the following disclaimer in the documentation and/or other
 *     materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#include <CommonC/Template.h>

#define CC_TYPE_CC_GENERIC_T0(...) CC_GENERIC_T(0)
#define CC_TYPE_CC_GENERIC_T1(...) CC_GENERIC_T(1)
#define CC_TYPE_CC_GENERIC_T2(...) CC_GENERIC_T(2)
#define CC_TYPE_CC_GENERIC_T3(...) CC_GENERIC_T(3)
#define CC_TYPE_CC_GENERIC_T4(...) CC_GENERIC_T(4)
#define CC_TYPE_CC_GENERIC_T5(...) CC_GENERIC_T(5)
#define CC_TYPE_CC_GENERIC_T6(...) CC_GENERIC_T(6)
#define CC_TYPE_CC_GENERIC_T7(...) CC_GENERIC_T(7)
#define CC_TYPE_CC_GENERIC_T8(...) CC_GENERIC_T(8)
#define CC_TYPE_CC_GENERIC_T9(...) CC_GENERIC_T(9)
#define CC_TYPE_CC_GENERIC_T10(...) CC_GENERIC_T(10)
#define CC_TYPE_CC_GENERIC_T11(...) CC_GENERIC_T(11)
#define CC_TYPE_CC_GENERIC_T12(...) CC_GENERIC_T(12)
#define CC_TYPE_CC_GENERIC_T13(...) CC_GENERIC_T(13)
#define CC_TYPE_CC_GENERIC_T14(...) CC_GENERIC_T(14)
#define CC_TYPE_CC_GENERIC_T15(...) CC_GENERIC_T(15)
#define CC_TYPE_CC_GENERIC_T16(...) CC_GENERIC_T(16)
#define CC_TYPE_CC_GENERIC_T17(...) CC_GENERIC_T(17)
#define CC_TYPE_CC_GENERIC_T18(...) CC_GENERIC_T(18)
#define CC_TYPE_CC_GENERIC_T19(...) CC_GENERIC_T(19)
#define CC_TYPE_0_CC_GENERIC_T0 CC_TYPE_CC_GENERIC_T0,
#define CC_TYPE_1_CC_GENERIC_T0 CC_TYPE_CC_GENERIC_T0,
#define CC_TYPE_2_CC_GENERIC_T0 CC_TYPE_CC_GENERIC_T0,
#define CC_TYPE_3_CC_GENERIC_T0 CC_TYPE_CC_GENERIC_T0,
#define CC_TYPE_4_CC_GENERIC_T0 CC_TYPE_CC_GENERIC_T0,
#define CC_TYPE_5_CC_GENERIC_T0 CC_TYPE_CC_GENERIC_T0,
#define CC_TYPE_6_CC_GENERIC_T0 CC_TYPE_CC_GENERIC_T0,
#define CC_TYPE_7_CC_GENERIC_T0 CC_TYPE_CC_GENERIC_T0,
#define CC_TYPE_8_CC_GENERIC_T0 CC_TYPE_CC_GENERIC_T0,
#define CC_TYPE_9_CC_GENERIC_T0 CC_TYPE_CC_GENERIC_T0,
#define CC_TYPE_0_CC_GENERIC_T1 CC_TYPE_CC_GENERIC_T1,
#define CC_TYPE_1_CC_GENERIC_T1 CC_TYPE_CC_GENERIC_T1,
#define CC_TYPE_2_CC_GENERIC_T1 CC_TYPE_CC_GENERIC_T1,
#define CC_TYPE_3_CC_GENERIC_T1 CC_TYPE_CC_GENERIC_T1,
#define CC_TYPE_4_CC_GENERIC_T1 CC_TYPE_CC_GENERIC_T1,
#define CC_TYPE_5_CC_GENERIC_T1 CC_TYPE_CC_GENERIC_T1,
#define CC_TYPE_6_CC_GENERIC_T1 CC_TYPE_CC_GENERIC_T1,
#define CC_TYPE_7_CC_GENERIC_T1 CC_TYPE_CC_GENERIC_T1,
#define CC_TYPE_8_CC_GENERIC_T1 CC_TYPE_CC_GENERIC_T1,
#define CC_TYPE_9_CC_GENERIC_T1 CC_TYPE_CC_GENERIC_T1,
#define CC_TYPE_0_CC_GENERIC_T2 CC_TYPE_CC_GENERIC_T2,
#define CC_TYPE_1_CC_GENERIC_T2 CC_TYPE_CC_GENERIC_T2,
#define CC_TYPE_2_CC_GENERIC_T2 CC_TYPE_CC_GENERIC_T2,
#define CC_TYPE_3_CC_GENERIC_T2 CC_TYPE_CC_GENERIC_T2,
#define CC_TYPE_4_CC_GENERIC_T2 CC_TYPE_CC_GENERIC_T2,
#define CC_TYPE_5_CC_GENERIC_T2 CC_TYPE_CC_GENERIC_T2,
#define CC_TYPE_6_CC_GENERIC_T2 CC_TYPE_CC_GENERIC_T2,
#define CC_TYPE_7_CC_GENERIC_T2 CC_TYPE_CC_GENERIC_T2,
#define CC_TYPE_8_CC_GENERIC_T2 CC_TYPE_CC_GENERIC_T2,
#define CC_TYPE_9_CC_GENERIC_T2 CC_TYPE_CC_GENERIC_T2,
#define CC_TYPE_0_CC_GENERIC_T3 CC_TYPE_CC_GENERIC_T3,
#define CC_TYPE_1_CC_GENERIC_T3 CC_TYPE_CC_GENERIC_T3,
#define CC_TYPE_2_CC_GENERIC_T3 CC_TYPE_CC_GENERIC_T3,
#define CC_TYPE_3_CC_GENERIC_T3 CC_TYPE_CC_GENERIC_T3,
#define CC_TYPE_4_CC_GENERIC_T3 CC_TYPE_CC_GENERIC_T3,
#define CC_TYPE_5_CC_GENERIC_T3 CC_TYPE_CC_GENERIC_T3,
#define CC_TYPE_6_CC_GENERIC_T3 CC_TYPE_CC_GENERIC_T3,
#define CC_TYPE_7_CC_GENERIC_T3 CC_TYPE_CC_GENERIC_T3,
#define CC_TYPE_8_CC_GENERIC_T3 CC_TYPE_CC_GENERIC_T3,
#define CC_TYPE_9_CC_GENERIC_T3 CC_TYPE_CC_GENERIC_T3,
#define CC_TYPE_0_CC_GENERIC_T4 CC_TYPE_CC_GENERIC_T4,
#define CC_TYPE_1_CC_GENERIC_T4 CC_TYPE_CC_GENERIC_T4,
#define CC_TYPE_2_CC_GENERIC_T4 CC_TYPE_CC_GENERIC_T4,
#define CC_TYPE_3_CC_GENERIC_T4 CC_TYPE_CC_GENERIC_T4,
#define CC_TYPE_4_CC_GENERIC_T4 CC_TYPE_CC_GENERIC_T4,
#define CC_TYPE_5_CC_GENERIC_T4 CC_TYPE_CC_GENERIC_T4,
#define CC_TYPE_6_CC_GENERIC_T4 CC_TYPE_CC_GENERIC_T4,
#define CC_TYPE_7_CC_GENERIC_T4 CC_TYPE_CC_GENERIC_T4,
#define CC_TYPE_8_CC_GENERIC_T4 CC_TYPE_CC_GENERIC_T4,
#define CC_TYPE_9_CC_GENERIC_T4 CC_TYPE_CC_GENERIC_T4,
#define CC_TYPE_0_CC_GENERIC_T5 CC_TYPE_CC_GENERIC_T5,
#define CC_TYPE_1_CC_GENERIC_T5 CC_TYPE_CC_GENERIC_T5,
#define CC_TYPE_2_CC_GENERIC_T5 CC_TYPE_CC_GENERIC_T5,
#define CC_TYPE_3_CC_GENERIC_T5 CC_TYPE_CC_GENERIC_T5,
#define CC_TYPE_4_CC_GENERIC_T5 CC_TYPE_CC_GENERIC_T5,
#define CC_TYPE_5_CC_GENERIC_T5 CC_TYPE_CC_GENERIC_T5,
#define CC_TYPE_6_CC_GENERIC_T5 CC_TYPE_CC_GENERIC_T5,
#define CC_TYPE_7_CC_GENERIC_T5 CC_TYPE_CC_GENERIC_T5,
#define CC_TYPE_8_CC_GENERIC_T5 CC_TYPE_CC_GENERIC_T5,
#define CC_TYPE_9_CC_GENERIC_T5 CC_TYPE_CC_GENERIC_T5,
#define CC_TYPE_0_CC_GENERIC_T6 CC_TYPE_CC_GENERIC_T6,
#define CC_TYPE_1_CC_GENERIC_T6 CC_TYPE_CC_GENERIC_T6,
#define CC_TYPE_2_CC_GENERIC_T6 CC_TYPE_CC_GENERIC_T6,
#define CC_TYPE_3_CC_GENERIC_T6 CC_TYPE_CC_GENERIC_T6,
#define CC_TYPE_4_CC_GENERIC_T6 CC_TYPE_CC_GENERIC_T6,
#define CC_TYPE_5_CC_GENERIC_T6 CC_TYPE_CC_GENERIC_T6,
#define CC_TYPE_6_CC_GENERIC_T6 CC_TYPE_CC_GENERIC_T6,
#define CC_TYPE_7_CC_GENERIC_T6 CC_TYPE_CC_GENERIC_T6,
#define CC_TYPE_8_CC_GENERIC_T6 CC_TYPE_CC_GENERIC_T6,
#define CC_TYPE_9_CC_GENERIC_T6 CC_TYPE_CC_GENERIC_T6,
#define CC_TYPE_0_CC_GENERIC_T7 CC_TYPE_CC_GENERIC_T7,
#define CC_TYPE_1_CC_GENERIC_T7 CC_TYPE_CC_GENERIC_T7,
#define CC_TYPE_2_CC_GENERIC_T7 CC_TYPE_CC_GENERIC_T7,
#define CC_TYPE_3_CC_GENERIC_T7 CC_TYPE_CC_GENERIC_T7,
#define CC_TYPE_4_CC_GENERIC_T7 CC_TYPE_CC_GENERIC_T7,
#define CC_TYPE_5_CC_GENERIC_T7 CC_TYPE_CC_GENERIC_T7,
#define CC_TYPE_6_CC_GENERIC_T7 CC_TYPE_CC_GENERIC_T7,
#define CC_TYPE_7_CC_GENERIC_T7 CC_TYPE_CC_GENERIC_T7,
#define CC_TYPE_8_CC_GENERIC_T7 CC_TYPE_CC_GENERIC_T7,
#define CC_TYPE_9_CC_GENERIC_T7 CC_TYPE_CC_GENERIC_T7,
#define CC_TYPE_0_CC_GENERIC_T8 CC_TYPE_CC_GENERIC_T8,
#define CC_TYPE_1_CC_GENERIC_T8 CC_TYPE_CC_GENERIC_T8,
#define CC_TYPE_2_CC_GENERIC_T8 CC_TYPE_CC_GENERIC_T8,
#define CC_TYPE_3_CC_GENERIC_T8 CC_TYPE_CC_GENERIC_T8,
#define CC_TYPE_4_CC_GENERIC_T8 CC_TYPE_CC_GENERIC_T8,
#define CC_TYPE_5_CC_GENERIC_T8 CC_TYPE_CC_GENERIC_T8,
#define CC_TYPE_6_CC_GENERIC_T8 CC_TYPE_CC_GENERIC_T8,
#define CC_TYPE_7_CC_GENERIC_T8 CC_TYPE_CC_GENERIC_T8,
#define CC_TYPE_8_CC_GENERIC_T8 CC_TYPE_CC_GENERIC_T8,
#define CC_TYPE_9_CC_GENERIC_T8 CC_TYPE_CC_GENERIC_T8,
#define CC_TYPE_0_CC_GENERIC_T9 CC_TYPE_CC_GENERIC_T9,
#define CC_TYPE_1_CC_GENERIC_T9 CC_TYPE_CC_GENERIC_T9,
#define CC_TYPE_2_CC_GENERIC_T9 CC_TYPE_CC_GENERIC_T9,
#define CC_TYPE_3_CC_GENERIC_T9 CC_TYPE_CC_GENERIC_T9,
#define CC_TYPE_4_CC_GENERIC_T9 CC_TYPE_CC_GENERIC_T9,
#define CC_TYPE_5_CC_GENERIC_T9 CC_TYPE_CC_GENERIC_T9,
#define CC_TYPE_6_CC_GENERIC_T9 CC_TYPE_CC_GENERIC_T9,
#define CC_TYPE_7_CC_GENERIC_T9 CC_TYPE_CC_GENERIC_T9,
#define CC_TYPE_8_CC_GENERIC_T9 CC_TYPE_CC_GENERIC_T9,
#define CC_TYPE_9_CC_GENERIC_T9 CC_TYPE_CC_GENERIC_T9,
#define CC_TYPE_0_CC_GENERIC_T10 CC_TYPE_CC_GENERIC_T10,
#define CC_TYPE_1_CC_GENERIC_T10 CC_TYPE_CC_GENERIC_T10,
#define CC_TYPE_2_CC_GENERIC_T10 CC_TYPE_CC_GENERIC_T10,
#define CC_TYPE_3_CC_GENERIC_T10 CC_TYPE_CC_GENERIC_T10,
#define CC_TYPE_4_CC_GENERIC_T10 CC_TYPE_CC_GENERIC_T10,
#define CC_TYPE_5_CC_GENERIC_T10 CC_TYPE_CC_GENERIC_T10,
#define CC_TYPE_6_CC_GENERIC_T10 CC_TYPE_CC_GENERIC_T10,
#define CC_TYPE_7_CC_GENERIC_T10 CC_TYPE_CC_GENERIC_T10,
#define CC_TYPE_8_CC_GENERIC_T10 CC_TYPE_CC_GENERIC_T10,
#define CC_TYPE_9_CC_GENERIC_T10 CC_TYPE_CC_GENERIC_T10,
#define CC_TYPE_0_CC_GENERIC_T11 CC_TYPE_CC_GENERIC_T11,
#define CC_TYPE_1_CC_GENERIC_T11 CC_TYPE_CC_GENERIC_T11,
#define CC_TYPE_2_CC_GENERIC_T11 CC_TYPE_CC_GENERIC_T11,
#define CC_TYPE_3_CC_GENERIC_T11 CC_TYPE_CC_GENERIC_T11,
#define CC_TYPE_4_CC_GENERIC_T11 CC_TYPE_CC_GENERIC_T11,
#define CC_TYPE_5_CC_GENERIC_T11 CC_TYPE_CC_GENERIC_T11,
#define CC_TYPE_6_CC_GENERIC_T11 CC_TYPE_CC_GENERIC_T11,
#define CC_TYPE_7_CC_GENERIC_T11 CC_TYPE_CC_GENERIC_T11,
#define CC_TYPE_8_CC_GENERIC_T11 CC_TYPE_CC_GENERIC_T11,
#define CC_TYPE_9_CC_GENERIC_T11 CC_TYPE_CC_GENERIC_T11,
#define CC_TYPE_0_CC_GENERIC_T12 CC_TYPE_CC_GENERIC_T12,
#define CC_TYPE_1_CC_GENERIC_T12 CC_TYPE_CC_GENERIC_T12,
#define CC_TYPE_2_CC_GENERIC_T12 CC_TYPE_CC_GENERIC_T12,
#define CC_TYPE_3_CC_GENERIC_T12 CC_TYPE_CC_GENERIC_T12,
#define CC_TYPE_4_CC_GENERIC_T12 CC_TYPE_CC_GENERIC_T12,
#define CC_TYPE_5_CC_GENERIC_T12 CC_TYPE_CC_GENERIC_T12,
#define CC_TYPE_6_CC_GENERIC_T12 CC_TYPE_CC_GENERIC_T12,
#define CC_TYPE_7_CC_GENERIC_T12 CC_TYPE_CC_GENERIC_T12,
#define CC_TYPE_8_CC_GENERIC_T12 CC_TYPE_CC_GENERIC_T12,
#define CC_TYPE_9_CC_GENERIC_T12 CC_TYPE_CC_GENERIC_T12,
#define CC_TYPE_0_CC_GENERIC_T13 CC_TYPE_CC_GENERIC_T13,
#define CC_TYPE_1_CC_GENERIC_T13 CC_TYPE_CC_GENERIC_T13,
#define CC_TYPE_2_CC_GENERIC_T13 CC_TYPE_CC_GENERIC_T13,
#define CC_TYPE_3_CC_GENERIC_T13 CC_TYPE_CC_GENERIC_T13,
#define CC_TYPE_4_CC_GENERIC_T13 CC_TYPE_CC_GENERIC_T13,
#define CC_TYPE_5_CC_GENERIC_T13 CC_TYPE_CC_GENERIC_T13,
#define CC_TYPE_6_CC_GENERIC_T13 CC_TYPE_CC_GENERIC_T13,
#define CC_TYPE_7_CC_GENERIC_T13 CC_TYPE_CC_GENERIC_T13,
#define CC_TYPE_8_CC_GENERIC_T13 CC_TYPE_CC_GENERIC_T13,
#define CC_TYPE_9_CC_GENERIC_T13 CC_TYPE_CC_GENERIC_T13,
#define CC_TYPE_0_CC_GENERIC_T14 CC_TYPE_CC_GENERIC_T14,
#define CC_TYPE_1_CC_GENERIC_T14 CC_TYPE_CC_GENERIC_T14,
#define CC_TYPE_2_CC_GENERIC_T14 CC_TYPE_CC_GENERIC_T14,
#define CC_TYPE_3_CC_GENERIC_T14 CC_TYPE_CC_GENERIC_T14,
#define CC_TYPE_4_CC_GENERIC_T14 CC_TYPE_CC_GENERIC_T14,
#define CC_TYPE_5_CC_GENERIC_T14 CC_TYPE_CC_GENERIC_T14,
#define CC_TYPE_6_CC_GENERIC_T14 CC_TYPE_CC_GENERIC_T14,
#define CC_TYPE_7_CC_GENERIC_T14 CC_TYPE_CC_GENERIC_T14,
#define CC_TYPE_8_CC_GENERIC_T14 CC_TYPE_CC_GENERIC_T14,
#define CC_TYPE_9_CC_GENERIC_T14 CC_TYPE_CC_GENERIC_T14,
#define CC_TYPE_0_CC_GENERIC_T15 CC_TYPE_CC_GENERIC_T15,
#define CC_TYPE_1_CC_GENERIC_T15 CC_TYPE_CC_GENERIC_T15,
#define CC_TYPE_2_CC_GENERIC_T15 CC_TYPE_CC_GENERIC_T15,
#define CC_TYPE_3_CC_GENERIC_T15 CC_TYPE_CC_GENERIC_T15,
#define CC_TYPE_4_CC_GENERIC_T15 CC_TYPE_CC_GENERIC_T15,
#define CC_TYPE_5_CC_GENERIC_T15 CC_TYPE_CC_GENERIC_T15,
#define CC_TYPE_6_CC_GENERIC_T15 CC_TYPE_CC_GENERIC_T15,
#define CC_TYPE_7_CC_GENERIC_T15 CC_TYPE_CC_GENERIC_T15,
#define CC_TYPE_8_CC_GENERIC_T15 CC_TYPE_CC_GENERIC_T15,
#define CC_TYPE_9_CC_GENERIC_T15 CC_TYPE_CC_GENERIC_T15,
#define CC_TYPE_0_CC_GENERIC_T16 CC_TYPE_CC_GENERIC_T16,
#define CC_TYPE_1_CC_GENERIC_T16 CC_TYPE_CC_GENERIC_T16,
#define CC_TYPE_2_CC_GENERIC_T16 CC_TYPE_CC_GENERIC_T16,
#define CC_TYPE_3_CC_GENERIC_T16 CC_TYPE_CC_GENERIC_T16,
#define CC_TYPE_4_CC_GENERIC_T16 CC_TYPE_CC_GENERIC_T16,
#define CC_TYPE_5_CC_GENERIC_T16 CC_TYPE_CC_GENERIC_T16,
#define CC_TYPE_6_CC_GENERIC_T16 CC_TYPE_CC_GENERIC_T16,
#define CC_TYPE_7_CC_GENERIC_T16 CC_TYPE_CC_GENERIC_T16,
#define CC_TYPE_8_CC_GENERIC_T16 CC_TYPE_CC_GENERIC_T16,
#define CC_TYPE_9_CC_GENERIC_T16 CC_TYPE_CC_GENERIC_T16,
#define CC_TYPE_0_CC_GENERIC_T17 CC_TYPE_CC_GENERIC_T17,
#define CC_TYPE_1_CC_GENERIC_T17 CC_TYPE_CC_GENERIC_T17,
#define CC_TYPE_2_CC_GENERIC_T17 CC_TYPE_CC_GENERIC_T17,
#define CC_TYPE_3_CC_GENERIC_T17 CC_TYPE_CC_GENERIC_T17,
#define CC_TYPE_4_CC_GENERIC_T17 CC_TYPE_CC_GENERIC_T17,
#define CC_TYPE_5_CC_GENERIC_T17 CC_TYPE_CC_GENERIC_T17,
#define CC_TYPE_6_CC_GENERIC_T17 CC_TYPE_CC_GENERIC_T17,
#define CC_TYPE_7_CC_GENERIC_T17 CC_TYPE_CC_GENERIC_T17,
#define CC_TYPE_8_CC_GENERIC_T17 CC_TYPE_CC_GENERIC_T17,
#define CC_TYPE_9_CC_GENERIC_T17 CC_TYPE_CC_GENERIC_T17,
#define CC_TYPE_0_CC_GENERIC_T18 CC_TYPE_CC_GENERIC_T18,
#define CC_TYPE_1_CC_GENERIC_T18 CC_TYPE_CC_GENERIC_T18,
#define CC_TYPE_2_CC_GENERIC_T18 CC_TYPE_CC_GENERIC_T18,
#define CC_TYPE_3_CC_GENERIC_T18 CC_TYPE_CC_GENERIC_T18,
#define CC_TYPE_4_CC_GENERIC_T18 CC_TYPE_CC_GENERIC_T18,
#define CC_TYPE_5_CC_GENERIC_T18 CC_TYPE_CC_GENERIC_T18,
#define CC_TYPE_6_CC_GENERIC_T18 CC_TYPE_CC_GENERIC_T18,
#define CC_TYPE_7_CC_GENERIC_T18 CC_TYPE_CC_GENERIC_T18,
#define CC_TYPE_8_CC_GENERIC_T18 CC_TYPE_CC_GENERIC_T18,
#define CC_TYPE_9_CC_GENERIC_T18 CC_TYPE_CC_GENERIC_T18,
#define CC_TYPE_0_CC_GENERIC_T19 CC_TYPE_CC_GENERIC_T19,
#define CC_TYPE_1_CC_GENERIC_T19 CC_TYPE_CC_GENERIC_T19,
#define CC_TYPE_2_CC_GENERIC_T19 CC_TYPE_CC_GENERIC_T19,
#define CC_TYPE_3_CC_GENERIC_T19 CC_TYPE_CC_GENERIC_T19,
#define CC_TYPE_4_CC_GENERIC_T19 CC_TYPE_CC_GENERIC_T19,
#define CC_TYPE_5_CC_GENERIC_T19 CC_TYPE_CC_GENERIC_T19,
#define CC_TYPE_6_CC_GENERIC_T19 CC_TYPE_CC_GENERIC_T19,
#define CC_TYPE_7_CC_GENERIC_T19 CC_TYPE_CC_GENERIC_T19,
#define CC_TYPE_8_CC_GENERIC_T19 CC_TYPE_CC_GENERIC_T19,
#define CC_TYPE_9_CC_GENERIC_T19 CC_TYPE_CC_GENERIC_T19,

#define CC_PRESERVE_CC_TYPE_CC_GENERIC_T0 CC_TYPE_CC_GENERIC_T0
#define CC_PRESERVE_CC_TYPE_CC_GENERIC_T1 CC_TYPE_CC_GENERIC_T1
#define CC_PRESERVE_CC_TYPE_CC_GENERIC_T2 CC_TYPE_CC_GENERIC_T2
#define CC_PRESERVE_CC_TYPE_CC_GENERIC_T3 CC_TYPE_CC_GENERIC_T3
#define CC_PRESERVE_CC_TYPE_CC_GENERIC_T4 CC_TYPE_CC_GENERIC_T4
#define CC_PRESERVE_CC_TYPE_CC_GENERIC_T5 CC_TYPE_CC_GENERIC_T5
#define CC_PRESERVE_CC_TYPE_CC_GENERIC_T6 CC_TYPE_CC_GENERIC_T6
#define CC_PRESERVE_CC_TYPE_CC_GENERIC_T7 CC_TYPE_CC_GENERIC_T7
#define CC_PRESERVE_CC_TYPE_CC_GENERIC_T8 CC_TYPE_CC_GENERIC_T8
#define CC_PRESERVE_CC_TYPE_CC_GENERIC_T9 CC_TYPE_CC_GENERIC_T9
#define CC_PRESERVE_CC_TYPE_CC_GENERIC_T10 CC_TYPE_CC_GENERIC_T10
#define CC_PRESERVE_CC_TYPE_CC_GENERIC_T11 CC_TYPE_CC_GENERIC_T11
#define CC_PRESERVE_CC_TYPE_CC_GENERIC_T12 CC_TYPE_CC_GENERIC_T12
#define CC_PRESERVE_CC_TYPE_CC_GENERIC_T13 CC_TYPE_CC_GENERIC_T13
#define CC_PRESERVE_CC_TYPE_CC_GENERIC_T14 CC_TYPE_CC_GENERIC_T14
#define CC_PRESERVE_CC_TYPE_CC_GENERIC_T15 CC_TYPE_CC_GENERIC_T15
#define CC_PRESERVE_CC_TYPE_CC_GENERIC_T16 CC_TYPE_CC_GENERIC_T16
#define CC_PRESERVE_CC_TYPE_CC_GENERIC_T17 CC_TYPE_CC_GENERIC_T17
#define CC_PRESERVE_CC_TYPE_CC_GENERIC_T18 CC_TYPE_CC_GENERIC_T18
#define CC_PRESERVE_CC_TYPE_CC_GENERIC_T19 CC_TYPE_CC_GENERIC_T19

#define CC_TYPE_DECL_CC_GENERIC_T0(...) CC_GENERIC_T(0), __VA_ARGS__
#define CC_TYPE_DECL_CC_GENERIC_T1(...) CC_GENERIC_T(1), __VA_ARGS__
#define CC_TYPE_DECL_CC_GENERIC_T2(...) CC_GENERIC_T(2), __VA_ARGS__
#define CC_TYPE_DECL_CC_GENERIC_T3(...) CC_GENERIC_T(3), __VA_ARGS__
#define CC_TYPE_DECL_CC_GENERIC_T4(...) CC_GENERIC_T(4), __VA_ARGS__
#define CC_TYPE_DECL_CC_GENERIC_T5(...) CC_GENERIC_T(5), __VA_ARGS__
#define CC_TYPE_DECL_CC_GENERIC_T6(...) CC_GENERIC_T(6), __VA_ARGS__
#define CC_TYPE_DECL_CC_GENERIC_T7(...) CC_GENERIC_T(7), __VA_ARGS__
#define CC_TYPE_DECL_CC_GENERIC_T8(...) CC_GENERIC_T(8), __VA_ARGS__
#define CC_TYPE_DECL_CC_GENERIC_T9(...) CC_GENERIC_T(9), __VA_ARGS__
#define CC_TYPE_DECL_CC_GENERIC_T10(...) CC_GENERIC_T(10), __VA_ARGS__
#define CC_TYPE_DECL_CC_GENERIC_T11(...) CC_GENERIC_T(11), __VA_ARGS__
#define CC_TYPE_DECL_CC_GENERIC_T12(...) CC_GENERIC_T(12), __VA_ARGS__
#define CC_TYPE_DECL_CC_GENERIC_T13(...) CC_GENERIC_T(13), __VA_ARGS__
#define CC_TYPE_DECL_CC_GENERIC_T14(...) CC_GENERIC_T(14), __VA_ARGS__
#define CC_TYPE_DECL_CC_GENERIC_T15(...) CC_GENERIC_T(15), __VA_ARGS__
#define CC_TYPE_DECL_CC_GENERIC_T16(...) CC_GENERIC_T(16), __VA_ARGS__
#define CC_TYPE_DECL_CC_GENERIC_T17(...) CC_GENERIC_T(17), __VA_ARGS__
#define CC_TYPE_DECL_CC_GENERIC_T18(...) CC_GENERIC_T(18), __VA_ARGS__
#define CC_TYPE_DECL_CC_GENERIC_T19(...) CC_GENERIC_T(19), __VA_ARGS__
#define CC_TYPE_DECL_0_CC_GENERIC_T0 CC_TYPE_DECL_CC_GENERIC_T0,
#define CC_TYPE_DECL_1_CC_GENERIC_T0 CC_TYPE_DECL_CC_GENERIC_T0,
#define CC_TYPE_DECL_2_CC_GENERIC_T0 CC_TYPE_DECL_CC_GENERIC_T0,
#define CC_TYPE_DECL_3_CC_GENERIC_T0 CC_TYPE_DECL_CC_GENERIC_T0,
#define CC_TYPE_DECL_4_CC_GENERIC_T0 CC_TYPE_DECL_CC_GENERIC_T0,
#define CC_TYPE_DECL_5_CC_GENERIC_T0 CC_TYPE_DECL_CC_GENERIC_T0,
#define CC_TYPE_DECL_6_CC_GENERIC_T0 CC_TYPE_DECL_CC_GENERIC_T0,
#define CC_TYPE_DECL_7_CC_GENERIC_T0 CC_TYPE_DECL_CC_GENERIC_T0,
#define CC_TYPE_DECL_8_CC_GENERIC_T0 CC_TYPE_DECL_CC_GENERIC_T0,
#define CC_TYPE_DECL_9_CC_GENERIC_T0 CC_TYPE_DECL_CC_GENERIC_T0,
#define CC_TYPE_DECL_0_CC_GENERIC_T1 CC_TYPE_DECL_CC_GENERIC_T1,
#define CC_TYPE_DECL_1_CC_GENERIC_T1 CC_TYPE_DECL_CC_GENERIC_T1,
#define CC_TYPE_DECL_2_CC_GENERIC_T1 CC_TYPE_DECL_CC_GENERIC_T1,
#define CC_TYPE_DECL_3_CC_GENERIC_T1 CC_TYPE_DECL_CC_GENERIC_T1,
#define CC_TYPE_DECL_4_CC_GENERIC_T1 CC_TYPE_DECL_CC_GENERIC_T1,
#define CC_TYPE_DECL_5_CC_GENERIC_T1 CC_TYPE_DECL_CC_GENERIC_T1,
#define CC_TYPE_DECL_6_CC_GENERIC_T1 CC_TYPE_DECL_CC_GENERIC_T1,
#define CC_TYPE_DECL_7_CC_GENERIC_T1 CC_TYPE_DECL_CC_GENERIC_T1,
#define CC_TYPE_DECL_8_CC_GENERIC_T1 CC_TYPE_DECL_CC_GENERIC_T1,
#define CC_TYPE_DECL_9_CC_GENERIC_T1 CC_TYPE_DECL_CC_GENERIC_T1,
#define CC_TYPE_DECL_0_CC_GENERIC_T2 CC_TYPE_DECL_CC_GENERIC_T2,
#define CC_TYPE_DECL_1_CC_GENERIC_T2 CC_TYPE_DECL_CC_GENERIC_T2,
#define CC_TYPE_DECL_2_CC_GENERIC_T2 CC_TYPE_DECL_CC_GENERIC_T2,
#define CC_TYPE_DECL_3_CC_GENERIC_T2 CC_TYPE_DECL_CC_GENERIC_T2,
#define CC_TYPE_DECL_4_CC_GENERIC_T2 CC_TYPE_DECL_CC_GENERIC_T2,
#define CC_TYPE_DECL_5_CC_GENERIC_T2 CC_TYPE_DECL_CC_GENERIC_T2,
#define CC_TYPE_DECL_6_CC_GENERIC_T2 CC_TYPE_DECL_CC_GENERIC_T2,
#define CC_TYPE_DECL_7_CC_GENERIC_T2 CC_TYPE_DECL_CC_GENERIC_T2,
#define CC_TYPE_DECL_8_CC_GENERIC_T2 CC_TYPE_DECL_CC_GENERIC_T2,
#define CC_TYPE_DECL_9_CC_GENERIC_T2 CC_TYPE_DECL_CC_GENERIC_T2,
#define CC_TYPE_DECL_0_CC_GENERIC_T3 CC_TYPE_DECL_CC_GENERIC_T3,
#define CC_TYPE_DECL_1_CC_GENERIC_T3 CC_TYPE_DECL_CC_GENERIC_T3,
#define CC_TYPE_DECL_2_CC_GENERIC_T3 CC_TYPE_DECL_CC_GENERIC_T3,
#define CC_TYPE_DECL_3_CC_GENERIC_T3 CC_TYPE_DECL_CC_GENERIC_T3,
#define CC_TYPE_DECL_4_CC_GENERIC_T3 CC_TYPE_DECL_CC_GENERIC_T3,
#define CC_TYPE_DECL_5_CC_GENERIC_T3 CC_TYPE_DECL_CC_GENERIC_T3,
#define CC_TYPE_DECL_6_CC_GENERIC_T3 CC_TYPE_DECL_CC_GENERIC_T3,
#define CC_TYPE_DECL_7_CC_GENERIC_T3 CC_TYPE_DECL_CC_GENERIC_T3,
#define CC_TYPE_DECL_8_CC_GENERIC_T3 CC_TYPE_DECL_CC_GENERIC_T3,
#define CC_TYPE_DECL_9_CC_GENERIC_T3 CC_TYPE_DECL_CC_GENERIC_T3,
#define CC_TYPE_DECL_0_CC_GENERIC_T4 CC_TYPE_DECL_CC_GENERIC_T4,
#define CC_TYPE_DECL_1_CC_GENERIC_T4 CC_TYPE_DECL_CC_GENERIC_T4,
#define CC_TYPE_DECL_2_CC_GENERIC_T4 CC_TYPE_DECL_CC_GENERIC_T4,
#define CC_TYPE_DECL_3_CC_GENERIC_T4 CC_TYPE_DECL_CC_GENERIC_T4,
#define CC_TYPE_DECL_4_CC_GENERIC_T4 CC_TYPE_DECL_CC_GENERIC_T4,
#define CC_TYPE_DECL_5_CC_GENERIC_T4 CC_TYPE_DECL_CC_GENERIC_T4,
#define CC_TYPE_DECL_6_CC_GENERIC_T4 CC_TYPE_DECL_CC_GENERIC_T4,
#define CC_TYPE_DECL_7_CC_GENERIC_T4 CC_TYPE_DECL_CC_GENERIC_T4,
#define CC_TYPE_DECL_8_CC_GENERIC_T4 CC_TYPE_DECL_CC_GENERIC_T4,
#define CC_TYPE_DECL_9_CC_GENERIC_T4 CC_TYPE_DECL_CC_GENERIC_T4,
#define CC_TYPE_DECL_0_CC_GENERIC_T5 CC_TYPE_DECL_CC_GENERIC_T5,
#define CC_TYPE_DECL_1_CC_GENERIC_T5 CC_TYPE_DECL_CC_GENERIC_T5,
#define CC_TYPE_DECL_2_CC_GENERIC_T5 CC_TYPE_DECL_CC_GENERIC_T5,
#define CC_TYPE_DECL_3_CC_GENERIC_T5 CC_TYPE_DECL_CC_GENERIC_T5,
#define CC_TYPE_DECL_4_CC_GENERIC_T5 CC_TYPE_DECL_CC_GENERIC_T5,
#define CC_TYPE_DECL_5_CC_GENERIC_T5 CC_TYPE_DECL_CC_GENERIC_T5,
#define CC_TYPE_DECL_6_CC_GENERIC_T5 CC_TYPE_DECL_CC_GENERIC_T5,
#define CC_TYPE_DECL_7_CC_GENERIC_T5 CC_TYPE_DECL_CC_GENERIC_T5,
#define CC_TYPE_DECL_8_CC_GENERIC_T5 CC_TYPE_DECL_CC_GENERIC_T5,
#define CC_TYPE_DECL_9_CC_GENERIC_T5 CC_TYPE_DECL_CC_GENERIC_T5,
#define CC_TYPE_DECL_0_CC_GENERIC_T6 CC_TYPE_DECL_CC_GENERIC_T6,
#define CC_TYPE_DECL_1_CC_GENERIC_T6 CC_TYPE_DECL_CC_GENERIC_T6,
#define CC_TYPE_DECL_2_CC_GENERIC_T6 CC_TYPE_DECL_CC_GENERIC_T6,
#define CC_TYPE_DECL_3_CC_GENERIC_T6 CC_TYPE_DECL_CC_GENERIC_T6,
#define CC_TYPE_DECL_4_CC_GENERIC_T6 CC_TYPE_DECL_CC_GENERIC_T6,
#define CC_TYPE_DECL_5_CC_GENERIC_T6 CC_TYPE_DECL_CC_GENERIC_T6,
#define CC_TYPE_DECL_6_CC_GENERIC_T6 CC_TYPE_DECL_CC_GENERIC_T6,
#define CC_TYPE_DECL_7_CC_GENERIC_T6 CC_TYPE_DECL_CC_GENERIC_T6,
#define CC_TYPE_DECL_8_CC_GENERIC_T6 CC_TYPE_DECL_CC_GENERIC_T6,
#define CC_TYPE_DECL_9_CC_GENERIC_T6 CC_TYPE_DECL_CC_GENERIC_T6,
#define CC_TYPE_DECL_0_CC_GENERIC_T7 CC_TYPE_DECL_CC_GENERIC_T7,
#define CC_TYPE_DECL_1_CC_GENERIC_T7 CC_TYPE_DECL_CC_GENERIC_T7,
#define CC_TYPE_DECL_2_CC_GENERIC_T7 CC_TYPE_DECL_CC_GENERIC_T7,
#define CC_TYPE_DECL_3_CC_GENERIC_T7 CC_TYPE_DECL_CC_GENERIC_T7,
#define CC_TYPE_DECL_4_CC_GENERIC_T7 CC_TYPE_DECL_CC_GENERIC_T7,
#define CC_TYPE_DECL_5_CC_GENERIC_T7 CC_TYPE_DECL_CC_GENERIC_T7,
#define CC_TYPE_DECL_6_CC_GENERIC_T7 CC_TYPE_DECL_CC_GENERIC_T7,
#define CC_TYPE_DECL_7_CC_GENERIC_T7 CC_TYPE_DECL_CC_GENERIC_T7,
#define CC_TYPE_DECL_8_CC_GENERIC_T7 CC_TYPE_DECL_CC_GENERIC_T7,
#define CC_TYPE_DECL_9_CC_GENERIC_T7 CC_TYPE_DECL_CC_GENERIC_T7,
#define CC_TYPE_DECL_0_CC_GENERIC_T8 CC_TYPE_DECL_CC_GENERIC_T8,
#define CC_TYPE_DECL_1_CC_GENERIC_T8 CC_TYPE_DECL_CC_GENERIC_T8,
#define CC_TYPE_DECL_2_CC_GENERIC_T8 CC_TYPE_DECL_CC_GENERIC_T8,
#define CC_TYPE_DECL_3_CC_GENERIC_T8 CC_TYPE_DECL_CC_GENERIC_T8,
#define CC_TYPE_DECL_4_CC_GENERIC_T8 CC_TYPE_DECL_CC_GENERIC_T8,
#define CC_TYPE_DECL_5_CC_GENERIC_T8 CC_TYPE_DECL_CC_GENERIC_T8,
#define CC_TYPE_DECL_6_CC_GENERIC_T8 CC_TYPE_DECL_CC_GENERIC_T8,
#define CC_TYPE_DECL_7_CC_GENERIC_T8 CC_TYPE_DECL_CC_GENERIC_T8,
#define CC_TYPE_DECL_8_CC_GENERIC_T8 CC_TYPE_DECL_CC_GENERIC_T8,
#define CC_TYPE_DECL_9_CC_GENERIC_T8 CC_TYPE_DECL_CC_GENERIC_T8,
#define CC_TYPE_DECL_0_CC_GENERIC_T9 CC_TYPE_DECL_CC_GENERIC_T9,
#define CC_TYPE_DECL_1_CC_GENERIC_T9 CC_TYPE_DECL_CC_GENERIC_T9,
#define CC_TYPE_DECL_2_CC_GENERIC_T9 CC_TYPE_DECL_CC_GENERIC_T9,
#define CC_TYPE_DECL_3_CC_GENERIC_T9 CC_TYPE_DECL_CC_GENERIC_T9,
#define CC_TYPE_DECL_4_CC_GENERIC_T9 CC_TYPE_DECL_CC_GENERIC_T9,
#define CC_TYPE_DECL_5_CC_GENERIC_T9 CC_TYPE_DECL_CC_GENERIC_T9,
#define CC_TYPE_DECL_6_CC_GENERIC_T9 CC_TYPE_DECL_CC_GENERIC_T9,
#define CC_TYPE_DECL_7_CC_GENERIC_T9 CC_TYPE_DECL_CC_GENERIC_T9,
#define CC_TYPE_DECL_8_CC_GENERIC_T9 CC_TYPE_DECL_CC_GENERIC_T9,
#define CC_TYPE_DECL_9_CC_GENERIC_T9 CC_TYPE_DECL_CC_GENERIC_T9,
#define CC_TYPE_DECL_0_CC_GENERIC_T10 CC_TYPE_DECL_CC_GENERIC_T10,
#define CC_TYPE_DECL_1_CC_GENERIC_T10 CC_TYPE_DECL_CC_GENERIC_T10,
#define CC_TYPE_DECL_2_CC_GENERIC_T10 CC_TYPE_DECL_CC_GENERIC_T10,
#define CC_TYPE_DECL_3_CC_GENERIC_T10 CC_TYPE_DECL_CC_GENERIC_T10,
#define CC_TYPE_DECL_4_CC_GENERIC_T10 CC_TYPE_DECL_CC_GENERIC_T10,
#define CC_TYPE_DECL_5_CC_GENERIC_T10 CC_TYPE_DECL_CC_GENERIC_T10,
#define CC_TYPE_DECL_6_CC_GENERIC_T10 CC_TYPE_DECL_CC_GENERIC_T10,
#define CC_TYPE_DECL_7_CC_GENERIC_T10 CC_TYPE_DECL_CC_GENERIC_T10,
#define CC_TYPE_DECL_8_CC_GENERIC_T10 CC_TYPE_DECL_CC_GENERIC_T10,
#define CC_TYPE_DECL_9_CC_GENERIC_T10 CC_TYPE_DECL_CC_GENERIC_T10,
#define CC_TYPE_DECL_0_CC_GENERIC_T11 CC_TYPE_DECL_CC_GENERIC_T11,
#define CC_TYPE_DECL_1_CC_GENERIC_T11 CC_TYPE_DECL_CC_GENERIC_T11,
#define CC_TYPE_DECL_2_CC_GENERIC_T11 CC_TYPE_DECL_CC_GENERIC_T11,
#define CC_TYPE_DECL_3_CC_GENERIC_T11 CC_TYPE_DECL_CC_GENERIC_T11,
#define CC_TYPE_DECL_4_CC_GENERIC_T11 CC_TYPE_DECL_CC_GENERIC_T11,
#define CC_TYPE_DECL_5_CC_GENERIC_T11 CC_TYPE_DECL_CC_GENERIC_T11,
#define CC_TYPE_DECL_6_CC_GENERIC_T11 CC_TYPE_DECL_CC_GENERIC_T11,
#define CC_TYPE_DECL_7_CC_GENERIC_T11 CC_TYPE_DECL_CC_GENERIC_T11,
#define CC_TYPE_DECL_8_CC_GENERIC_T11 CC_TYPE_DECL_CC_GENERIC_T11,
#define CC_TYPE_DECL_9_CC_GENERIC_T11 CC_TYPE_DECL_CC_GENERIC_T11,
#define CC_TYPE_DECL_0_CC_GENERIC_T12 CC_TYPE_DECL_CC_GENERIC_T12,
#define CC_TYPE_DECL_1_CC_GENERIC_T12 CC_TYPE_DECL_CC_GENERIC_T12,
#define CC_TYPE_DECL_2_CC_GENERIC_T12 CC_TYPE_DECL_CC_GENERIC_T12,
#define CC_TYPE_DECL_3_CC_GENERIC_T12 CC_TYPE_DECL_CC_GENERIC_T12,
#define CC_TYPE_DECL_4_CC_GENERIC_T12 CC_TYPE_DECL_CC_GENERIC_T12,
#define CC_TYPE_DECL_5_CC_GENERIC_T12 CC_TYPE_DECL_CC_GENERIC_T12,
#define CC_TYPE_DECL_6_CC_GENERIC_T12 CC_TYPE_DECL_CC_GENERIC_T12,
#define CC_TYPE_DECL_7_CC_GENERIC_T12 CC_TYPE_DECL_CC_GENERIC_T12,
#define CC_TYPE_DECL_8_CC_GENERIC_T12 CC_TYPE_DECL_CC_GENERIC_T12,
#define CC_TYPE_DECL_9_CC_GENERIC_T12 CC_TYPE_DECL_CC_GENERIC_T12,
#define CC_TYPE_DECL_0_CC_GENERIC_T13 CC_TYPE_DECL_CC_GENERIC_T13,
#define CC_TYPE_DECL_1_CC_GENERIC_T13 CC_TYPE_DECL_CC_GENERIC_T13,
#define CC_TYPE_DECL_2_CC_GENERIC_T13 CC_TYPE_DECL_CC_GENERIC_T13,
#define CC_TYPE_DECL_3_CC_GENERIC_T13 CC_TYPE_DECL_CC_GENERIC_T13,
#define CC_TYPE_DECL_4_CC_GENERIC_T13 CC_TYPE_DECL_CC_GENERIC_T13,
#define CC_TYPE_DECL_5_CC_GENERIC_T13 CC_TYPE_DECL_CC_GENERIC_T13,
#define CC_TYPE_DECL_6_CC_GENERIC_T13 CC_TYPE_DECL_CC_GENERIC_T13,
#define CC_TYPE_DECL_7_CC_GENERIC_T13 CC_TYPE_DECL_CC_GENERIC_T13,
#define CC_TYPE_DECL_8_CC_GENERIC_T13 CC_TYPE_DECL_CC_GENERIC_T13,
#define CC_TYPE_DECL_9_CC_GENERIC_T13 CC_TYPE_DECL_CC_GENERIC_T13,
#define CC_TYPE_DECL_0_CC_GENERIC_T14 CC_TYPE_DECL_CC_GENERIC_T14,
#define CC_TYPE_DECL_1_CC_GENERIC_T14 CC_TYPE_DECL_CC_GENERIC_T14,
#define CC_TYPE_DECL_2_CC_GENERIC_T14 CC_TYPE_DECL_CC_GENERIC_T14,
#define CC_TYPE_DECL_3_CC_GENERIC_T14 CC_TYPE_DECL_CC_GENERIC_T14,
#define CC_TYPE_DECL_4_CC_GENERIC_T14 CC_TYPE_DECL_CC_GENERIC_T14,
#define CC_TYPE_DECL_5_CC_GENERIC_T14 CC_TYPE_DECL_CC_GENERIC_T14,
#define CC_TYPE_DECL_6_CC_GENERIC_T14 CC_TYPE_DECL_CC_GENERIC_T14,
#define CC_TYPE_DECL_7_CC_GENERIC_T14 CC_TYPE_DECL_CC_GENERIC_T14,
#define CC_TYPE_DECL_8_CC_GENERIC_T14 CC_TYPE_DECL_CC_GENERIC_T14,
#define CC_TYPE_DECL_9_CC_GENERIC_T14 CC_TYPE_DECL_CC_GENERIC_T14,
#define CC_TYPE_DECL_0_CC_GENERIC_T15 CC_TYPE_DECL_CC_GENERIC_T15,
#define CC_TYPE_DECL_1_CC_GENERIC_T15 CC_TYPE_DECL_CC_GENERIC_T15,
#define CC_TYPE_DECL_2_CC_GENERIC_T15 CC_TYPE_DECL_CC_GENERIC_T15,
#define CC_TYPE_DECL_3_CC_GENERIC_T15 CC_TYPE_DECL_CC_GENERIC_T15,
#define CC_TYPE_DECL_4_CC_GENERIC_T15 CC_TYPE_DECL_CC_GENERIC_T15,
#define CC_TYPE_DECL_5_CC_GENERIC_T15 CC_TYPE_DECL_CC_GENERIC_T15,
#define CC_TYPE_DECL_6_CC_GENERIC_T15 CC_TYPE_DECL_CC_GENERIC_T15,
#define CC_TYPE_DECL_7_CC_GENERIC_T15 CC_TYPE_DECL_CC_GENERIC_T15,
#define CC_TYPE_DECL_8_CC_GENERIC_T15 CC_TYPE_DECL_CC_GENERIC_T15,
#define CC_TYPE_DECL_9_CC_GENERIC_T15 CC_TYPE_DECL_CC_GENERIC_T15,
#define CC_TYPE_DECL_0_CC_GENERIC_T16 CC_TYPE_DECL_CC_GENERIC_T16,
#define CC_TYPE_DECL_1_CC_GENERIC_T16 CC_TYPE_DECL_CC_GENERIC_T16,
#define CC_TYPE_DECL_2_CC_GENERIC_T16 CC_TYPE_DECL_CC_GENERIC_T16,
#define CC_TYPE_DECL_3_CC_GENERIC_T16 CC_TYPE_DECL_CC_GENERIC_T16,
#define CC_TYPE_DECL_4_CC_GENERIC_T16 CC_TYPE_DECL_CC_GENERIC_T16,
#define CC_TYPE_DECL_5_CC_GENERIC_T16 CC_TYPE_DECL_CC_GENERIC_T16,
#define CC_TYPE_DECL_6_CC_GENERIC_T16 CC_TYPE_DECL_CC_GENERIC_T16,
#define CC_TYPE_DECL_7_CC_GENERIC_T16 CC_TYPE_DECL_CC_GENERIC_T16,
#define CC_TYPE_DECL_8_CC_GENERIC_T16 CC_TYPE_DECL_CC_GENERIC_T16,
#define CC_TYPE_DECL_9_CC_GENERIC_T16 CC_TYPE_DECL_CC_GENERIC_T16,
#define CC_TYPE_DECL_0_CC_GENERIC_T17 CC_TYPE_DECL_CC_GENERIC_T17,
#define CC_TYPE_DECL_1_CC_GENERIC_T17 CC_TYPE_DECL_CC_GENERIC_T17,
#define CC_TYPE_DECL_2_CC_GENERIC_T17 CC_TYPE_DECL_CC_GENERIC_T17,
#define CC_TYPE_DECL_3_CC_GENERIC_T17 CC_TYPE_DECL_CC_GENERIC_T17,
#define CC_TYPE_DECL_4_CC_GENERIC_T17 CC_TYPE_DECL_CC_GENERIC_T17,
#define CC_TYPE_DECL_5_CC_GENERIC_T17 CC_TYPE_DECL_CC_GENERIC_T17,
#define CC_TYPE_DECL_6_CC_GENERIC_T17 CC_TYPE_DECL_CC_GENERIC_T17,
#define CC_TYPE_DECL_7_CC_GENERIC_T17 CC_TYPE_DECL_CC_GENERIC_T17,
#define CC_TYPE_DECL_8_CC_GENERIC_T17 CC_TYPE_DECL_CC_GENERIC_T17,
#define CC_TYPE_DECL_9_CC_GENERIC_T17 CC_TYPE_DECL_CC_GENERIC_T17,
#define CC_TYPE_DECL_0_CC_GENERIC_T18 CC_TYPE_DECL_CC_GENERIC_T18,
#define CC_TYPE_DECL_1_CC_GENERIC_T18 CC_TYPE_DECL_CC_GENERIC_T18,
#define CC_TYPE_DECL_2_CC_GENERIC_T18 CC_TYPE_DECL_CC_GENERIC_T18,
#define CC_TYPE_DECL_3_CC_GENERIC_T18 CC_TYPE_DECL_CC_GENERIC_T18,
#define CC_TYPE_DECL_4_CC_GENERIC_T18 CC_TYPE_DECL_CC_GENERIC_T18,
#define CC_TYPE_DECL_5_CC_GENERIC_T18 CC_TYPE_DECL_CC_GENERIC_T18,
#define CC_TYPE_DECL_6_CC_GENERIC_T18 CC_TYPE_DECL_CC_GENERIC_T18,
#define CC_TYPE_DECL_7_CC_GENERIC_T18 CC_TYPE_DECL_CC_GENERIC_T18,
#define CC_TYPE_DECL_8_CC_GENERIC_T18 CC_TYPE_DECL_CC_GENERIC_T18,
#define CC_TYPE_DECL_9_CC_GENERIC_T18 CC_TYPE_DECL_CC_GENERIC_T18,
#define CC_TYPE_DECL_0_CC_GENERIC_T19 CC_TYPE_DECL_CC_GENERIC_T19,
#define CC_TYPE_DECL_1_CC_GENERIC_T19 CC_TYPE_DECL_CC_GENERIC_T19,
#define CC_TYPE_DECL_2_CC_GENERIC_T19 CC_TYPE_DECL_CC_GENERIC_T19,
#define CC_TYPE_DECL_3_CC_GENERIC_T19 CC_TYPE_DECL_CC_GENERIC_T19,
#define CC_TYPE_DECL_4_CC_GENERIC_T19 CC_TYPE_DECL_CC_GENERIC_T19,
#define CC_TYPE_DECL_5_CC_GENERIC_T19 CC_TYPE_DECL_CC_GENERIC_T19,
#define CC_TYPE_DECL_6_CC_GENERIC_T19 CC_TYPE_DECL_CC_GENERIC_T19,
#define CC_TYPE_DECL_7_CC_GENERIC_T19 CC_TYPE_DECL_CC_GENERIC_T19,
#define CC_TYPE_DECL_8_CC_GENERIC_T19 CC_TYPE_DECL_CC_GENERIC_T19,
#define CC_TYPE_DECL_9_CC_GENERIC_T19 CC_TYPE_DECL_CC_GENERIC_T19,

#define CC_GENERIC_T(n) CC_GENERIC_T_(CC_GENERIC_TYPE, n)
#define CC_GENERIC_T_(t, n) CC_GENERIC_T__(t, n)
#define CC_GENERIC_T__(t, n) t##_T##n

#if !defined(CC_GENERIC_COUNT) || CC_GENERIC_COUNT == 0
typedef CC_TYPE_DECL(T) CC_GENERIC_T(0);
#undef T
#define T CC_GENERIC_T0

#undef CC_GENERIC_COUNT
#define CC_GENERIC_COUNT 1

#elif CC_GENERIC_COUNT == 1
typedef CC_TYPE_DECL(T) CC_GENERIC_T(1);
#undef T
#define T CC_GENERIC_T1

#undef CC_GENERIC_COUNT
#define CC_GENERIC_COUNT 2

#elif CC_GENERIC_COUNT == 2
typedef CC_TYPE_DECL(T) CC_GENERIC_T(2);
#undef T
#define T CC_GENERIC_T2

#undef CC_GENERIC_COUNT
#define CC_GENERIC_COUNT 3

#elif CC_GENERIC_COUNT == 3
typedef CC_TYPE_DECL(T) CC_GENERIC_T(3);
#undef T
#define T CC_GENERIC_T3

#undef CC_GENERIC_COUNT
#define CC_GENERIC_COUNT 4

#elif CC_GENERIC_COUNT == 4
typedef CC_TYPE_DECL(T) CC_GENERIC_T(4);
#undef T
#define T CC_GENERIC_T4

#undef CC_GENERIC_COUNT
#define CC_GENERIC_COUNT 5

#elif CC_GENERIC_COUNT == 5
typedef CC_TYPE_DECL(T) CC_GENERIC_T(5);
#undef T
#define T CC_GENERIC_T5

#undef CC_GENERIC_COUNT
#define CC_GENERIC_COUNT 6

#elif CC_GENERIC_COUNT == 6
typedef CC_TYPE_DECL(T) CC_GENERIC_T(6);
#undef T
#define T CC_GENERIC_T6

#undef CC_GENERIC_COUNT
#define CC_GENERIC_COUNT 7

#elif CC_GENERIC_COUNT == 7
typedef CC_TYPE_DECL(T) CC_GENERIC_T(7);
#undef T
#define T CC_GENERIC_T7

#undef CC_GENERIC_COUNT
#define CC_GENERIC_COUNT 8

#elif CC_GENERIC_COUNT == 8
typedef CC_TYPE_DECL(T) CC_GENERIC_T(8);
#undef T
#define T CC_GENERIC_T8

#undef CC_GENERIC_COUNT
#define CC_GENERIC_COUNT 9

#elif CC_GENERIC_COUNT == 9
typedef CC_TYPE_DECL(T) CC_GENERIC_T(9);
#undef T
#define T CC_GENERIC_T9

#undef CC_GENERIC_COUNT
#define CC_GENERIC_COUNT 10

#elif CC_GENERIC_COUNT == 10
typedef CC_TYPE_DECL(T) CC_GENERIC_T(10);
#undef T
#define T CC_GENERIC_T10

#undef CC_GENERIC_COUNT
#define CC_GENERIC_COUNT 11

#elif CC_GENERIC_COUNT == 11
typedef CC_TYPE_DECL(T) CC_GENERIC_T(11);
#undef T
#define T CC_GENERIC_T11

#undef CC_GENERIC_COUNT
#define CC_GENERIC_COUNT 12

#elif CC_GENERIC_COUNT == 12
typedef CC_TYPE_DECL(T) CC_GENERIC_T(12);
#undef T
#define T CC_GENERIC_T12

#undef CC_GENERIC_COUNT
#define CC_GENERIC_COUNT 13

#elif CC_GENERIC_COUNT == 13
typedef CC_TYPE_DECL(T) CC_GENERIC_T(13);
#undef T
#define T CC_GENERIC_T13

#undef CC_GENERIC_COUNT
#define CC_GENERIC_COUNT 14

#elif CC_GENERIC_COUNT == 14
typedef CC_TYPE_DECL(T) CC_GENERIC_T(14);
#undef T
#define T CC_GENERIC_T14

#undef CC_GENERIC_COUNT
#define CC_GENERIC_COUNT 15

#elif CC_GENERIC_COUNT == 15
typedef CC_TYPE_DECL(T) CC_GENERIC_T(15);
#undef T
#define T CC_GENERIC_T15

#undef CC_GENERIC_COUNT
#define CC_GENERIC_COUNT 16

#elif CC_GENERIC_COUNT == 16
typedef CC_TYPE_DECL(T) CC_GENERIC_T(16);
#undef T
#define T CC_GENERIC_T16

#undef CC_GENERIC_COUNT
#define CC_GENERIC_COUNT 17

#elif CC_GENERIC_COUNT == 17
typedef CC_TYPE_DECL(T) CC_GENERIC_T(17);
#undef T
#define T CC_GENERIC_T17

#undef CC_GENERIC_COUNT
#define CC_GENERIC_COUNT 18

#elif CC_GENERIC_COUNT == 18
typedef CC_TYPE_DECL(T) CC_GENERIC_T(18);
#undef T
#define T CC_GENERIC_T18

#undef CC_GENERIC_COUNT
#define CC_GENERIC_COUNT 19

#elif CC_GENERIC_COUNT == 19
typedef CC_TYPE_DECL(T) CC_GENERIC_T(19);
#undef T
#define T CC_GENERIC_T19

#undef CC_GENERIC_COUNT
#define CC_GENERIC_COUNT 20

#else
#error Add additional cases
#endif

#include CC_GENERIC_TEMPLATE

#ifndef CC_GENERIC_PRESERVE_TYPE
#undef T
#endif

#ifndef CC_GENERIC_PRESERVE_HEADER
#undef CC_GENERIC_TEMPLATE
#endif
