/*
 *  Copyright (c) 2026, Stefan Johnson
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without modification,
 *  are permitted provided that the following conditions are met:
 *
 *  1. Redistributions of source code must retain the above copyright notice, this list
 *     of conditions and the following disclaimer.
 *  2. Redistributions in binary form must reproduce the above copyright notice, this
 *     list of conditions and the following disclaimer in the documentation and/or other
 *     materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef CC_SIMD_WIDTH
#error "CC_SIMD_WIDTH is not defined"
#endif

#define CC_SIMD_LANES_MAX (CC_SIMD_WIDTH / 8)

#define CC_SIMD_N_2_ELEMENT_TYPES CC_CAT(CC_SIMD_, CC_SIMD_WIDTH, _2_ELEMENT_TYPES)
#define CC_SIMD_N_4_ELEMENT_TYPES CC_CAT(CC_SIMD_, CC_SIMD_WIDTH, _4_ELEMENT_TYPES)
#define CC_SIMD_N_8_ELEMENT_TYPES CC_CAT(CC_SIMD_, CC_SIMD_WIDTH, _8_ELEMENT_TYPES)
#define CC_SIMD_N_16_ELEMENT_TYPES CC_CAT(CC_SIMD_, CC_SIMD_WIDTH, _16_ELEMENT_TYPES)
#define CC_SIMD_N_32_ELEMENT_TYPES CC_CAT(CC_SIMD_, CC_SIMD_WIDTH, _32_ELEMENT_TYPES)
#define CC_SIMD_N_64_ELEMENT_TYPES CC_CAT(CC_SIMD_, CC_SIMD_WIDTH, _64_ELEMENT_TYPES)

#define CC_SIMD_N_INTEGER_TYPES CC_CAT(CC_SIMD_, CC_SIMD_WIDTH, _INTEGER_TYPES)
#define CC_SIMD_N_FLOAT_TYPES CC_CAT(CC_SIMD_, CC_SIMD_WIDTH, _FLOAT_TYPES)

#define CC_SIMD_N_TYPES CC_CAT(CC_SIMD_, CC_SIMD_WIDTH, _TYPES)

#define CC_SIMD_N_2_ELEMENT_INTEGER_TYPES CC_CAT(CC_SIMD_, CC_SIMD_WIDTH, _2_ELEMENT_INTEGER_TYPES)
#define CC_SIMD_N_4_ELEMENT_INTEGER_TYPES CC_CAT(CC_SIMD_, CC_SIMD_WIDTH, _4_ELEMENT_INTEGER_TYPES)
#define CC_SIMD_N_8_ELEMENT_INTEGER_TYPES CC_CAT(CC_SIMD_, CC_SIMD_WIDTH, _8_ELEMENT_INTEGER_TYPES)
#define CC_SIMD_N_16_ELEMENT_INTEGER_TYPES CC_CAT(CC_SIMD_, CC_SIMD_WIDTH, _16_ELEMENT_INTEGER_TYPES)
#define CC_SIMD_N_32_ELEMENT_INTEGER_TYPES CC_CAT(CC_SIMD_, CC_SIMD_WIDTH, _32_ELEMENT_INTEGER_TYPES)
#define CC_SIMD_N_64_ELEMENT_INTEGER_TYPES CC_CAT(CC_SIMD_, CC_SIMD_WIDTH, _64_ELEMENT_INTEGER_TYPES)

#if CC_SIMD_WIDTH >= 16
#define CC_SIMD_N_INTEGER_8_TYPES CC_CAT(CC_SIMD_, CC_SIMD_WIDTH, _INTEGER_8_TYPES)
#if CC_SIMD_WIDTH >= 32
#define CC_SIMD_N_INTEGER_16_TYPES CC_CAT(CC_SIMD_, CC_SIMD_WIDTH, _INTEGER_16_TYPES)
#if CC_SIMD_WIDTH >= 64
#define CC_SIMD_N_INTEGER_32_TYPES CC_CAT(CC_SIMD_, CC_SIMD_WIDTH, _INTEGER_32_TYPES)
#if CC_SIMD_WIDTH >= 128
#define CC_SIMD_N_INTEGER_64_TYPES CC_CAT(CC_SIMD_, CC_SIMD_WIDTH, _INTEGER_64_TYPES)
#endif
#endif
#endif
#endif

#pragma mark -

#define CC_SIMD_MISSING_CCSimdZero CC_SIMD_N_TYPES
#define CC_SIMD_MISSING_CCSimdSetSequence CC_SIMD_N_TYPES
#define CC_SIMD_MISSING_CCSimdAndNot CC_SIMD_N_INTEGER_TYPES
#define CC_SIMD_MISSING_CCSimdRotateLeft CC_SIMD_N_INTEGER_TYPES
#define CC_SIMD_MISSING_CCSimdRotateLeftN CC_SIMD_N_INTEGER_TYPES
#define CC_SIMD_MISSING_CCSimdRotateRight CC_SIMD_N_INTEGER_TYPES
#define CC_SIMD_MISSING_CCSimdRotateRightN CC_SIMD_N_INTEGER_TYPES
#define CC_SIMD_MISSING_CCSimdLowestUnset CC_SIMD_N_INTEGER_TYPES
#define CC_SIMD_MISSING_CCSimdLowestSet CC_SIMD_N_INTEGER_TYPES
#define CC_SIMD_MISSING_CCSimdHighestSet CC_SIMD_N_INTEGER_TYPES
#define CC_SIMD_MISSING_CCSimdNextPow2 CC_SIMD_N_INTEGER_TYPES
#define CC_SIMD_MISSING_CCSimdMask CC_SIMD_N_INTEGER_TYPES
#define CC_SIMD_MISSING_CCSimdMaskLowerPow2 CC_SIMD_N_INTEGER_TYPES
#define CC_SIMD_MISSING_CCSimdMaskHighestUnset CC_SIMD_N_INTEGER_TYPES
#define CC_SIMD_MISSING_CCSimdCountLowestUnset CC_SIMD_N_INTEGER_TYPES
#define CC_SIMD_MISSING_CCSimdCountSet CC_SIMD_N_INTEGER_TYPES
#define CC_SIMD_MISSING_CCSimdCompareEqual CC_SIMD_N_TYPES
#define CC_SIMD_MISSING_CCSimdCompareNotEqual CC_SIMD_N_TYPES
#define CC_SIMD_MISSING_CCSimdCompareLessThan CC_SIMD_N_TYPES
#define CC_SIMD_MISSING_CCSimdCompareLessThanEqual CC_SIMD_N_TYPES
#define CC_SIMD_MISSING_CCSimdCompareGreaterThan CC_SIMD_N_TYPES
#define CC_SIMD_MISSING_CCSimdCompareGreaterThanEqual CC_SIMD_N_TYPES
#define CC_SIMD_MISSING_CCSimdMaskCompareNotEqual CC_SIMD_N_TYPES
#define CC_SIMD_MISSING_CCSimdMin CC_SIMD_N_TYPES
#define CC_SIMD_MISSING_CCSimdMax CC_SIMD_N_TYPES
#define CC_SIMD_MISSING_CCSimdMadd CC_SIMD_N_TYPES
#define CC_SIMD_MISSING_CCSimdNegMadd CC_SIMD_N_TYPES
#define CC_SIMD_MISSING_CCSimdMsub CC_SIMD_N_TYPES
#define CC_SIMD_MISSING_CCSimdNegMsub CC_SIMD_N_TYPES
#define CC_SIMD_MISSING_CCSimdDiv CC_SIMD_N_TYPES
#define CC_SIMD_MISSING_CCSimdMod CC_SIMD_N_TYPES
#define CC_SIMD_MISSING_CCSimdHadd CC_SIMD_N_TYPES
#define CC_SIMD_MISSING_CCSimdHsub CC_SIMD_N_TYPES
#define CC_SIMD_MISSING_CCSimdDot CC_SIMD_N_TYPES
#define CC_SIMD_MISSING_CCSimdClamp CC_SIMD_N_TYPES

#define CC_SIMD_MISSING_CCSimdPosPiRadSin CC_SIMD_N_FLOAT_TYPES
#define CC_SIMD_MISSING_CCSimdHalfPiRadCos CC_SIMD_N_FLOAT_TYPES
#define CC_SIMD_MISSING_CCSimdPosSin CC_SIMD_N_FLOAT_TYPES
#define CC_SIMD_MISSING_CCSimdPiRadSin CC_SIMD_N_FLOAT_TYPES
#define CC_SIMD_MISSING_CCSimdSin CC_SIMD_N_FLOAT_TYPES
#define CC_SIMD_MISSING_CCSimdArcSin CC_SIMD_N_FLOAT_TYPES
#define CC_SIMD_MISSING_CCSimdCos CC_SIMD_N_FLOAT_TYPES
#define CC_SIMD_MISSING_CCSimdArcCos CC_SIMD_N_FLOAT_TYPES
#define CC_SIMD_MISSING_CCSimdTan CC_SIMD_N_FLOAT_TYPES
#define CC_SIMD_MISSING_CCSimdQtrPiArcTan CC_SIMD_N_FLOAT_TYPES
#define CC_SIMD_MISSING_CCSimdArcTan CC_SIMD_N_FLOAT_TYPES
#define CC_SIMD_MISSING_CCSimdArcTan2 CC_SIMD_N_FLOAT_TYPES
#define CC_SIMD_MISSING_CCSimdCsc CC_SIMD_N_FLOAT_TYPES
#define CC_SIMD_MISSING_CCSimdSec CC_SIMD_N_FLOAT_TYPES
#define CC_SIMD_MISSING_CCSimdCot CC_SIMD_N_FLOAT_TYPES
#define CC_SIMD_MISSING_CCSimdLog2 CC_SIMD_N_FLOAT_TYPES
#define CC_SIMD_MISSING_CCSimdLog CC_SIMD_N_FLOAT_TYPES
#define CC_SIMD_MISSING_CCSimdPow CC_SIMD_N_FLOAT_TYPES
#define CC_SIMD_MISSING_CCSimdPow2 CC_SIMD_N_FLOAT_TYPES
#define CC_SIMD_MISSING_CCSimdExp CC_SIMD_N_FLOAT_TYPES
#define CC_SIMD_MISSING_CCSimdExp2 CC_SIMD_N_FLOAT_TYPES
#define CC_SIMD_MISSING_CCSimdCbrt CC_SIMD_N_FLOAT_TYPES
#define CC_SIMD_MISSING_CCSimdInvCbrt CC_SIMD_N_FLOAT_TYPES
