/*
 *  Copyright (c) 2013, 2014, Stefan Johnson
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without modification,
 *  are permitted provided that the following conditions are met:
 *
 *  1. Redistributions of source code must retain the above copyright notice, this list
 *     of conditions and the following disclaimer.
 *  2. Redistributions in binary form must reproduce the above copyright notice, this
 *     list of conditions and the following disclaimer in the documentation and/or other
 *     materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef CommonGL_Version_h
#define CommonGL_Version_h

#import <CommonGL/Defined.h>


#define CC_OPENGL_VERSION_1_0       10000
#define CC_OPENGL_VERSION_1_1       10100
#define CC_OPENGL_VERSION_1_2       10200
#define CC_OPENGL_VERSION_1_2_1     10201
#define CC_OPENGL_VERSION_1_3       10300
#define CC_OPENGL_VERSION_1_4       10400
#define CC_OPENGL_VERSION_1_5       10500
#define CC_OPENGL_VERSION_2_0       20000
#define CC_OPENGL_VERSION_2_1       20100
#define CC_OPENGL_VERSION_3_0       30000
#define CC_OPENGL_VERSION_3_1       30100
#define CC_OPENGL_VERSION_3_2       30200
#define CC_OPENGL_VERSION_3_3       30300
#define CC_OPENGL_VERSION_4_0       40000
#define CC_OPENGL_VERSION_4_1       40100
#define CC_OPENGL_VERSION_4_2       40200
#define CC_OPENGL_VERSION_4_3       40300
#define CC_OPENGL_VERSION_4_4       40400
#define CC_OPENGL_VERSION_4_5       40500
#define CC_OPENGL_VERSION_NA        99999


#define CC_OPENGL_ES_VERSION_1_0    10000
#define CC_OPENGL_ES_VERSION_1_1    10100
#define CC_OPENGL_ES_VERSION_2_0    20000
#define CC_OPENGL_ES_VERSION_3_0    30000
#define CC_OPENGL_ES_VERSION_3_1    30100
#define CC_OPENGL_ES_VERSION_NA     99999


#if CC_OPENGL

#if !defined(CC_OPENGL_MODERN) && !defined(CC_OPENGL_LEGACY)
#if defined(__gl_h_)
#define CC_OPENGL_LEGACY 1
#elif defined(__gl3_h_)
#define CC_OPENGL_MODERN 1
#endif
#endif

#if GL_VERSION_4_5
#define CC_OPENGL_VERSION_MAX_ALLOWED CC_OPENGL_VERSION_4_5
#elif GL_VERSION_4_4
#define CC_OPENGL_VERSION_MAX_ALLOWED CC_OPENGL_VERSION_4_4
#elif GL_VERSION_4_3
#define CC_OPENGL_VERSION_MAX_ALLOWED CC_OPENGL_VERSION_4_3
#elif GL_VERSION_4_2
#define CC_OPENGL_VERSION_MAX_ALLOWED CC_OPENGL_VERSION_4_2
#elif GL_VERSION_4_1
#define CC_OPENGL_VERSION_MAX_ALLOWED CC_OPENGL_VERSION_4_1
#elif GL_VERSION_4_0
#define CC_OPENGL_VERSION_MAX_ALLOWED CC_OPENGL_VERSION_4_0
#elif GL_VERSION_3_3
#define CC_OPENGL_VERSION_MAX_ALLOWED CC_OPENGL_VERSION_3_3
#elif GL_VERSION_3_2
#define CC_OPENGL_VERSION_MAX_ALLOWED CC_OPENGL_VERSION_3_2
#elif GL_VERSION_3_1
#define CC_OPENGL_VERSION_MAX_ALLOWED CC_OPENGL_VERSION_3_1
#elif GL_VERSION_3_0
#define CC_OPENGL_VERSION_MAX_ALLOWED CC_OPENGL_VERSION_3_0
#elif GL_VERSION_2_1
#define CC_OPENGL_VERSION_MAX_ALLOWED CC_OPENGL_VERSION_2_1
#elif GL_VERSION_2_0
#define CC_OPENGL_VERSION_MAX_ALLOWED CC_OPENGL_VERSION_2_0
#elif GL_VERSION_1_5
#define CC_OPENGL_VERSION_MAX_ALLOWED CC_OPENGL_VERSION_1_5
#elif GL_VERSION_1_4
#define CC_OPENGL_VERSION_MAX_ALLOWED CC_OPENGL_VERSION_1_4
#elif GL_VERSION_1_3
#define CC_OPENGL_VERSION_MAX_ALLOWED CC_OPENGL_VERSION_1_3
#elif GL_VERSION_1_2_1
#define CC_OPENGL_VERSION_MAX_ALLOWED CC_OPENGL_VERSION_1_2_1
#elif GL_VERSION_1_2
#define CC_OPENGL_VERSION_MAX_ALLOWED CC_OPENGL_VERSION_1_2
#elif GL_VERSION_1_1
#define CC_OPENGL_VERSION_MAX_ALLOWED CC_OPENGL_VERSION_1_1
#elif GL_VERSION_1_0
#define CC_OPENGL_VERSION_MAX_ALLOWED CC_OPENGL_VERSION_1_0
#else
#define CC_OPENGL_VERSION_MAX_ALLOWED CC_OPENGL_VERSION_NA
#endif

#ifdef CC_OPENGL_VERSION_MAX_ALLOWED
#define CC_GL_VERSION_MIN_REQUIRED(gl, gles) (CC_OPENGL_VERSION_MAX_ALLOWED >= (gl))
#define CC_GL_VERSION_MAX_SUPPORTED(gl, gles) (CC_OPENGL_VERSION_MAX_ALLOWED <= (gl))
#else
#define CC_GL_VERSION_MIN_REQUIRED(gl, gles) 0
#define CC_GL_VERSION_MAX_SUPPORTED(gl, gles) 0
#endif

#elif CC_OPENGL_ES

#if !defined(CC_OPENGL_ES_MODERN) && !defined(CC_OPENGL_ES_LEGACY)
#if defined(ES1_GL_H_GUARD)
#define CC_OPENGL_ES_LEGACY 1
#elif defined(__gl_es20_h_) || defined(__gl_es30_h_)
#define CC_OPENGL_ES_MODERN 1
#endif
#endif

#if GL_ES_VERSION_3_1
#define CC_OPENGL_ES_VERSION_MAX_ALLOWED CC_OPENGL_ES_VERSION_3_1
#elif GL_ES_VERSION_3_0
#define CC_OPENGL_ES_VERSION_MAX_ALLOWED CC_OPENGL_ES_VERSION_3_0
#elif GL_ES_VERSION_2_0
#define CC_OPENGL_ES_VERSION_MAX_ALLOWED CC_OPENGL_ES_VERSION_2_0
#elif GL_VERSION_ES_CM_1_1 || GL_VERSION_ES_CL_1_1 || GL_OES_VERSION_1_1
#define CC_OPENGL_ES_VERSION_MAX_ALLOWED CC_OPENGL_ES_VERSION_1_1
#elif GL_VERSION_ES_CM_1_0 || GL_VERSION_ES_CL_1_0 || GL_OES_VERSION_1_0
#define CC_OPENGL_ES_VERSION_MAX_ALLOWED CC_OPENGL_ES_VERSION_1_0
#else
#define CC_OPENGL_ES_VERSION_MAX_ALLOWED CC_OPENGL_ES_VERSION_NA
#endif

#ifdef CC_OPENGL_ES_VERSION_MAX_ALLOWED
#define CC_GL_VERSION_MIN_REQUIRED(gl, gles) (CC_OPENGL_ES_VERSION_MAX_ALLOWED >= (gles))
#define CC_GL_VERSION_MAX_SUPPORTED(gl, gles) (CC_OPENGL_VERSION_MAX_ALLOWED <= (gles))
#else
#define CC_GL_VERSION_MIN_REQUIRED(gl, gles) 0
#define CC_GL_VERSION_MAX_SUPPORTED(gl, gles) 0
#endif

#endif

#import <CommonGL/VersionMacro.h>

#endif
