/*
 *  Copyright (c) 2014, Stefan Johnson
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without modification,
 *  are permitted provided that the following conditions are met:
 *
 *  1. Redistributions of source code must retain the above copyright notice, this list
 *     of conditions and the following disclaimer.
 *  2. Redistributions in binary form must reproduce the above copyright notice, this
 *     list of conditions and the following disclaimer in the documentation and/or other
 *     materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef CommonGL_VersionMacro_h
#define CommonGL_VersionMacro_h

#if CC_GL_VERSION_MIN_REQUIRED(CC_OPENGL_VERSION_1_0, CC_OPENGL_ES_VERSION_1_0)
#define CC_GL_VERSION_ACTIVE_MIN_1_0(max, ...) CC_GL_VERSION_ACTIVE_MIN_1_0_MAX_##max(__VA_ARGS__)

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_0, CC_OPENGL_ES_VERSION_1_0)
#define CC_GL_VERSION_ACTIVE_MIN_1_0_MAX_1_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_0_MAX_1_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_1, CC_OPENGL_ES_VERSION_1_1)
#define CC_GL_VERSION_ACTIVE_MIN_1_0_MAX_1_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_0_MAX_1_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_2, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_0_MAX_1_2(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_0_MAX_1_2(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_2_1, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_0_MAX_1_2_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_0_MAX_1_2_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_3, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_0_MAX_1_3(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_0_MAX_1_3(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_4, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_0_MAX_1_4(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_0_MAX_1_4(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_5, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_0_MAX_1_5(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_0_MAX_1_5(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_2_0, CC_OPENGL_ES_VERSION_2_0)
#define CC_GL_VERSION_ACTIVE_MIN_1_0_MAX_2_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_0_MAX_2_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_2_1, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_0_MAX_2_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_0_MAX_2_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_0, CC_OPENGL_ES_VERSION_3_0)
#define CC_GL_VERSION_ACTIVE_MIN_1_0_MAX_3_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_0_MAX_3_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_1, CC_OPENGL_ES_VERSION_3_1)
#define CC_GL_VERSION_ACTIVE_MIN_1_0_MAX_3_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_0_MAX_3_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_2, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_0_MAX_3_2(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_0_MAX_3_2(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_3, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_0_MAX_3_3(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_0_MAX_3_3(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_0, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_0_MAX_4_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_0_MAX_4_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_1, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_0_MAX_4_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_0_MAX_4_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_2, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_0_MAX_4_2(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_0_MAX_4_2(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_3, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_0_MAX_4_3(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_0_MAX_4_3(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_4, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_0_MAX_4_4(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_0_MAX_4_4(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_5, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_0_MAX_4_5(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_0_MAX_4_5(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_NA, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_0_MAX_NA(...) __VA_ARGS__
#endif

#else
#define CC_GL_VERSION_ACTIVE_MIN_1_0(max, ...)
#endif

#if CC_GL_VERSION_MIN_REQUIRED(CC_OPENGL_VERSION_1_1, CC_OPENGL_ES_VERSION_1_1)
#define CC_GL_VERSION_ACTIVE_MIN_1_1(max, ...) CC_GL_VERSION_ACTIVE_MIN_1_1_MAX_##max(__VA_ARGS__)

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_0, CC_OPENGL_ES_VERSION_1_0)
#define CC_GL_VERSION_ACTIVE_MIN_1_1_MAX_1_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_1_MAX_1_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_1, CC_OPENGL_ES_VERSION_1_1)
#define CC_GL_VERSION_ACTIVE_MIN_1_1_MAX_1_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_1_MAX_1_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_2, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_1_MAX_1_2(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_1_MAX_1_2(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_2_1, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_1_MAX_1_2_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_1_MAX_1_2_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_3, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_1_MAX_1_3(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_1_MAX_1_3(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_4, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_1_MAX_1_4(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_1_MAX_1_4(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_5, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_1_MAX_1_5(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_1_MAX_1_5(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_2_0, CC_OPENGL_ES_VERSION_2_0)
#define CC_GL_VERSION_ACTIVE_MIN_1_1_MAX_2_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_1_MAX_2_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_2_1, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_1_MAX_2_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_1_MAX_2_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_0, CC_OPENGL_ES_VERSION_3_0)
#define CC_GL_VERSION_ACTIVE_MIN_1_1_MAX_3_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_1_MAX_3_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_1, CC_OPENGL_ES_VERSION_3_1)
#define CC_GL_VERSION_ACTIVE_MIN_1_1_MAX_3_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_1_MAX_3_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_2, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_1_MAX_3_2(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_1_MAX_3_2(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_3, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_1_MAX_3_3(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_1_MAX_3_3(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_0, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_1_MAX_4_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_1_MAX_4_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_1, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_1_MAX_4_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_1_MAX_4_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_2, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_1_MAX_4_2(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_1_MAX_4_2(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_3, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_1_MAX_4_3(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_1_MAX_4_3(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_4, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_1_MAX_4_4(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_1_MAX_4_4(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_5, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_1_MAX_4_5(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_1_MAX_4_5(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_NA, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_1_MAX_NA(...) __VA_ARGS__
#endif

#else
#define CC_GL_VERSION_ACTIVE_MIN_1_1(max, ...)
#endif

#if CC_GL_VERSION_MIN_REQUIRED(CC_OPENGL_VERSION_1_2, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_2(max, ...) CC_GL_VERSION_ACTIVE_MIN_1_2_MAX_##max(__VA_ARGS__)

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_0, CC_OPENGL_ES_VERSION_1_0)
#define CC_GL_VERSION_ACTIVE_MIN_1_2_MAX_1_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_2_MAX_1_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_1, CC_OPENGL_ES_VERSION_1_1)
#define CC_GL_VERSION_ACTIVE_MIN_1_2_MAX_1_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_2_MAX_1_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_2, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_2_MAX_1_2(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_2_MAX_1_2(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_2_1, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_2_MAX_1_2_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_2_MAX_1_2_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_3, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_2_MAX_1_3(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_2_MAX_1_3(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_4, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_2_MAX_1_4(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_2_MAX_1_4(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_5, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_2_MAX_1_5(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_2_MAX_1_5(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_2_0, CC_OPENGL_ES_VERSION_2_0)
#define CC_GL_VERSION_ACTIVE_MIN_1_2_MAX_2_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_2_MAX_2_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_2_1, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_2_MAX_2_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_2_MAX_2_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_0, CC_OPENGL_ES_VERSION_3_0)
#define CC_GL_VERSION_ACTIVE_MIN_1_2_MAX_3_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_2_MAX_3_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_1, CC_OPENGL_ES_VERSION_3_1)
#define CC_GL_VERSION_ACTIVE_MIN_1_2_MAX_3_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_2_MAX_3_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_2, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_2_MAX_3_2(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_2_MAX_3_2(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_3, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_2_MAX_3_3(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_2_MAX_3_3(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_0, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_2_MAX_4_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_2_MAX_4_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_1, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_2_MAX_4_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_2_MAX_4_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_2, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_2_MAX_4_2(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_2_MAX_4_2(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_3, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_2_MAX_4_3(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_2_MAX_4_3(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_4, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_2_MAX_4_4(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_2_MAX_4_4(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_5, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_2_MAX_4_5(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_2_MAX_4_5(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_NA, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_2_MAX_NA(...) __VA_ARGS__
#endif

#else
#define CC_GL_VERSION_ACTIVE_MIN_1_2(max, ...)
#endif

#if CC_GL_VERSION_MIN_REQUIRED(CC_OPENGL_VERSION_1_2_1, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_2_1(max, ...) CC_GL_VERSION_ACTIVE_MIN_1_2_1_MAX_##max(__VA_ARGS__)

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_0, CC_OPENGL_ES_VERSION_1_0)
#define CC_GL_VERSION_ACTIVE_MIN_1_2_1_MAX_1_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_2_1_MAX_1_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_1, CC_OPENGL_ES_VERSION_1_1)
#define CC_GL_VERSION_ACTIVE_MIN_1_2_1_MAX_1_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_2_1_MAX_1_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_2, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_2_1_MAX_1_2(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_2_1_MAX_1_2(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_2_1, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_2_1_MAX_1_2_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_2_1_MAX_1_2_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_3, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_2_1_MAX_1_3(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_2_1_MAX_1_3(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_4, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_2_1_MAX_1_4(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_2_1_MAX_1_4(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_5, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_2_1_MAX_1_5(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_2_1_MAX_1_5(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_2_0, CC_OPENGL_ES_VERSION_2_0)
#define CC_GL_VERSION_ACTIVE_MIN_1_2_1_MAX_2_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_2_1_MAX_2_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_2_1, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_2_1_MAX_2_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_2_1_MAX_2_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_0, CC_OPENGL_ES_VERSION_3_0)
#define CC_GL_VERSION_ACTIVE_MIN_1_2_1_MAX_3_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_2_1_MAX_3_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_1, CC_OPENGL_ES_VERSION_3_1)
#define CC_GL_VERSION_ACTIVE_MIN_1_2_1_MAX_3_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_2_1_MAX_3_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_2, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_2_1_MAX_3_2(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_2_1_MAX_3_2(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_3, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_2_1_MAX_3_3(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_2_1_MAX_3_3(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_0, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_2_1_MAX_4_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_2_1_MAX_4_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_1, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_2_1_MAX_4_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_2_1_MAX_4_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_2, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_2_1_MAX_4_2(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_2_1_MAX_4_2(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_3, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_2_1_MAX_4_3(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_2_1_MAX_4_3(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_4, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_2_1_MAX_4_4(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_2_1_MAX_4_4(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_5, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_2_1_MAX_4_5(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_2_1_MAX_4_5(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_NA, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_2_1_MAX_NA(...) __VA_ARGS__
#endif

#else
#define CC_GL_VERSION_ACTIVE_MIN_1_2_1(max, ...)
#endif

#if CC_GL_VERSION_MIN_REQUIRED(CC_OPENGL_VERSION_1_3, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_3(max, ...) CC_GL_VERSION_ACTIVE_MIN_1_3_MAX_##max(__VA_ARGS__)

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_0, CC_OPENGL_ES_VERSION_1_0)
#define CC_GL_VERSION_ACTIVE_MIN_1_3_MAX_1_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_3_MAX_1_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_1, CC_OPENGL_ES_VERSION_1_1)
#define CC_GL_VERSION_ACTIVE_MIN_1_3_MAX_1_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_3_MAX_1_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_2, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_3_MAX_1_2(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_3_MAX_1_2(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_2_1, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_3_MAX_1_2_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_3_MAX_1_2_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_3, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_3_MAX_1_3(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_3_MAX_1_3(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_4, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_3_MAX_1_4(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_3_MAX_1_4(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_5, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_3_MAX_1_5(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_3_MAX_1_5(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_2_0, CC_OPENGL_ES_VERSION_2_0)
#define CC_GL_VERSION_ACTIVE_MIN_1_3_MAX_2_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_3_MAX_2_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_2_1, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_3_MAX_2_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_3_MAX_2_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_0, CC_OPENGL_ES_VERSION_3_0)
#define CC_GL_VERSION_ACTIVE_MIN_1_3_MAX_3_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_3_MAX_3_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_1, CC_OPENGL_ES_VERSION_3_1)
#define CC_GL_VERSION_ACTIVE_MIN_1_3_MAX_3_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_3_MAX_3_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_2, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_3_MAX_3_2(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_3_MAX_3_2(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_3, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_3_MAX_3_3(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_3_MAX_3_3(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_0, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_3_MAX_4_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_3_MAX_4_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_1, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_3_MAX_4_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_3_MAX_4_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_2, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_3_MAX_4_2(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_3_MAX_4_2(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_3, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_3_MAX_4_3(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_3_MAX_4_3(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_4, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_3_MAX_4_4(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_3_MAX_4_4(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_5, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_3_MAX_4_5(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_3_MAX_4_5(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_NA, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_3_MAX_NA(...) __VA_ARGS__
#endif

#else
#define CC_GL_VERSION_ACTIVE_MIN_1_3(max, ...)
#endif

#if CC_GL_VERSION_MIN_REQUIRED(CC_OPENGL_VERSION_1_4, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_4(max, ...) CC_GL_VERSION_ACTIVE_MIN_1_4_MAX_##max(__VA_ARGS__)

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_0, CC_OPENGL_ES_VERSION_1_0)
#define CC_GL_VERSION_ACTIVE_MIN_1_4_MAX_1_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_4_MAX_1_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_1, CC_OPENGL_ES_VERSION_1_1)
#define CC_GL_VERSION_ACTIVE_MIN_1_4_MAX_1_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_4_MAX_1_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_2, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_4_MAX_1_2(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_4_MAX_1_2(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_2_1, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_4_MAX_1_2_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_4_MAX_1_2_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_3, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_4_MAX_1_3(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_4_MAX_1_3(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_4, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_4_MAX_1_4(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_4_MAX_1_4(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_5, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_4_MAX_1_5(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_4_MAX_1_5(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_2_0, CC_OPENGL_ES_VERSION_2_0)
#define CC_GL_VERSION_ACTIVE_MIN_1_4_MAX_2_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_4_MAX_2_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_2_1, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_4_MAX_2_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_4_MAX_2_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_0, CC_OPENGL_ES_VERSION_3_0)
#define CC_GL_VERSION_ACTIVE_MIN_1_4_MAX_3_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_4_MAX_3_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_1, CC_OPENGL_ES_VERSION_3_1)
#define CC_GL_VERSION_ACTIVE_MIN_1_4_MAX_3_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_4_MAX_3_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_2, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_4_MAX_3_2(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_4_MAX_3_2(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_3, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_4_MAX_3_3(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_4_MAX_3_3(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_0, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_4_MAX_4_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_4_MAX_4_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_1, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_4_MAX_4_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_4_MAX_4_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_2, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_4_MAX_4_2(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_4_MAX_4_2(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_3, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_4_MAX_4_3(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_4_MAX_4_3(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_4, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_4_MAX_4_4(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_4_MAX_4_4(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_5, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_4_MAX_4_5(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_4_MAX_4_5(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_NA, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_4_MAX_NA(...) __VA_ARGS__
#endif

#else
#define CC_GL_VERSION_ACTIVE_MIN_1_4(max, ...)
#endif

#if CC_GL_VERSION_MIN_REQUIRED(CC_OPENGL_VERSION_1_5, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_5(max, ...) CC_GL_VERSION_ACTIVE_MIN_1_5_MAX_##max(__VA_ARGS__)

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_0, CC_OPENGL_ES_VERSION_1_0)
#define CC_GL_VERSION_ACTIVE_MIN_1_5_MAX_1_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_5_MAX_1_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_1, CC_OPENGL_ES_VERSION_1_1)
#define CC_GL_VERSION_ACTIVE_MIN_1_5_MAX_1_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_5_MAX_1_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_2, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_5_MAX_1_2(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_5_MAX_1_2(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_2_1, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_5_MAX_1_2_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_5_MAX_1_2_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_3, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_5_MAX_1_3(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_5_MAX_1_3(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_4, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_5_MAX_1_4(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_5_MAX_1_4(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_5, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_5_MAX_1_5(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_5_MAX_1_5(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_2_0, CC_OPENGL_ES_VERSION_2_0)
#define CC_GL_VERSION_ACTIVE_MIN_1_5_MAX_2_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_5_MAX_2_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_2_1, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_5_MAX_2_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_5_MAX_2_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_0, CC_OPENGL_ES_VERSION_3_0)
#define CC_GL_VERSION_ACTIVE_MIN_1_5_MAX_3_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_5_MAX_3_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_1, CC_OPENGL_ES_VERSION_3_1)
#define CC_GL_VERSION_ACTIVE_MIN_1_5_MAX_3_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_5_MAX_3_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_2, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_5_MAX_3_2(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_5_MAX_3_2(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_3, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_5_MAX_3_3(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_5_MAX_3_3(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_0, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_5_MAX_4_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_5_MAX_4_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_1, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_5_MAX_4_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_5_MAX_4_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_2, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_5_MAX_4_2(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_5_MAX_4_2(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_3, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_5_MAX_4_3(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_5_MAX_4_3(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_4, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_5_MAX_4_4(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_5_MAX_4_4(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_5, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_5_MAX_4_5(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_1_5_MAX_4_5(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_NA, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_1_5_MAX_NA(...) __VA_ARGS__
#endif

#else
#define CC_GL_VERSION_ACTIVE_MIN_1_5(max, ...)
#endif

#if CC_GL_VERSION_MIN_REQUIRED(CC_OPENGL_VERSION_2_0, CC_OPENGL_ES_VERSION_2_0)
#define CC_GL_VERSION_ACTIVE_MIN_2_0(max, ...) CC_GL_VERSION_ACTIVE_MIN_2_0_MAX_##max(__VA_ARGS__)

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_0, CC_OPENGL_ES_VERSION_1_0)
#define CC_GL_VERSION_ACTIVE_MIN_2_0_MAX_1_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_2_0_MAX_1_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_1, CC_OPENGL_ES_VERSION_1_1)
#define CC_GL_VERSION_ACTIVE_MIN_2_0_MAX_1_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_2_0_MAX_1_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_2, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_2_0_MAX_1_2(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_2_0_MAX_1_2(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_2_1, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_2_0_MAX_1_2_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_2_0_MAX_1_2_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_3, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_2_0_MAX_1_3(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_2_0_MAX_1_3(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_4, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_2_0_MAX_1_4(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_2_0_MAX_1_4(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_5, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_2_0_MAX_1_5(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_2_0_MAX_1_5(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_2_0, CC_OPENGL_ES_VERSION_2_0)
#define CC_GL_VERSION_ACTIVE_MIN_2_0_MAX_2_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_2_0_MAX_2_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_2_1, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_2_0_MAX_2_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_2_0_MAX_2_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_0, CC_OPENGL_ES_VERSION_3_0)
#define CC_GL_VERSION_ACTIVE_MIN_2_0_MAX_3_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_2_0_MAX_3_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_1, CC_OPENGL_ES_VERSION_3_1)
#define CC_GL_VERSION_ACTIVE_MIN_2_0_MAX_3_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_2_0_MAX_3_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_2, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_2_0_MAX_3_2(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_2_0_MAX_3_2(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_3, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_2_0_MAX_3_3(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_2_0_MAX_3_3(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_0, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_2_0_MAX_4_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_2_0_MAX_4_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_1, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_2_0_MAX_4_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_2_0_MAX_4_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_2, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_2_0_MAX_4_2(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_2_0_MAX_4_2(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_3, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_2_0_MAX_4_3(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_2_0_MAX_4_3(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_4, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_2_0_MAX_4_4(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_2_0_MAX_4_4(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_5, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_2_0_MAX_4_5(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_2_0_MAX_4_5(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_NA, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_2_0_MAX_NA(...) __VA_ARGS__
#endif

#else
#define CC_GL_VERSION_ACTIVE_MIN_2_0(max, ...)
#endif

#if CC_GL_VERSION_MIN_REQUIRED(CC_OPENGL_VERSION_2_1, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_2_1(max, ...) CC_GL_VERSION_ACTIVE_MIN_2_1_MAX_##max(__VA_ARGS__)

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_0, CC_OPENGL_ES_VERSION_1_0)
#define CC_GL_VERSION_ACTIVE_MIN_2_1_MAX_1_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_2_1_MAX_1_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_1, CC_OPENGL_ES_VERSION_1_1)
#define CC_GL_VERSION_ACTIVE_MIN_2_1_MAX_1_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_2_1_MAX_1_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_2, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_2_1_MAX_1_2(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_2_1_MAX_1_2(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_2_1, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_2_1_MAX_1_2_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_2_1_MAX_1_2_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_3, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_2_1_MAX_1_3(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_2_1_MAX_1_3(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_4, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_2_1_MAX_1_4(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_2_1_MAX_1_4(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_5, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_2_1_MAX_1_5(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_2_1_MAX_1_5(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_2_0, CC_OPENGL_ES_VERSION_2_0)
#define CC_GL_VERSION_ACTIVE_MIN_2_1_MAX_2_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_2_1_MAX_2_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_2_1, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_2_1_MAX_2_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_2_1_MAX_2_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_0, CC_OPENGL_ES_VERSION_3_0)
#define CC_GL_VERSION_ACTIVE_MIN_2_1_MAX_3_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_2_1_MAX_3_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_1, CC_OPENGL_ES_VERSION_3_1)
#define CC_GL_VERSION_ACTIVE_MIN_2_1_MAX_3_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_2_1_MAX_3_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_2, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_2_1_MAX_3_2(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_2_1_MAX_3_2(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_3, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_2_1_MAX_3_3(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_2_1_MAX_3_3(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_0, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_2_1_MAX_4_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_2_1_MAX_4_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_1, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_2_1_MAX_4_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_2_1_MAX_4_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_2, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_2_1_MAX_4_2(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_2_1_MAX_4_2(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_3, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_2_1_MAX_4_3(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_2_1_MAX_4_3(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_4, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_2_1_MAX_4_4(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_2_1_MAX_4_4(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_5, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_2_1_MAX_4_5(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_2_1_MAX_4_5(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_NA, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_2_1_MAX_NA(...) __VA_ARGS__
#endif

#else
#define CC_GL_VERSION_ACTIVE_MIN_2_1(max, ...)
#endif

#if CC_GL_VERSION_MIN_REQUIRED(CC_OPENGL_VERSION_3_0, CC_OPENGL_ES_VERSION_3_0)
#define CC_GL_VERSION_ACTIVE_MIN_3_0(max, ...) CC_GL_VERSION_ACTIVE_MIN_3_0_MAX_##max(__VA_ARGS__)

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_0, CC_OPENGL_ES_VERSION_1_0)
#define CC_GL_VERSION_ACTIVE_MIN_3_0_MAX_1_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_0_MAX_1_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_1, CC_OPENGL_ES_VERSION_1_1)
#define CC_GL_VERSION_ACTIVE_MIN_3_0_MAX_1_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_0_MAX_1_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_2, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_3_0_MAX_1_2(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_0_MAX_1_2(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_2_1, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_3_0_MAX_1_2_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_0_MAX_1_2_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_3, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_3_0_MAX_1_3(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_0_MAX_1_3(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_4, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_3_0_MAX_1_4(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_0_MAX_1_4(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_5, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_3_0_MAX_1_5(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_0_MAX_1_5(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_2_0, CC_OPENGL_ES_VERSION_2_0)
#define CC_GL_VERSION_ACTIVE_MIN_3_0_MAX_2_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_0_MAX_2_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_2_1, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_3_0_MAX_2_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_0_MAX_2_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_0, CC_OPENGL_ES_VERSION_3_0)
#define CC_GL_VERSION_ACTIVE_MIN_3_0_MAX_3_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_0_MAX_3_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_1, CC_OPENGL_ES_VERSION_3_1)
#define CC_GL_VERSION_ACTIVE_MIN_3_0_MAX_3_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_0_MAX_3_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_2, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_3_0_MAX_3_2(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_0_MAX_3_2(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_3, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_3_0_MAX_3_3(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_0_MAX_3_3(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_0, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_3_0_MAX_4_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_0_MAX_4_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_1, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_3_0_MAX_4_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_0_MAX_4_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_2, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_3_0_MAX_4_2(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_0_MAX_4_2(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_3, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_3_0_MAX_4_3(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_0_MAX_4_3(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_4, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_3_0_MAX_4_4(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_0_MAX_4_4(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_5, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_3_0_MAX_4_5(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_0_MAX_4_5(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_NA, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_3_0_MAX_NA(...) __VA_ARGS__
#endif

#else
#define CC_GL_VERSION_ACTIVE_MIN_3_0(max, ...)
#endif

#if CC_GL_VERSION_MIN_REQUIRED(CC_OPENGL_VERSION_3_1, CC_OPENGL_ES_VERSION_3_1)
#define CC_GL_VERSION_ACTIVE_MIN_3_1(max, ...) CC_GL_VERSION_ACTIVE_MIN_3_1_MAX_##max(__VA_ARGS__)

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_0, CC_OPENGL_ES_VERSION_1_0)
#define CC_GL_VERSION_ACTIVE_MIN_3_1_MAX_1_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_1_MAX_1_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_1, CC_OPENGL_ES_VERSION_1_1)
#define CC_GL_VERSION_ACTIVE_MIN_3_1_MAX_1_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_1_MAX_1_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_2, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_3_1_MAX_1_2(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_1_MAX_1_2(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_2_1, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_3_1_MAX_1_2_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_1_MAX_1_2_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_3, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_3_1_MAX_1_3(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_1_MAX_1_3(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_4, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_3_1_MAX_1_4(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_1_MAX_1_4(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_5, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_3_1_MAX_1_5(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_1_MAX_1_5(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_2_0, CC_OPENGL_ES_VERSION_2_0)
#define CC_GL_VERSION_ACTIVE_MIN_3_1_MAX_2_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_1_MAX_2_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_2_1, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_3_1_MAX_2_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_1_MAX_2_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_0, CC_OPENGL_ES_VERSION_3_0)
#define CC_GL_VERSION_ACTIVE_MIN_3_1_MAX_3_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_1_MAX_3_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_1, CC_OPENGL_ES_VERSION_3_1)
#define CC_GL_VERSION_ACTIVE_MIN_3_1_MAX_3_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_1_MAX_3_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_2, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_3_1_MAX_3_2(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_1_MAX_3_2(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_3, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_3_1_MAX_3_3(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_1_MAX_3_3(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_0, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_3_1_MAX_4_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_1_MAX_4_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_1, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_3_1_MAX_4_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_1_MAX_4_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_2, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_3_1_MAX_4_2(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_1_MAX_4_2(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_3, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_3_1_MAX_4_3(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_1_MAX_4_3(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_4, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_3_1_MAX_4_4(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_1_MAX_4_4(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_5, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_3_1_MAX_4_5(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_1_MAX_4_5(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_NA, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_3_1_MAX_NA(...) __VA_ARGS__
#endif

#else
#define CC_GL_VERSION_ACTIVE_MIN_3_1(max, ...)
#endif

#if CC_GL_VERSION_MIN_REQUIRED(CC_OPENGL_VERSION_3_2, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_3_2(max, ...) CC_GL_VERSION_ACTIVE_MIN_3_2_MAX_##max(__VA_ARGS__)

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_0, CC_OPENGL_ES_VERSION_1_0)
#define CC_GL_VERSION_ACTIVE_MIN_3_2_MAX_1_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_2_MAX_1_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_1, CC_OPENGL_ES_VERSION_1_1)
#define CC_GL_VERSION_ACTIVE_MIN_3_2_MAX_1_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_2_MAX_1_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_2, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_3_2_MAX_1_2(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_2_MAX_1_2(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_2_1, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_3_2_MAX_1_2_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_2_MAX_1_2_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_3, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_3_2_MAX_1_3(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_2_MAX_1_3(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_4, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_3_2_MAX_1_4(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_2_MAX_1_4(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_5, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_3_2_MAX_1_5(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_2_MAX_1_5(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_2_0, CC_OPENGL_ES_VERSION_2_0)
#define CC_GL_VERSION_ACTIVE_MIN_3_2_MAX_2_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_2_MAX_2_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_2_1, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_3_2_MAX_2_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_2_MAX_2_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_0, CC_OPENGL_ES_VERSION_3_0)
#define CC_GL_VERSION_ACTIVE_MIN_3_2_MAX_3_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_2_MAX_3_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_1, CC_OPENGL_ES_VERSION_3_1)
#define CC_GL_VERSION_ACTIVE_MIN_3_2_MAX_3_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_2_MAX_3_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_2, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_3_2_MAX_3_2(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_2_MAX_3_2(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_3, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_3_2_MAX_3_3(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_2_MAX_3_3(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_0, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_3_2_MAX_4_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_2_MAX_4_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_1, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_3_2_MAX_4_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_2_MAX_4_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_2, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_3_2_MAX_4_2(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_2_MAX_4_2(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_3, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_3_2_MAX_4_3(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_2_MAX_4_3(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_4, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_3_2_MAX_4_4(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_2_MAX_4_4(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_5, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_3_2_MAX_4_5(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_2_MAX_4_5(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_NA, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_3_2_MAX_NA(...) __VA_ARGS__
#endif

#else
#define CC_GL_VERSION_ACTIVE_MIN_3_2(max, ...)
#endif

#if CC_GL_VERSION_MIN_REQUIRED(CC_OPENGL_VERSION_3_3, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_3_3(max, ...) CC_GL_VERSION_ACTIVE_MIN_3_3_MAX_##max(__VA_ARGS__)

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_0, CC_OPENGL_ES_VERSION_1_0)
#define CC_GL_VERSION_ACTIVE_MIN_3_3_MAX_1_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_3_MAX_1_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_1, CC_OPENGL_ES_VERSION_1_1)
#define CC_GL_VERSION_ACTIVE_MIN_3_3_MAX_1_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_3_MAX_1_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_2, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_3_3_MAX_1_2(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_3_MAX_1_2(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_2_1, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_3_3_MAX_1_2_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_3_MAX_1_2_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_3, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_3_3_MAX_1_3(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_3_MAX_1_3(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_4, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_3_3_MAX_1_4(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_3_MAX_1_4(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_5, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_3_3_MAX_1_5(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_3_MAX_1_5(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_2_0, CC_OPENGL_ES_VERSION_2_0)
#define CC_GL_VERSION_ACTIVE_MIN_3_3_MAX_2_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_3_MAX_2_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_2_1, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_3_3_MAX_2_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_3_MAX_2_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_0, CC_OPENGL_ES_VERSION_3_0)
#define CC_GL_VERSION_ACTIVE_MIN_3_3_MAX_3_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_3_MAX_3_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_1, CC_OPENGL_ES_VERSION_3_1)
#define CC_GL_VERSION_ACTIVE_MIN_3_3_MAX_3_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_3_MAX_3_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_2, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_3_3_MAX_3_2(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_3_MAX_3_2(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_3, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_3_3_MAX_3_3(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_3_MAX_3_3(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_0, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_3_3_MAX_4_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_3_MAX_4_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_1, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_3_3_MAX_4_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_3_MAX_4_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_2, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_3_3_MAX_4_2(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_3_MAX_4_2(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_3, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_3_3_MAX_4_3(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_3_MAX_4_3(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_4, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_3_3_MAX_4_4(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_3_MAX_4_4(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_5, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_3_3_MAX_4_5(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_3_3_MAX_4_5(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_NA, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_3_3_MAX_NA(...) __VA_ARGS__
#endif

#else
#define CC_GL_VERSION_ACTIVE_MIN_3_3(max, ...)
#endif

#if CC_GL_VERSION_MIN_REQUIRED(CC_OPENGL_VERSION_4_0, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_0(max, ...) CC_GL_VERSION_ACTIVE_MIN_4_0_MAX_##max(__VA_ARGS__)

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_0, CC_OPENGL_ES_VERSION_1_0)
#define CC_GL_VERSION_ACTIVE_MIN_4_0_MAX_1_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_0_MAX_1_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_1, CC_OPENGL_ES_VERSION_1_1)
#define CC_GL_VERSION_ACTIVE_MIN_4_0_MAX_1_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_0_MAX_1_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_2, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_0_MAX_1_2(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_0_MAX_1_2(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_2_1, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_0_MAX_1_2_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_0_MAX_1_2_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_3, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_0_MAX_1_3(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_0_MAX_1_3(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_4, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_0_MAX_1_4(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_0_MAX_1_4(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_5, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_0_MAX_1_5(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_0_MAX_1_5(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_2_0, CC_OPENGL_ES_VERSION_2_0)
#define CC_GL_VERSION_ACTIVE_MIN_4_0_MAX_2_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_0_MAX_2_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_2_1, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_0_MAX_2_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_0_MAX_2_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_0, CC_OPENGL_ES_VERSION_3_0)
#define CC_GL_VERSION_ACTIVE_MIN_4_0_MAX_3_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_0_MAX_3_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_1, CC_OPENGL_ES_VERSION_3_1)
#define CC_GL_VERSION_ACTIVE_MIN_4_0_MAX_3_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_0_MAX_3_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_2, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_0_MAX_3_2(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_0_MAX_3_2(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_3, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_0_MAX_3_3(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_0_MAX_3_3(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_0, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_0_MAX_4_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_0_MAX_4_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_1, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_0_MAX_4_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_0_MAX_4_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_2, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_0_MAX_4_2(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_0_MAX_4_2(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_3, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_0_MAX_4_3(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_0_MAX_4_3(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_4, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_0_MAX_4_4(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_0_MAX_4_4(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_5, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_0_MAX_4_5(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_0_MAX_4_5(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_NA, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_0_MAX_NA(...) __VA_ARGS__
#endif

#else
#define CC_GL_VERSION_ACTIVE_MIN_4_0(max, ...)
#endif

#if CC_GL_VERSION_MIN_REQUIRED(CC_OPENGL_VERSION_4_1, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_1(max, ...) CC_GL_VERSION_ACTIVE_MIN_4_1_MAX_##max(__VA_ARGS__)

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_0, CC_OPENGL_ES_VERSION_1_0)
#define CC_GL_VERSION_ACTIVE_MIN_4_1_MAX_1_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_1_MAX_1_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_1, CC_OPENGL_ES_VERSION_1_1)
#define CC_GL_VERSION_ACTIVE_MIN_4_1_MAX_1_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_1_MAX_1_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_2, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_1_MAX_1_2(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_1_MAX_1_2(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_2_1, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_1_MAX_1_2_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_1_MAX_1_2_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_3, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_1_MAX_1_3(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_1_MAX_1_3(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_4, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_1_MAX_1_4(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_1_MAX_1_4(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_5, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_1_MAX_1_5(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_1_MAX_1_5(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_2_0, CC_OPENGL_ES_VERSION_2_0)
#define CC_GL_VERSION_ACTIVE_MIN_4_1_MAX_2_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_1_MAX_2_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_2_1, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_1_MAX_2_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_1_MAX_2_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_0, CC_OPENGL_ES_VERSION_3_0)
#define CC_GL_VERSION_ACTIVE_MIN_4_1_MAX_3_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_1_MAX_3_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_1, CC_OPENGL_ES_VERSION_3_1)
#define CC_GL_VERSION_ACTIVE_MIN_4_1_MAX_3_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_1_MAX_3_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_2, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_1_MAX_3_2(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_1_MAX_3_2(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_3, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_1_MAX_3_3(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_1_MAX_3_3(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_0, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_1_MAX_4_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_1_MAX_4_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_1, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_1_MAX_4_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_1_MAX_4_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_2, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_1_MAX_4_2(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_1_MAX_4_2(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_3, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_1_MAX_4_3(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_1_MAX_4_3(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_4, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_1_MAX_4_4(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_1_MAX_4_4(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_5, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_1_MAX_4_5(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_1_MAX_4_5(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_NA, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_1_MAX_NA(...) __VA_ARGS__
#endif

#else
#define CC_GL_VERSION_ACTIVE_MIN_4_1(max, ...)
#endif

#if CC_GL_VERSION_MIN_REQUIRED(CC_OPENGL_VERSION_4_2, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_2(max, ...) CC_GL_VERSION_ACTIVE_MIN_4_2_MAX_##max(__VA_ARGS__)

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_0, CC_OPENGL_ES_VERSION_1_0)
#define CC_GL_VERSION_ACTIVE_MIN_4_2_MAX_1_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_2_MAX_1_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_1, CC_OPENGL_ES_VERSION_1_1)
#define CC_GL_VERSION_ACTIVE_MIN_4_2_MAX_1_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_2_MAX_1_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_2, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_2_MAX_1_2(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_2_MAX_1_2(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_2_1, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_2_MAX_1_2_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_2_MAX_1_2_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_3, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_2_MAX_1_3(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_2_MAX_1_3(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_4, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_2_MAX_1_4(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_2_MAX_1_4(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_5, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_2_MAX_1_5(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_2_MAX_1_5(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_2_0, CC_OPENGL_ES_VERSION_2_0)
#define CC_GL_VERSION_ACTIVE_MIN_4_2_MAX_2_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_2_MAX_2_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_2_1, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_2_MAX_2_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_2_MAX_2_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_0, CC_OPENGL_ES_VERSION_3_0)
#define CC_GL_VERSION_ACTIVE_MIN_4_2_MAX_3_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_2_MAX_3_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_1, CC_OPENGL_ES_VERSION_3_1)
#define CC_GL_VERSION_ACTIVE_MIN_4_2_MAX_3_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_2_MAX_3_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_2, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_2_MAX_3_2(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_2_MAX_3_2(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_3, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_2_MAX_3_3(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_2_MAX_3_3(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_0, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_2_MAX_4_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_2_MAX_4_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_1, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_2_MAX_4_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_2_MAX_4_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_2, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_2_MAX_4_2(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_2_MAX_4_2(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_3, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_2_MAX_4_3(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_2_MAX_4_3(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_4, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_2_MAX_4_4(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_2_MAX_4_4(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_5, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_2_MAX_4_5(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_2_MAX_4_5(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_NA, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_2_MAX_NA(...) __VA_ARGS__
#endif

#else
#define CC_GL_VERSION_ACTIVE_MIN_4_2(max, ...)
#endif

#if CC_GL_VERSION_MIN_REQUIRED(CC_OPENGL_VERSION_4_3, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_3(max, ...) CC_GL_VERSION_ACTIVE_MIN_4_3_MAX_##max(__VA_ARGS__)

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_0, CC_OPENGL_ES_VERSION_1_0)
#define CC_GL_VERSION_ACTIVE_MIN_4_3_MAX_1_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_3_MAX_1_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_1, CC_OPENGL_ES_VERSION_1_1)
#define CC_GL_VERSION_ACTIVE_MIN_4_3_MAX_1_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_3_MAX_1_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_2, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_3_MAX_1_2(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_3_MAX_1_2(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_2_1, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_3_MAX_1_2_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_3_MAX_1_2_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_3, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_3_MAX_1_3(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_3_MAX_1_3(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_4, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_3_MAX_1_4(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_3_MAX_1_4(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_5, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_3_MAX_1_5(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_3_MAX_1_5(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_2_0, CC_OPENGL_ES_VERSION_2_0)
#define CC_GL_VERSION_ACTIVE_MIN_4_3_MAX_2_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_3_MAX_2_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_2_1, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_3_MAX_2_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_3_MAX_2_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_0, CC_OPENGL_ES_VERSION_3_0)
#define CC_GL_VERSION_ACTIVE_MIN_4_3_MAX_3_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_3_MAX_3_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_1, CC_OPENGL_ES_VERSION_3_1)
#define CC_GL_VERSION_ACTIVE_MIN_4_3_MAX_3_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_3_MAX_3_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_2, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_3_MAX_3_2(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_3_MAX_3_2(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_3, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_3_MAX_3_3(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_3_MAX_3_3(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_0, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_3_MAX_4_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_3_MAX_4_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_1, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_3_MAX_4_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_3_MAX_4_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_2, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_3_MAX_4_2(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_3_MAX_4_2(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_3, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_3_MAX_4_3(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_3_MAX_4_3(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_4, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_3_MAX_4_4(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_3_MAX_4_4(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_5, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_3_MAX_4_5(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_3_MAX_4_5(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_NA, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_3_MAX_NA(...) __VA_ARGS__
#endif

#else
#define CC_GL_VERSION_ACTIVE_MIN_4_3(max, ...)
#endif

#if CC_GL_VERSION_MIN_REQUIRED(CC_OPENGL_VERSION_4_4, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_4(max, ...) CC_GL_VERSION_ACTIVE_MIN_4_4_MAX_##max(__VA_ARGS__)

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_0, CC_OPENGL_ES_VERSION_1_0)
#define CC_GL_VERSION_ACTIVE_MIN_4_4_MAX_1_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_4_MAX_1_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_1, CC_OPENGL_ES_VERSION_1_1)
#define CC_GL_VERSION_ACTIVE_MIN_4_4_MAX_1_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_4_MAX_1_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_2, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_4_MAX_1_2(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_4_MAX_1_2(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_2_1, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_4_MAX_1_2_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_4_MAX_1_2_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_3, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_4_MAX_1_3(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_4_MAX_1_3(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_4, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_4_MAX_1_4(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_4_MAX_1_4(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_5, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_4_MAX_1_5(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_4_MAX_1_5(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_2_0, CC_OPENGL_ES_VERSION_2_0)
#define CC_GL_VERSION_ACTIVE_MIN_4_4_MAX_2_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_4_MAX_2_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_2_1, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_4_MAX_2_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_4_MAX_2_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_0, CC_OPENGL_ES_VERSION_3_0)
#define CC_GL_VERSION_ACTIVE_MIN_4_4_MAX_3_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_4_MAX_3_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_1, CC_OPENGL_ES_VERSION_3_1)
#define CC_GL_VERSION_ACTIVE_MIN_4_4_MAX_3_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_4_MAX_3_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_2, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_4_MAX_3_2(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_4_MAX_3_2(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_3, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_4_MAX_3_3(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_4_MAX_3_3(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_0, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_4_MAX_4_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_4_MAX_4_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_1, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_4_MAX_4_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_4_MAX_4_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_2, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_4_MAX_4_2(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_4_MAX_4_2(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_3, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_4_MAX_4_3(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_4_MAX_4_3(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_4, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_4_MAX_4_4(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_4_MAX_4_4(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_5, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_4_MAX_4_5(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_4_MAX_4_5(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_NA, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_4_MAX_NA(...) __VA_ARGS__
#endif

#else
#define CC_GL_VERSION_ACTIVE_MIN_4_4(max, ...)
#endif

#if CC_GL_VERSION_MIN_REQUIRED(CC_OPENGL_VERSION_4_5, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_5(max, ...) CC_GL_VERSION_ACTIVE_MIN_4_5_MAX_##max(__VA_ARGS__)

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_0, CC_OPENGL_ES_VERSION_1_0)
#define CC_GL_VERSION_ACTIVE_MIN_4_5_MAX_1_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_5_MAX_1_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_1, CC_OPENGL_ES_VERSION_1_1)
#define CC_GL_VERSION_ACTIVE_MIN_4_5_MAX_1_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_5_MAX_1_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_2, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_5_MAX_1_2(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_5_MAX_1_2(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_2_1, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_5_MAX_1_2_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_5_MAX_1_2_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_3, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_5_MAX_1_3(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_5_MAX_1_3(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_4, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_5_MAX_1_4(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_5_MAX_1_4(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_1_5, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_5_MAX_1_5(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_5_MAX_1_5(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_2_0, CC_OPENGL_ES_VERSION_2_0)
#define CC_GL_VERSION_ACTIVE_MIN_4_5_MAX_2_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_5_MAX_2_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_2_1, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_5_MAX_2_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_5_MAX_2_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_0, CC_OPENGL_ES_VERSION_3_0)
#define CC_GL_VERSION_ACTIVE_MIN_4_5_MAX_3_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_5_MAX_3_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_1, CC_OPENGL_ES_VERSION_3_1)
#define CC_GL_VERSION_ACTIVE_MIN_4_5_MAX_3_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_5_MAX_3_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_2, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_5_MAX_3_2(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_5_MAX_3_2(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_3_3, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_5_MAX_3_3(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_5_MAX_3_3(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_0, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_5_MAX_4_0(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_5_MAX_4_0(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_1, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_5_MAX_4_1(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_5_MAX_4_1(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_2, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_5_MAX_4_2(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_5_MAX_4_2(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_3, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_5_MAX_4_3(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_5_MAX_4_3(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_4, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_5_MAX_4_4(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_5_MAX_4_4(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_4_5, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_5_MAX_4_5(...) __VA_ARGS__
#else
#define CC_GL_VERSION_ACTIVE_MIN_4_5_MAX_4_5(...)
#endif

#if CC_GL_VERSION_MAX_SUPPORTED(CC_OPENGL_VERSION_NA, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_4_5_MAX_NA(...) __VA_ARGS__
#endif

#else
#define CC_GL_VERSION_ACTIVE_MIN_4_5(max, ...)
#endif

#if CC_GL_VERSION_MIN_REQUIRED(CC_OPENGL_VERSION_NA, CC_OPENGL_ES_VERSION_NA)
#define CC_GL_VERSION_ACTIVE_MIN_NA(max, ...)
#else
#define CC_GL_VERSION_ACTIVE_MIN_NA(max, ...)
#endif


#define CC_GL_VERSION_ACTIVE_(min, max, ...) CC_GL_VERSION_ACTIVE_MIN_##min(max, __VA_ARGS__)


#if CC_OPENGL
#define CC_GL_VERSION_ACTIVE(glmin, glmax, glesmin, glesmax, ...) CC_GL_VERSION_ACTIVE_(glmin, glmax, __VA_ARGS__)
#elif CC_OPENGL_ES
#define CC_GL_VERSION_ACTIVE(glmin, glmax, glesmin, glesmax, ...) CC_GL_VERSION_ACTIVE_(glesmin, glesmax, __VA_ARGS__)
#else
#define CC_GL_VERSION_ACTIVE(glmin, glmax, glesmin, glesmax, ...)
#endif

#endif
